### ISSUE TITLE
Would a Stretch flavor be possible?

### ISSUE THREAD

**Issue by jrabbit** [docker-library/python#104]
I was using python:2.7-slim with stretch for a while and got hit by a version incompatibility b/t gnupg and taskd without a non-aptitude type solution.

**Comment by yosifkit** [comment]
I think that right now Debian Stretch is too early in the cycle to promote as a stable base for language stacks.  Since you are already using `slim`, have you tried the `python:2.7-alpine` version?  It usually has newer packages to install (though it may require using the `edge` apk repository).

**Comment by gcbirzan** [comment]
This should probably be revised, now that Stretch is frozen.

**Comment by SpoonMeiser** [comment]
I would like to see a 2.7 stretch image too; we can't use the alpine images because they are incompatible with manylinux1 wheels.

**Comment by daveisfera** [comment]
The list is of options is starting to get long, but what are the thoughts on having a slim variant based on stretch?

**Comment by yosifkit** [comment]
We do have stretch based images for 2.7, 3.6, and 3.7 (https://github.com/docker-library/python/pull/215).  As for `slim` variant of stretch, we'll track that in #219.
