### ISSUE TITLE
Add dbm support

### ISSUE THREAD

**Issue by jgehrcke** [docker-library/python#105]
The `python:2.7` package yields `ImportError: No module named dbm` upon `import dbm`. I have reported https://github.com/docker-library/buildpack-deps/issues/44 because I think that buildpack is the right place to add the header files. But I guess that a "Add dbm support" ticket is also important for you guys to keep track of it.

**Comment by tianon** [comment]
Yeah, for sure!  I think we probably need to do something for the `slim` and `alpine` variants too (which don't use `buildpack-deps`), so we'll likely need to update our `python-imports` test. :+1:

**Comment by tianon** [comment]
Looks like the impact of this is really minimal -- https://github.com/docker-library/official-images/issues/2033 shows that only Python 2.7 `alpine` and `slim` variants need to be updated now. :+1:

**Comment by tianon** [comment]
Test update is merged; working on a PR for fixing `2.7-slim` and `2.7-alpine` now. :+1:
