### ISSUE TITLE
Upgrade base image to alpine:3.4

### ISSUE THREAD

**Issue by SirIle** [docker-library/python#113]
The new alpine:3.4 base image should fix the issue with dns resolving not being able to use search-attribute in the etc/resolv.conf as described for example in https://github.com/gliderlabs/docker-alpine/issues/8. This would allow using this image as base for containers in Docker Cloud and on Kubernetes that rely on this functionality for the service discovery to work.

**Comment by tianon** [comment]
https://github.com/docker-library/python/commit/0610d9ccc2dc8ad4ab6038f775e7a28cadf12114 :+1:
