### ISSUE TITLE
make: *** [libinstall] Error 1 while installing python 2.7.11

### ISSUE THREAD

**Issue by manycoding** [docker-library/python#114]
I am not exactly using this container, I just copy pasted everything into mine, but lately I am not able to build python, which files with this error:

Compiling /usr/local/lib/python2.7/zipfile.py ...
make: *** [libinstall] Error 1

Here is some piece of the console output:
http://piratepad.net/ep/pad/view/ro.gl0rcJXb3s8/latest
And here is my old dockerfile https://github.com/manycoding/teamcity-agent-robotframework-docker/commit/bc2a2b3566f7e68c3edc8bdc22a75dc26641442b

Does anyone have any ideas perhaps?

**Comment by lijian8** [comment]
I got same error, any suggestion? Thanks.

**Comment by manycoding** [comment]
Well, I just installed python from ppa:fkrull/deadsnakes-python2.7

**Comment by tianon** [comment]
This appears to be related:
```
Compiling /usr/local/lib/python2.7/dist-packages/enum/py35_test_enum.py ...
  File "/usr/local/lib/python2.7/dist-packages/enum/py35_test_enum.py", line 974
    class AutoNumberedEnum(Enum, metaclass=auto_enum):
                                          ^
SyntaxError: invalid syntax
```

**Comment by lega911** [comment]
I had the same problem building 2.7.14, I fix it removing /usr/lib/python2.x and /usr/local/lib/python2.x

**Comment by kutex09** [comment]
@lega911 Thanks very much. It worked just a while ago for python2.7.14

**Comment by pallavbakshi** [comment]
@lega911 Hey! Thanks for the response. But ain't we supposed to not delete python2.x files since Ubuntu/Linux system depends upon them. I checked some question on stackoverflow about uninstalling python2.7 but most of them recommended me to not uninstall it. Is it safe to delete the files in lieu of python 2.7.14?

https://askubuntu.com/questions/315015/how-can-i-remove-python-2-7-after-installing-python-3-3

**Comment by lega911** [comment]
@pallavbakshi
I removed files inside of the docker just to build deb package, after that I can install this deb normally, without removing (on another system/container). Also you can try to choose another folder for python to prevent conflicts.

**Comment by KylixC** [comment]
yeh...
update python2.7.6 to python2.7.14, find the same problem...

mv /usr/lib/python2.7  /usr/lib/badpython2.7

of curse, i install python to /usr/bin
like this
mkdir build
cd build
../configure --prefix=/usr/
make
make install

mv /usr/lib/python2.7  /usr/lib/badpython2.7

make install

done



3KS

**Comment by schrodervictor** [comment]
As @KylixC noted above, the trick here is to remove the old python from the way, otherwise the commands during the installation will try to use the old one instead of the new one you've just built.

**Comment by jinhyuk-im** [comment]
> I had the same problem building 2.7.14, I fix it removing /usr/lib/python2.x and /usr/local/lib/python2.x

I had the same problem building 2.7.16, and I fixed it same solution.

**Comment by ndvbd** [comment]
But if you remove the /usr/local/lib you remove all the installed packages, aren't you?

**Comment by lega911** [comment]
@ndvbd /usr/local/lib != /usr/local/lib/python2.x
but today my recommendation would be to use docker-image without preinstalled python to build python, works fine many years
