### ISSUE TITLE
Possibly incorrect assumption that most people want virtualenv

### ISSUE THREAD

**Issue by samos123** [docker-library/python#115]
After inspecting the Dockerfile for 2.7.11:wheezy I noticed that virtualenv gets installed by default: https://github.com/docker-library/python/blob/9383f7d4d2f96068e8957651aa3588fee8b48f71/2.7/wheezy/Dockerfile

I don't need virtualenv as I'm using Docker to run a single service where docker already provides isolation of dependencies. I think most people won't actually need virtualenv but instead will use pip to install packages globally.

My suggestion is to remove the line to install virtualenv and reduce the image to be clean and unbiased.

**Comment by Starefossen** [comment]
While I generally agree with you, this will break backwards comparability for those relying on `virtualenv` being installed. This is a fundamental problem with the way Official Docker Images are tagged.

**Comment by tianon** [comment]
Do the `slim` and/or `alpine` variants of the image also install `virtualenv`, or do they appropriately abstain?

**Comment by ushuz** [comment]
@tianon `slim` `alpine` variants won't install `virtualenv`.

**Comment by yosifkit** [comment]
So it seems that the "include everything" approach for the default versions of python 2 does include `virtualenv` since python 3 includes `venv` and those who want more control over what is included should be using the smaller images like `slim` and `alpine`.
