### ISSUE TITLE
Python 2.7.12 - Pending release

### ISSUE THREAD

**Issue by mattrobenolt** [docker-library/python#117]
Do we want to get a tag going for the rc? Or just wait until GA?

https://www.python.org/downloads/release/python-2712rc1/

**Comment by tianon** [comment]
Given that it's not very easy for us to autodiscover these, I'm leaning towards a -1 unless there's definite demand for it (especially since this is "caveman Python" :smile:)

**Comment by mattrobenolt** [comment]
Yeah, that's why I opened issue rather than submit a PR for it. :)

I'll rename this for 2.7.12 release and I'll get PR for that when time comes.

**Comment by tianon** [comment]
Sounds good! :+1:
