### ISSUE TITLE
pkg-config, libfreetype6-dev missing

### ISSUE THREAD

**Issue by astopy** [docker-library/python#129]
It looks like as of yesterday `pkg-config` and `libfreetype6-dev` (and presumably other packages) are no longer in `python:2.7` (and presumably other tags). Was this deliberate and should I just start installing these myself in my images?

**Comment by kjmph** [comment]
My problem is that I rely on requirements.txt to install matplotlib. However, now I have to remove matplotlib from requirements.txt, apt-get install libfreetype6-dev and pkg-config, then execute pip install matplotlib with my own RUN command. It seems a bit unnecessary.

**Comment by mr-sk** [comment]
I'm suffering the same issue as @kjmph. Some feedback would be appreciated. Thanks.

**Comment by yosifkit** [comment]
Definitely not our intention to remove those packages.  I am looking over a build log and it looks like the [line 54](https://github.com/docker-library/python/blob/3e451a9b89bdaebeb3d5cb4f01f5843749deb867/2.7/Dockerfile#L54) is removing many more packages than it should be.

**Comment by adelescott** [comment]
Hi @yosifkit, do you have an ETA on when this fix will be merged into docker-library/official-images and available on the hub?  Our build has been broken for over a week now because of it.

**Comment by yosifkit** [comment]
Looks like it will be built and pushed once https://github.com/docker-library/official-images/pull/2005 is merged. Hopefully this afternoon.

**Comment by adelescott** [comment]
All working now, thanks @yosifkit.
