### ISSUE TITLE
uwsgi routing is broken with latest python:2.7

### ISSUE THREAD

**Issue by mozbhearsum** [docker-library/python#132]
I recently rebuilt some images that depend on the python:2.7 image. This app I'm running uses some uwsgi routing rules, and I discovered that it was broken after the rebuild. Digging into the log I found:
balrogadmin_1 | !!! no internal routing support, rebuild with pcre support !!!

If I add this to my Dockerfile, everything works again:
```RUN apt-get -q update && apt-get -q --yes install libpcre3 libpcre3-dev && apt-get clean```

I suspect that the ```apt-get purge --auto-remove``` from https://github.com/docker-library/python/commit/8d03a5036b0170c12ae422ed8f10169e8db9b30b#diff-d6ac67f048d96870edb1787bc2b3e17cR54 ends up removing libpcre3-dev, which causes uwsgi to install without routing support, though I'm not certain of that.

**Comment by yosifkit** [comment]
This should be fixed by https://github.com/docker-library/python/pull/131.  New images should be up on the hub later today (after a PR to docker-library/official-images).

**Comment by mozbhearsum** [comment]
Cheers!

**Comment by tianon** [comment]
#131 came and went, fixed a few things, broke a few others, and thus #137 has merged and should be up on the Hub very shortly
