### ISSUE TITLE
2.7.12 image breaks installation of several packages, e.g. lsb-release or supervisor

### ISSUE THREAD

**Issue by Bahus** [docker-library/python#138]
Here is the problem with the latest python image:

`docker run -it --rm python:2.7.12 /bin/bash`

```bash
> apt-get update 
> apt-get install -y lsb-release
> lsb_release
bash: /usr/bin/lsb_release: /usr/bin/python: bad interpreter: No such file or directory

> ls /usr/bin/python
ls: cannot access /usr/bin/python: No such file or directory
```

OK, this issue can be workarounded with symlink:

```bash
ln -s /usr/local/bin/python /usr/bin/python
> lsb_release
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 28, in <module>
    import lsb_release
ImportError: No module named lsb_release
```

Since new python version does not include `"/usr/lib/python2.7/dist-packages/"` in the **sys.path**, so lsb_release.py cannot be found. Workaround is under investigation, since PYTHONPATH is ignored by `/usr/bin/lsb_release`.

**Comment by kevin-brown** [comment]
There is a pretty good chance that this is a duplicate of https://github.com/docker-library/python/issues/133.

**Comment by Bahus** [comment]
Seems like it is. 
Actually there are two different issues, both are described in this comment: https://github.com/docker-library/python/issues/133#issuecomment-237570388

Can be closed.
