### ISSUE TITLE
Can't run Python process in the background

### ISSUE THREAD

**Issue by Rodrigo2018** [docker-library/python#148]
After installing Django, when I make a new Django project I start the Django builtin server. Once the server is running, if I hit Ctrl+Z, the server process is placed stopped in the background. Then if I type the "bg" command in order to resume the builtin server process I get the following message:

"Error: [Errno 1] Operation not permitted"

The container is a Python 3.5.1 running on a Ubuntu Desktop X64 15.10. If I run the same setup directly installed on the very Ubuntu machine that hosts the container, there is no errors and all works fine.

A friend of mine said the issue could be related to overlayfs. But that is not the case, since my Docker setup uses aufs as storage driver and extfs as the backing filesystem.

you have any idea, guys?

**Comment by tianon** [comment]
I would guess that it's related to either seccomp or apparmor denying
something the shell is trying to do in resuming the subprocess.
