### ISSUE TITLE
python: can't open file './main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cedricleroy** [docker-library/python#150]
I am new with Docker, and I am trying to run a minimalist python example.

Here is the Docker file:

```
FROM python:3.5
CMD ["python", "./main.py"]
```

The build is fine:

```
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM python:3.5
 ---> 1d0326469b55
Step 2 : CMD python ./main.py
 ---> Using cache
 ---> a0f7fad9414e
Successfully built a0f7fad9414e
```

However when I try to run:

```
python: can't open file './main.py': [Errno 2] No such file or directory
```

The doc says that it copies the directory content to /usr/src/app, but didn't see anything there.

Any ideas?

**Comment by yosifkit** [comment]
The docs specifically mention using one of the `onbuild` images.  Its steps automatically `COPY` in your directory and install dependencies so that your code is available in the resulting image and container.  It is the same as running this in your Dockerfile.

```Dockerfile
FROM python:3.5

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app
CMD ["python", "./main.py"]
```

**Comment by yosifkit** [comment]
Closing old issue.

**Comment by KalpitSuthar** [comment]
python3: can't open file 'kickthemout.p': [Errno 2] No such file or directory
please help?

**Comment by 1brian** [comment]
edefef

**Comment by tanchao90** [comment]
I have the same issue：
python: can't open file './main.py': [Errno 2] No such file or directory
why?

**Comment by ocawa** [comment]
Wrong interpreter, it could be that you're project interpreter is inside a vritualenv or docker, that's what worked for me :)

**Comment by nabil51o** [comment]
python2: can't open file 'admin_panel_finder': [Errno 2] No such file or directory faceing this problem or can anyone gide me how to find any website login link for sql injection please
