### ISSUE TITLE
Python 3.6.0b4 on Docker Hub

### ISSUE THREAD

**Issue by Naddiseo** [docker-library/python#159]
Could we get the latest beta available on Docker Hub, please?

Thanks.

**Comment by tianon** [comment]
This was fixed in https://github.com/docker-library/python/commit/d8aac61bc3abddfd7ba58724446cf9b0e949ffa4, but since then we've also gotten https://github.com/docker-library/python/commit/12bf960914ceaec59562cf49cf048b971e54399a which puts us at 3.6.0rc1. :+1:
