### ISSUE TITLE
can‘t install mysqlclient 

### ISSUE THREAD

**Issue by iloveyo123u1** [docker-library/python#162]
pip install mysqlclient

-------------------------------------

 Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d8t1b9s4/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-d8t1b9s4/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-d8t1b9s4/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d8t1b9s4/mysqlclient/

**Comment by kevin-brown** [comment]
My guess is that you aren't installing the prerequisites before trying to pip install it.

https://github.com/PyMySQL/mysqlclient-python#prerequisites

**Comment by tianon** [comment]
Indeed, for `pip install` to complete successfully, dependencies _must_ be installed.

I was able to successfully `pip install mysqlclient` with both of the following:

```dockerfile
FROM python:2-alpine
RUN apk add --no-cache mariadb-dev gcc libc-dev
RUN pip install mysqlclient
```

```dockerfile
FROM python:3-alpine
RUN apk add --no-cache mariadb-dev gcc libc-dev
RUN pip install mysqlclient
```

(hopefully this helps adapt for your use case)

**Comment by iloveyo123u1** [comment]
tks @all
