### ISSUE TITLE
Python 3.6.0, please!

### ISSUE THREAD

**Issue by brainix** [docker-library/python#165]
I apologize if this is not the appropriate place to report this issue, but...

Python 3.6.0 was recently released.  May we please have a Docker Hub image with 3.6.0?

Thanks in advance, and keep up the great work!

**Comment by mackeyja92** [comment]
+1

**Comment by achauve** [comment]
The branch with python 3.6 has been merged in this repository but the tag does not show up on docker hub https://hub.docker.com/r/library/python/ . Is there a problem somewhere?

**Comment by kevin-brown** [comment]
The official-library repository still needs to update the tags for the Python 3.6 images.

https://github.com/docker-library/official-images/issues/2495
