### ISSUE TITLE
urllib.request and ftplib issue inside docker container

### ISSUE THREAD

**Issue by elmbeech** [docker-library/python#171]
I try to download a file via ftp from inside a python3 docker container, The container was built form the official docker hub python repository.

Here is a minimal example of the python code I try to execute: 
- import

- ftplib
- ftp = ftplib.FTP("ftp.geneontology.org")
- ftp.login()
- ftp.sendcmd("MDTM /go/ontology/go-basic.obo")
- ftp.retrbinary("RETR /go/ontology/go-basic.obo", callback=open("go-basic.obo", "wb").write)

This code's MDTM and RETR command works well in the host.

However, in the python3 docker container only the MDTM command works. The RETR command throws the following error message:
`
ftp.retrbinary("RETR /go/ontology/go-basic.obo", callback=open("ich.obo", "wb").write)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/ftplib.py", line 443, in retrbinary
  data = conn.recv(blocksize)
ConnectionResetError: [Errno 104] Connection reset by peer
`

My Dockerfile looks like this:
- FROM python:3
- CMD ["/bin/bash"]

I build, enter the container and python shell with this sequence:

1. docker build --tag bue/py3ftp .
1. docker images
1. docker run -ti --name=abc bue/py3ftp /bin/bash
1. python

My computer is configured with the following software:
OSX 10.11.6 ElCapitan; VirtualBox version 5.1.8 r111374 (Qt5.5.1) used by docker-machine; docker-machine version 0.8.2, build e18a919; docker version 1.12.3, build 6b644ec; Python 3.6.0 (default, Dec 28 2016, 23:09:04) inside the docker container.

**Comment by elmbeech** [comment]
- docker run -ti -p 21:21 --name=abc bue/py3ftp /bin/bash
or
- docker run -ti -P --name=abc bue/py3ftp /bin/bash
solves the problem.

**Comment by tianon** [comment]
This sounds like active FTP vs passive FTP -- if `ftplib` allows you to use passive FTP instead, that's probably a more general solution to this same issue for folks who can't accept incoming connections.
