### ISSUE TITLE
Update Alpine to 3.5

### ISSUE THREAD

**Issue by ghost** [docker-library/python#173]
https://hub.docker.com/_/alpine/

**Comment by yosifkit** [comment]
See https://github.com/docker-library/python/pull/166, https://github.com/docker-library/python/pull/168, and https://github.com/docker-library/golang/pull/131#issuecomment-270677556.

**Comment by lorddaedra** [comment]
:'-( 

May be add 
3.6.0-alpine, 3.6-alpine, 3-alpine, alpine (3.6/alpine/Dockerfile) / stay with 3.4 Alpine for now, add deprecation warning and switch to latest alpine later and after that always use latest alpine /
3.6.0-alpine3.4, 3.6-alpine3.4, 3-alpine3.4, alpine3.4 (3.6/alpine/Dockerfile)
3.6.0-alpine3.5, 3.6-alpine3.5, 3-alpine3.5, alpine3.5 (3.6/alpine/Dockerfile)

**Comment by beaugunderson** [comment]
I would also use a `python:3.6-alpine3.5` tag if there was one (driven mostly by LibreSSL, postgres @ 9.6, and no warning during `update-ca-certs`) ✨

**Comment by snimavat** [comment]
Plz update to alpine 3.5

**Comment by nigma** [comment]
The `docker-library/golang` repository included the `-alpine3.5` variant (https://github.com/docker-library/golang/tree/master/1.7/alpine3.5) following the discussion in https://github.com/docker-library/golang/pull/131.

How about using the same approach here?

**Comment by Lubo** [comment]
It was a big mistake not to go for Alpine 3.5 when Python 3.6 was released. Now, I'd prefer if we don't get too crazy with tags, but sticking to Alpine 3.4 for another year until Python 3.7 is released would suck big time.

**Comment by tianon** [comment]
@Lubo Python 3.6 was released 2016-12-23; Alpine 3.5 was released 2016-12-22 -- we didn't even know we'd have to be reverting anything at that point, but yeah, we should've left 3.6 (a bit late now)

@nigma yeah, that's sane -- once https://github.com/docker-library/python/pull/194 settles, I'll take a look at adding `alpine3.5` variants here

**Comment by Suor** [comment]
Trying to use Python 2.7 with R, which only available in alpine 3.5. Any reasons not to upgrade?

**Comment by Lubo** [comment]
Alpine 3.6 is out a it's the new stable. Shouldn't we jump right there? Also, this issue has been around for nearly half a year now. What can we do speed the things up?

**Comment by skwashd** [comment]
I've created PR #201 in order to bump the Alpine version to [3.6](https://alpinelinux.org/posts/Alpine-3.6.0-released.html). The build is green for the PR. 

I'm happy to reroll it to introduce a `alpine3.6` tag if that is the preferred approach.

**Comment by tianon** [comment]
Yes, let's add explicit `alpine3.6` variants here.  See https://github.com/docker-library/golang/pull/162 for an example of doing that for the `golang` image.

**Comment by tianon** [comment]
I think we should start conservative and only include `python:3.6` and _possibly_ `python:2.7` initially (to also help encourage folks to update to the latest version).

**Comment by tianon** [comment]
Also, let me know if you are no longer interested in taking the lead on this change and I'm happy to take over.

**Comment by skwashd** [comment]
@tianon thanks for the offer. I like a challenge so I'd like to continue to work on this. I would appreciate your feedback when I push my changes. I hope to get that done later today or some time tomorrow Australian time.

**Comment by skwashd** [comment]
@tianon it took me a little long than planned, but I have made the changes you suggested above. There is an issue with the build that I would appreciate some help with. See PR #201 for all the details.

**Comment by skwashd** [comment]
@tianon now that PR #201, which adds alpine 3.6 support for Python 2.7 and 3.6, has been merged can we close this issue?

**Comment by tianon** [comment]
Yep, thanks!
