### ISSUE TITLE
python:onbuild - delete requirements.txt after usage

### ISSUE THREAD

**Issue by prokopst** [docker-library/python#179]
Is `requirements.txt` kept there for any specific reason?

Why am I asking? `requirements.txt` supports command line options as well, so it's possible to create:
```
--index-url 'https://username:password@my-private-pypi.something.com/pypi/simple/'
requests
jinja2
internal-package
```
for python:onbuild. After `requirements.txt` file is used, it's no deleted and the file stays there. Including credentials.

If there is no reason, corporations having private pypis would not have to do explicit cleanup of the `requirements.txt` file and the official onbuild images would be "private pypi friendly" from the beginning.

**Comment by tianon** [comment]
Once we `COPY` a file into the image, it exists in the image permanently -- it cannot be removed (if a newer layer does something like `RUN rm requirements.txt`, the file still exists, but it's got what's called a "whiteout" on top of it, and is still accessible so is not sufficient for hiding secrets).

**Comment by prokopst** [comment]
Wow, that's good to know, thanks. After some reading I think I'll not use onbuild and I'll create a new one using `ONBUILD ARG`.
