### ISSUE TITLE
zlib module missing when --enable-optimizations

### ISSUE THREAD

**Issue by ghost** [docker-library/python#185]
I don't know if you guys have this issue. I compiled python 2.7.13 with --enable-optimizations on, then `zlib` module is gone. Have anyone encountered this too?

**Comment by yosifkit** [comment]
Oh, that is strange. I didn't check that in my test for https://github.com/docker-library/python/issues/160 and could be a blocker if we seriously consider using it for all the images.  If you can make a reproducible case, you should probably report it to upstream in their issue tracker https://bugs.python.org/.

**Comment by yuanzimiaoKyren** [comment]
Right. This is solved finally by finding the `libz.so.1` in my `/lib/x86_64-linux-gnu` folder and make a link `sudo ln -s /lib/x86_64-linux-gnu/libz.so.1 /lib/libz.so` according to a ubuntu forum thread(I, lost the link to that thread...). It actually worked. I'm working on Ubuntu 14.04, don' know if it's system specific problem. I'll report to python.org anyway. Thanks.

**Comment by tianon** [comment]
Closing, given that this appears resolved.
