### ISSUE TITLE
/usr/bin/python3 should exist for scripts using #!/usr/bin/python3 interpreter reference

### ISSUE THREAD

**Issue by JonasT** [docker-library/python#191]
/usr/bin/python3 should exist for scripts using #!/usr/bin/python3 interpreter reference. It usually does on all big distributions, but some reason not in this image in the "latest" version. Therefore, this command should be added to the build steps:

`ln -s /usr/local/bin/python3.6 /usr/bin/python3`

(or an equivalent)

Edit: fix suggested command

**Comment by yosifkit** [comment]
In order to not run into package conflicts if someone installs python3 from apt, we only put things in `/usr/local/`.  To be better portable users can use `#!/usr/bin/env python3` which will use the first `python3` from the `PATH`.
