### ISSUE TITLE
Replace `pip3` to `python3 -m pip`

### ISSUE THREAD

**Issue by lorddaedra** [docker-library/python#195]
Here: https://github.com/docker-library/python/blob/master/Dockerfile-alpine.template#L76

**Comment by yosifkit** [comment]
We refactored the linked section with https://github.com/docker-library/python/pull/194.

**Comment by lorddaedra** [comment]
Currently I use my custom version of Python Docker file (https://dpaste.de/8Xps), I try to stay close to original version..

- Alpine 3.5
- upgrade packages before processing
- install and configure flake8 and some tools like pylint, mypy and sphinx,..

I fixed some bug with `wget: can't execute 'ssl_helper': No such file or directory`, as I see, it's similar too https://github.com/Yelp/dumb-init/issues/73 ... and previous `wget -0 ...` completed without errors, so I added `get-pip.py` to 46 line close to other wget commands, before deleting .fetch-deps and it works now... https://dpaste.de/8Xps#L46,74

For some reason your code works in your version but doesn't in my. May be because of modern Alpine version or because of it is in different RUN block... 

I use one single RUN block to minimize count of layers of image...

Not sure about replacing `&&` to `;`, in future I going to use Ansible for building images (https://www.ansible.com/ansible-container), but not sure, it will work with Docker Cloud/Hub build system (but it may work with https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands)...

**Comment by tianon** [comment]
> `wget: can't execute 'ssl_helper': No such file or directory`

This is indeed due to the Alpine version -- the newer Alpine releases no longer require `libressl` or CA certificates installed in order to fetch SSL web content.

Given that this doesn't appear to be an issue with the image we maintain (and thus not something we can really fix), I'm going to close. :+1:
