### ISSUE TITLE
use of dpkg-architecture in python Alpine Dockerfile

### ISSUE THREAD

**Issue by ThomasChiroux** [docker-library/python#202]
Here:
https://github.com/docker-library/python/blob/master/3.6/alpine/Dockerfile#L64

I don't think the $gnuArch will be well populated using a debian tool in the Alpine installation.
After that, i'm not sure which architecture will take ./configure, but

I've seen differences in math calculation within the alpine image compared my pc, certainly due to float size differences.

**Comment by skwashd** [comment]
@ThomasChiroux thanks for raising this. I have had no issue building the alpine docker images. Before `dpkg-architecture` is called [`dpkg` and `dpkg-dev` are installed](https://github.com/docker-library/python/blob/master/3.6/alpine/Dockerfile#L43). Here is the output in a alpine 3.6 container after installing those 2 packages:

```
~ # dpkg-architecture --query DEB_BUILD_GNU_TYPE
x86_64-linux-musl
~ #
```

@tianon I think we can close this one.

**Comment by tianon** [comment]
Yeah, I think we'd need more concrete examples of issues this causes -- it's what makes some of our ongoing multiarch work possible.

If it is causing issues (which remains to be seen for sure, right?) I'd imagine the worst would be that we need updated copies of `config.{sub,guess}` like we do in several other repos. 👍
