### ISSUE TITLE
PYTHONDONTWRITEBYTECODE

### ISSUE THREAD

**Issue by tianon** [docker-library/python#207]
We should play with exporting `PYTHONDONTWRITEBYTECODE` instead of deleting the `pyc` files after the fact!

See also https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE and https://docs.python.org/2/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE.

**Comment by tianon** [comment]
Played with this a little bit, and it looks like the Python build scripts create `*.pyc` files unconditionally.

Additionally, `get-pip.py` creates `*.pyc` files too, which I'm guessing are because it's pulling in pre-compiled wheels, so the `*.pyc` files are coming in as part of what's being downloaded/installed, not being generated by Python or `pip`.

**Comment by xavfernandez** [comment]
FWIW `*.pyc` are generated by pip but you can provide `--no-compile` to `get-pip.py` (and/or `pip`) and it shouldn't create the `.pyc` files.

**Comment by tianon** [comment]
Indeed!  I did some experimentation:

```diff
diff --git a/3.7/alpine3.10/Dockerfile b/3.7/alpine3.10/Dockerfile
index 05dfb5f..63c4bc2 100644
--- a/3.7/alpine3.10/Dockerfile
+++ b/3.7/alpine3.10/Dockerfile
@@ -152,14 +152,16 @@ RUN set -ex; \
        wget -O get-pip.py "$PYTHON_GET_PIP_URL"; \
        echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c -; \
        \
+       export PYTHONDONTWRITEBYTECODE=1; \
        python get-pip.py \
                --disable-pip-version-check \
                --no-cache-dir \
+               --no-compile \
                "pip==$PYTHON_PIP_VERSION" \
        ; \
        pip --version; \
        \
-       find /usr/local -depth \
+       echo find /usr/local -depth \
                \( \
                        \( -type d -a \( -name test -o -name tests \) \) \
                        -o \
```

Running `find /usr/local -name '*.pyc'` in the resulting image came up empty, which is interesting. :smile:

**Comment by tianon** [comment]
Coming back to this with fresh eyes, I'm not convinced adding this makes our `Dockerfile` _more_ clear (or really much/any more efficient), especially since we'd probably still want a test just to make sure we didn't somehow regress. :see_no_evil:  As such, I'm leaning towards closing this. :see_no_evil:

**Comment by imomaliev** [comment]
I think this could greatly simplify `Dockerfile`'s and slightly improve build times. Also, I should note that many developers copy some parts of official `Dockerfile`'s and using best practices would be a good thing. Regarding testing for regression, IMHO that there probably should already be a test to check that images don't contain `py[co]` files in case somebody breaks cleanup.

**Comment by tianon** [comment]
Yeah, that's fair -- I suppose it would make more sense to make that one of our post-build integration tests instead of part of the `Dockerfile` itself.

**Comment by imomaliev** [comment]
@tianon Great news. Thank you for all the work)
