### ISSUE TITLE
issue while importing python modules located in docker volumes.

### ISSUE THREAD

**Issue by apre** [docker-library/python#210]
With `python:3.6.1-windowsservercore`:

python cannot load modules that are contained  in a docker-volume directory.

However it is correctly imported if the file is in the container filesystem.
 
I created here a simple project to reproduce the issue:
https://github.com/apre/windows-volume-issue

**Comment by yosifkit** [comment]
If this is really just https://github.com/moby/moby/issues/27537, then it probably needs to be fixed at the language level like [golang did](https://github.com/golang/go/commit/53003621720ff39c4745a76f76847123c27b01ea).

**Comment by apre** [comment]
Thank you @yosifkit for your answer. I filled a python issue (http://bugs.python.org/issue30865) for making this issue visible to the great python team.

**Comment by yosifkit** [comment]
Since this is an upstream language issue, I'll go ahead and close since there is nothing we can change in the image to fix it.
