### ISSUE TITLE
IDLE tests could be deleted too 

### ISSUE THREAD

**Issue by edmorley** [docker-library/python#214]
The current build scripts delete test-related directories after the build, by finding exact directory matches against the names `test` and `tests`. However this leaves one directory behind:
`lib/python3.6/idlelib/idle_test/`

It's only ~1MB, but seeing as the other test directories are being deleted, I think it makes sense to include it too.

Ideally at some point upstream will support disabling building tests in the first place (eg `--disable-test-suite`) which will be much less fragile (plus save build time), but for now the ticket seems to have stalled:
https://bugs.python.org/issue27640

**Comment by yosifkit** [comment]
Closed by #430

**Comment by edmorley** [comment]
@gliptak thank you :-)

**Comment by gliptak** [comment]
@edmorley to save some download bandwidth :)
