### ISSUE TITLE
I can't seem to create a virtual environment using Python 3's venv

### ISSUE THREAD

**Issue by peterfebin** [docker-library/python#216]
This is my Dockerfile

```
FROM python
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN python3 -m venv flask
```
This results in the below error:

> Step 4/4 : RUN python3 -m venv flask
>  ---> Running in 4fb4aa38a8ca
> Error: [Errno 2] No such file or directory: '/usr/src/app/flask/bin/python3'
> The command '/bin/sh -c python3 -m venv flask' returned a non-zero code: 1

Is venv part of this image or should I be using another image instead ?

**Comment by edmorley** [comment]
That works for me using the most recent `python:latest` image:
```
$ docker pull python
...
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM python
 ---> c5700ee6fe7b
Step 2/4 : COPY . /usr/src/app
 ---> b8f96d28dafc
Removing intermediate container 2b23a453bd94
Step 3/4 : WORKDIR /usr/src/app
 ---> 6d747e9e29e2
Removing intermediate container e4b17d2f18ff
Step 4/4 : RUN python3 -m venv flask
 ---> Running in a4c56ea6e6b4
 ---> 30216b92f0f5
Removing intermediate container a4c56ea6e6b4
Successfully built 30216b92f0f5
Successfully tagged test:latest
```

Are you sure you're using a recent image and there's nothing in the local directory that is being copied in that would prevent the venv from being created?

**Comment by peterfebin** [comment]
Thank you. I already had a venv by name flask within my directory which caused the conflict.
The error got me confused.  Fixed now. Closing this.
