### ISSUE TITLE
Base python:slim on debian:stretch-slim

### ISSUE THREAD

**Issue by chpio** [docker-library/python#219]
Hi,

1. `strech` is the current stable release and (IMHO) should be used as default.
2. `python:slim` is based on a non slim debian image, which is kind of misleading given the name `python:slim`

**Comment by douglasmiranda** [comment]
Related: #104

**Comment by yosifkit** [comment]
1. since we don't have an simple way to let users know when the default for `python:3.6` will be `stretch` rather than `jessie` we have not made a decision when to switch over since that is a large breaking change for many
    - since https://github.com/docker-library/python/pull/215 we do label the images so that users can choose `jessie` or `stretch` for python 2.7 and 3.6 (ex `python:2.7-stretch` and `python:3.6-stretch`), though we do not yet have a `slim` variant for the `stretch` variety
    - `stretch` is the default in python 3.7 and above (currently in alpha stages)
    - I think adding a `python:3.6-slim-stretch` would be useful (along with explicit `-jessie` and `-wheezy` on the rest of the `-slim` images), but until we have a defined policy regarding Distro updates we cannot change default distribution in minor releases. (similar work to https://github.com/docker-library/php/issues/504)

 1. the `slim` in python images is about the size of the image and does not necessarily indicate being from a Debian slim (the python slim came first, there was no Debian slim)
    > This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run python. Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
    > 
    > \- https://github.com/docker-library/docs/tree/212ed60a19b8b5454308b504fdcdf5d317f42b6f/python#pythonslim
    
    - if this will not break users, I am not opposed to moving the slim python images to be from the slim Debian images
