### ISSUE TITLE
Adding pipenv 

### ISSUE THREAD

**Issue by jabagawee** [docker-library/python#225]
So apparently the new hotness in Python packaging is [Pipenv](http://pipenv.org), and it has the official recommendation of [Python.org](https://packaging.python.org/new-tutorials/installing-and-using-packages/). Its `Pipfile` format aims to replace `requirements.txt`, and I was wondering if it was appropriate to add a line like

```Dockerfile
RUN pip install pipenv
```

to the images in this build?

**Comment by kennethreitz** [comment]
it easy enough for people to do this themselves.
