### ISSUE TITLE
Any plans to add an alpine variant for arm32v7?

### ISSUE THREAD

**Issue by Serkan-devel** [docker-library/python#234]
I cant find containers like `arm32v7:3.6.0-alpine` . The closest to it are slim variants.

**Comment by tianon** [comment]
Correct, Alpine is not officially multiarch yet; see https://github.com/gliderlabs/docker-alpine/issues/304.

Once Alpine is multiarch, we'll add arm32v6 to the Alpine architectures here. 👍
