### ISSUE TITLE
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.

### ISSUE THREAD

**Issue by CrimsonGlory** [docker-library/python#241]
Doing apt-get update from [python:2.7-stretch](https://github.com/docker-library/python/blob/b1512ead24c6b111506a8d4229134a29da240597/2.7/stretch/Dockerfile) I get:

```
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found [IP: 151.101.0.204 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This started happening about 1 hour ago. AFAIK stretch is still supported.

**Comment by yosifkit** [comment]
Sounds similar to https://github.com/docker-library/openjdk/issues/90 and the answer is usually https://github.com/docker-library/openjdk/issues/90#issuecomment-268863365.  It should still be there and works fine from here, but sometimes some mirrors are flaky.

```console
$ docker run -it --rm python:2.7-stretch bash
root@7c1f22f2a866:/# apt-get update
Get:3 http://security.debian.org stretch/updates InRelease [63.0 kB]
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2479 B]
Get:6 http://security.debian.org stretch/updates/main amd64 Packages [283 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [6499 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.1 MB in 0s (11.6 MB/s)
Reading package lists... Done
root@7c1f22f2a866:/# 
```

**Comment by CrimsonGlory** [comment]
You are correct.

**Comment by crashoverride95** [comment]
root@crash-override:~# apt-get clean && apt-get update
Ign:1 http://deb.leap.se/client stretch InRelease                              
Err:2 http://deb.leap.se/client stretch Release                                
  404  Not Found
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease          
Hit:3 http://kali-za.bitcrack.net/kali kali-rolling InRelease                 
Hit:5 http://kali-za.bitcrack.net/kali kali-bleeding-edge InRelease      
Hit:6 http://dl.google.com/linux/chrome/deb stable Release
Reading package lists... Done
E: The repository 'http://deb.leap.se/client stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jacohend** [comment]
Currently getting this from practically any stretch dockerfile.

**Comment by tianon** [comment]
Yep, Debian is having an upstream outage on deb.debian.org ATM -- nothing we can do but send them virtual hugs and hope they get it resolved in a timely manner.

**Comment by daneren2005** [comment]
Same thing here.  I am getting this from `circleci/php:7.2-cli-node-browsers`, so it is probably a more general problem.

**Comment by Littlejd1997** [comment]
Reviving this thread. Is it down again?

**Comment by Littlejd1997** [comment]
Yup, its down. Literally running the example from @yosifkit 

    jonathan@Jonathans-MacBook-Pro ~> docker run -it --rm python:2.7-stretch bash
    Unable to find image 'python:2.7-stretch' locally
    2.7-stretch: Pulling from library/python
    bc9ab73e5b14: Pull complete
    193a6306c92a: Pull complete
    e5c3f8c317dc: Pull complete
    a587a86c9dcb: Pull complete
    72744d0a318b: Pull complete
    23bf491a4f84: Pull complete
    7f3410abb2aa: Pull complete
    08c5081d43e2: Pull complete
    80a779c2daa3: Pull complete
    Digest: sha256:629868162ed980d9b24bf3bf0699cb300b368e8b144be9fc43a6a4740cc02561
    Status: Downloaded newer image for python:2.7-stretch
    root@b83c28200ce1:/# apt-get update
    Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
    Ign:2 http://deb.debian.org/debian stretch InRelease
    0% [1 InRelease 13.9 kB/94.3 kB 15%]
    Ign:3 http://deb.debian.org/debian stretch-updates InRelease
    Ign:4 http://deb.debian.org/debian stretch Release
    Ign:5 http://deb.debian.org/debian stretch-updates Release
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
    Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Get:10 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [452 kB]
    Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
    Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
    Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
    Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
    Ign:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Ign:6 http://deb.debian.org/debian stretch/main all Packages
    Err:7 http://deb.debian.org/debian stretch/main amd64 Packages
      404  Not Found
    Err:8 http://deb.debian.org/debian stretch-updates/main amd64 Packages
      404  Not Found
    Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
    Fetched 546 kB in 0s (836 kB/s)
    Reading package lists... Done
    W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
    E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    root@b83c28200ce1:/#
    root@b83c28200ce1:/#

**Comment by hudspeth** [comment]
Running into the same issue 
`Err:6 http://deb.debian.org/debian stretch/main amd64 Packages
  404  Not Found
Ign:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages
Err:9 http://deb.debian.org/debian stretch-updates/main amd64 Packages
  404  Not Found
Ign:9 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages
Fetched 546 kB in 3s (157 kB/s)
Reading package lists...
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch/main/binary-all/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch-updates/main/binary-all/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update 	&& apt-get install -y curl openssl tar unzip 	&& apt-get clean' returned a non-zero code: 100`

**Comment by banoodle** [comment]
yup

**Comment by Littlejd1997** [comment]
Is there a better way to alert the debian folks? That's where the issue lies

**Comment by tianon** [comment]
Yes, Debian is having another outage -- this is not the appropriate place to discuss it.  Please find a more appropriate channel for discussion.

**Comment by tianon** [comment]
(I can assure you, the folks in charge of that are well aware of the issue, and are working on it -- I have been in direct contact with some of them myself.)
