### ISSUE TITLE
`tests_require` syntax error

### ISSUE THREAD

**Issue by rubendibattista** [docker-library/python#246]
Guys, in the last days in the docker images (python:2.7) that we use for CD, I started to get the following error when running a `pip install .`:

```
Complete output from command python setup.py egg_info:
    error in <package> setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
```

Is this a bug or there were non-backwards compatible changes in the last versions of Python?

This is my `tests_require` section in `setup.py`:
```
tests_require={
        'pytest',
        'doctest',
        'pytest-cov',
        'pytest-pylint',
        'pytest-xdist'
    },
```

The `setup.py` works correctly locally on my Mac Book Pro with last Macports python2.7 installed.
```
  python27 @2.7.14_0 (active)
```

`python -V`
```
Python 2.7.14 (default, Sep 22 2017, 00:06:07)
```

**Comment by tianon** [comment]
I think you need to replace your `{` with `[` -- we just had a Debian update, which would have trickled down to a rebuild here, which probably pulled in a newer version of `setuptools`.  Googling the error message, I found several similar reports from other projects related to `setuptools` version.

**Comment by rubendibattista** [comment]
Nice catch. I'm probably overly dumb since I looked on Google a lot before coming here and asking. 

Sorry about bothering you!

For reference, the change was introduced in [`setuptools  v38.0.0`](https://github.com/pypa/setuptools/issues/458)
