### ISSUE TITLE
manifest for python:2.7.14-alpine3.7 not found

### ISSUE THREAD

**Issue by leonsp** [docker-library/python#252]
There's supposed to be a `2.7.14-alpine3.7` tag per the documentation, but I get this error:

```
$ docker pull python:2.7.14-alpine3.7
Error response from daemon: manifest for python:2.7.14-alpine3.7 not found
```

`2.7.14-alpine3.6` works fine

**Comment by tianon** [comment]
Yeah, the `amd64` build queue for official images is a bit overloaded right now -- give it a little time and it'll come through (once the build servers get around to `python`).

See also docker-library/rabbitmq#188, docker-library/ruby#159, c0b/docker-erlang-otp#75, docker-library/official-images#3472, https://github.com/docker-library/wordpress/issues/239, https://github.com/piwik/docker-piwik/issues/70, https://github.com/nodejs/docker-node/issues/571, https://github.com/docker-library/official-images/issues/3653, https://github.com/docker-library/official-images/pull/3622#issuecomment-339838650, https://github.com/docker-library/redis/issues/115, https://github.com/docker-library/rabbitmq/issues/217.

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
