### ISSUE TITLE
python:3.6.4-slim can not guess extension well

### ISSUE THREAD

**Issue by haoliang-gao** [docker-library/python#254]
It was not a language bug in my tests.

I have test `python:3.6.4-jessie` and `python:3.6.4-slim`, and python in jessie works well.

here is my python script:

```
import mimetypes, sys

print("python ver: %s" % (sys.version) )
print("ext: %s" % (mimetypes.guess_extension("application/vnd.openxmlformats-officedocument.wordprocessingml.document")) )
```

![2018_01_08_17_34_33](https://user-images.githubusercontent.com/6236829/34665229-5b7424f2-f49a-11e7-8bfc-5020459e3b75.jpg)

**Comment by tianon** [comment]
From https://docs.python.org/3/library/mimetypes.html, it appears this module reads type information from a `mime.types` file provided on the system.  In the `python:3` image, we have `mime-support` installed, which provides `/etc/mime.types`, but that package is not installed in `python:3-slim`, so I think this is working as designed.  If you install `mime-support` in your `python:3-slim` container, it should have the same set of mime type detection as `python:3` does.

**Comment by haoliang-gao** [comment]
So detailed, thank you.
and this issue turns into a question.

**Comment by mbiswal94** [comment]
@tianon I am stuck at this. Can you tell me how I can add mime-support package to a 3.9-slim-buster image?

**Comment by yosifkit** [comment]
The same as you would for any OS package; likely by creating a Dockerfile to create a new image:
```dockerfile
FROM python:3.9-slim-buster
RUN apt-get update && apt-get install -y mime-support && rm -rf /var/lib/apt/lists/*
```
(Though, looking at the [description of the package](https://packages.debian.org/bullseye/mime-support), you probably just need the `media-types` package instead)
