### ISSUE TITLE
Latest Python 2.7 image broken

### ISSUE THREAD

**Issue by toastdriven** [docker-library/python#260]
Apologies if this is the wrong place to file this report. If you use the `Decimal` library, the latest `python:2.7` image on [Docker Hub](https://hub.docker.com/r/_/python/) is broken.

## Reproduce

A minimal Dockerfile

```
FROM python:2.7

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN python -c "from decimal import Decimal"
```

Then run `docker build -t broke .`. You should get the following output:

```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM python:2.7
 ---> 9e92c8430ba0
Step 2/3 : ENV PYTHONUNBUFFERED=1     PYTHONDONTWRITEBYTECODE=1
 ---> Running in b5e1308c52ab
Removing intermediate container b5e1308c52ab
 ---> 21683927efbd
Step 3/3 : RUN python -c "from decimal import Decimal"
 ---> Running in 69369edcaa20
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/decimal.py", line 1
SyntaxError: Non-ASCII character '\xab' in file /usr/local/lib/python2.7/decimal.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
The command '/bin/sh -c python -c "from decimal import Decimal"' returned a non-zero code: 1
```

## Environment

macOS High Sierra 10.13.3
Docker Community Edition Version 17.12.0-ce-mac49 (21995)
Channel: stable
f50f37646d

**Comment by toastdriven** [comment]
For what it's worth, the current SHA is `sha256:7dd4dab14fc521c6cb61bbc2f56d70ef03fd5fe3ed7bf96e630c8e8476f830c5` & fails.

**Comment by yosifkit** [comment]
Try deleting the image and pulling it again.  We've seen many images become corrupt on Docker For Mac recently: docker-library/mysql#372, docker-library/ruby#180, docker/for-mac#2327

**Comment by toastdriven** [comment]
For what it's worth, I finally got this sorted.

```
$ docker rmi python
$ docker pull python:2.7
$ docker build -t broke .
```

This yielded a working image. I say this because just doing `docker rmi python` wasn't enough. I'm assuming there was some sort of cached image/version combination sitting around.

Thanks for the help!
