### ISSUE TITLE
Arrow Keys Don't Work In Python REPL

### ISSUE THREAD

**Issue by Miserlou** [docker-library/python#262]
It's very easy to reproduce:

```
FROM python:3.6-slim
ENTRYPOINT ["python"]
```
```
docker build -t ptest -f Dockerfile .
docker run -i ptest -i
```

Press the `up` key and you will see a `^[[A`.

This makes debugging with `pdb` super, super annoying.

I think this has to do with how `readline` works. I've tried installing `readline`, `gnureadline`, `libncurses-dev`, everything, to no avail. I don't know what's going on. Using Docker on Mac.

**Comment by tianon** [comment]
Try adding `-t` to your `docker run`.

**Comment by Miserlou** [comment]
Bless your heart, you sweet, wonderful man.
