### ISSUE TITLE
Remove `CMD`

### ISSUE THREAD

**Issue by kerinin** [docker-library/python#263]
Setting `CMD` makes it impossible to pass command arguments by setting `ENTRYPOINT` to a container's main executable.

Example:
```
FROM python
COPY . /app
ENTRYPOINT ["python3", "mysript.py"]
```

If `CMD` isn't specified in the base image I can do things like run `docker run myscript --arg1`, but as it is, the first argument will be `python3`.

**Comment by yosifkit** [comment]
Your `ENTRYPOINT` should work as is.  It is not documented (https://github.com/moby/moby/issues/35027), but if you specify `ENTRYPOINT` then the inherited `CMD` from the parent image is emptied out (https://github.com/moby/moby/pull/6909).
