### ISSUE TITLE
Executing 3 build triggers - COPY failed

### ISSUE THREAD

**Issue by linampatino** [docker-library/python#268]
Hi, 
I've trying to follow a docker tutorial that use pytho:3-onbuild image, but I have problems when I run docker build, it return this error  : "COPY failed: stat /var/lib/docker/tmp/docker-builder433999506/requirements.txt: no such file or directory"

![error_docker](https://user-images.githubusercontent.com/17790884/37158259-f3d90aea-22b8-11e8-9072-b866b8a72364.png)

My Dockerfile just has this lines:

FROM python:3-onbuild
EXPOSE 5000
CMD ["python", "./app.py"]

Thanks!!

**Comment by tianon** [comment]
Officially, `onbuild` variants are deprecated (see https://github.com/docker-library/official-images/issues/2076 and https://github.com/docker-library/docs/pull/911).

In your case, it sounds like your directory doesn't have a `requirements.txt` file (which the default `ONBUILD` triggers are trying to copy into the image so they can be used to determine the dependencies of your application automatically).

**Comment by akshika47** [comment]
@linampatino run the command going inside the Flask app. You are running it outside the folder.

**Comment by ashishpatel22** [comment]
> @linampatino run the command going inside the Flask app. You are running it outside the folder.

thanks, it solved problem in my case.
