### ISSUE TITLE
Docker images outdated, containing CVEs that have been fixed in base image

### ISSUE THREAD

**Issue by psono** [docker-library/python#269]
Hello beloved python gurus,

First thanks for your hard work! Second, it would be amazing if you could implement something  to ensure a rebuild once the base image receives an update (like a nightly build or at least a notification by mail or something to trigger a manual rebuild).

For example alpine images got updated 16 days ago with fixes for multiple CVEs and your python:alpine3.7 didn't get rebuild.

Im pretty sure that there is a ton of folks out there, that just pull your images and dont run an "upgrade" afterwards (like I did up to now).

Regards
Sascha

**Comment by yosifkit** [comment]
Yes, the process is automatic and new image builds trigger dependent images: https://doi-janky.infosiftr.net/job/multiarch/.

Also, the last update to Alpine images was Jan 9 (https://github.com/docker-library/official-images/pull/3886), which is the day before the `python:alpine3.7` image was updated. So the alpine-based python images are as updated as they can be.

Build job output from last periodic Alpine build: 
> ```
> skipping amd64/alpine:3.7 (created 2018-01-09T21:10:58Z, last updated 2018-01-09T21:13:37Z)
>```

From the last python build:
> ```
> skipping amd64/python:alpine3.7 (created 2018-01-10T05:21:42Z, last updated 2018-01-10T05:48:22Z)
> ```

[repo-info](https://github.com/docker-library/repo-info/) is a useful collection of info that is constantly scraped from official-images available on the Docker Hub, like [`python:alpine3.7`](https://github.com/docker-library/repo-info/blob/6c9eaec2266b5dc94ffbdab0b4ad75b52a2696a1/repos/python/remote/alpine3.7.md#pythonalpine37---linux-amd64).

**Comment by chickahoona** [comment]
Hi yosifkit,
I had to investigate as your reply made me wonder. I compared 

https://anchore.io/image/dockerhub/3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353?repo=library%2Falpine&tag=3.7#security

and

https://anchore.io/image/dockerhub/4b00a94b6f26b22a3f204df1278160a6ca27e16802930041d9777bbd7438cd01?repo=library%2Fpython&tag=alpine3.7#security

So the base image had those vulnerabilities fixed while python images still were "unprotected". It looks that the fixes are only available via "apk upgrade" and not part of the current base image:

```
$ docker pull python:alpine3.7
alpine3.7: Pulling from library/python
Digest: sha256:985da44358da888df62a6a7759f661c51333f06626d9a3cb9b8c064348346b11
Status: Image is up to date for python:alpine3.7

$ docker run -it psono-docker.jfrog.io/python:alpine3.7 /bin/sh
/ # apk upgrade --no-cache
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.8.1-r1 -> 2.9.1-r0)
Executing busybox-1.27.2-r6.trigger
Continuing the upgrade transaction with new apk-tools:
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/6) Upgrading musl (1.1.18-r2 -> 1.1.18-r3)
(2/6) Upgrading ncurses-terminfo-base (6.0_p20170930-r0 -> 6.0_p20171125-r0)
(3/6) Upgrading ncurses-terminfo (6.0_p20170930-r0 -> 6.0_p20171125-r0)
(4/6) Upgrading ncurses-libs (6.0_p20170930-r0 -> 6.0_p20171125-r0)
(5/6) Upgrading busybox (1.27.2-r6 -> 1.27.2-r8)
Executing busybox-1.27.2-r8.post-upgrade
(6/6) Upgrading musl-utils (1.1.18-r2 -> 1.1.18-r3)
Executing busybox-1.27.2-r8.trigger
OK: 30 MiB in 35 packages
/ #
```

I have to check if there is a reason why they didnt upgrade their docker images.
