### ISSUE TITLE
3.x-slim are missing /etc/services which breaks getservbyname

### ISSUE THREAD

**Issue by skion** [docker-library/python#270]
This breaks `socket.getservbyname()` on those images, while that function works fine on `2.7-slim`.

```
docker run -ti python:3.6-slim ls -l /etc/services
ls: cannot access /etc/services: No such file or directory
```
and
```
docker run -ti python:3.5-slim ls -l /etc/services
ls: cannot access /etc/services: No such file or directory
```
vs
```
docker run -ti python:2.7-slim ls -l /etc/services
-rw-r--r-- 1 root root 19605 Oct 21  2014 /etc/services
```

**Comment by tianon** [comment]
Try installing the "netbase" Debian package, I believe it's responsible for
providing that file.

**Comment by skion** [comment]
Thanks. Yes I've worked around it already, but just noticed the (unexpected) discrepancy between the 2.7 and 3.x images.

**Comment by tianon** [comment]
It makes me curious what's pulling it in for 2.7 and whether that's to be
expected.

**Comment by skion** [comment]
Yea could be a bug the other way round too indeed.

**Comment by tianon** [comment]
Now that I'm at a keyboard, I can't actually reproduce the problem as described:

```console
$ docker pull python:2.7-slim
2.7-slim: Pulling from library/python
Digest: sha256:2130a0b8fe2e3a9f6b35cc9210e862e05c4f48dbb36de6fafd4d3ca1d3932d21
Status: Image is up to date for python:2.7-slim

$ docker run --rm python:2.7-slim ls -l /etc/services
ls: cannot access /etc/services: No such file or directory

$ docker pull python:3.6-slim
3.6-slim: Pulling from library/python
Digest: sha256:c76c238aff91f7204754bb6927a8e627ea7cd3ce320ee20b7f7d1d9627bc47a3
Status: Image is up to date for python:3.6-slim

$ docker run --rm python:3.6-slim ls -l /etc/services
ls: cannot access /etc/services: No such file or directory
```

**Comment by skion** [comment]
Me neither when pulling the latest tag... was it removed on purpose?

**Comment by tianon** [comment]
It wasn't removed through an active action, but it's definitely not a bug
that it's gone -- the slim variants are supposed to include the absolute
bare minimum we can possibly get away with, so if we don't need "netbase",
it won't be included.

**Comment by skion** [comment]
If getting away with includes having a non-functional `socket.getservbyname()`, then that's fine, there are easy workarounds (once you've figured out why it's broken).

**Comment by skion** [comment]
For reference, this file also just disappeared on the 2.7 branch between 2.7.13 and 2.17.14.

**Comment by tianon** [comment]
That's probably due to https://github.com/debuerreotype/docker-debian-artifacts/issues/36#issuecomment-385212707.
