### ISSUE TITLE
how install gcc in python:3.6.4

### ISSUE THREAD

**Issue by wangxingjian2004** [docker-library/python#273]
when install numpy, error:
RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by yosifkit** [comment]
I am unable to reproduce. It is probably corrupt images. Try deleting them completely and pulling them again.

See also, https://github.com/docker/for-mac/issues/2327 (https://github.com/docker-library/openjdk/issues/169, https://github.com/docker-library/ruby/issues/180, https://github.com/docker-library/mysql/issues/372, https://github.com/docker/for-mac/issues/2542, https://github.com/docker-library/python/issues/260, https://github.com/docker-library/php/issues/594, https://github.com/docker-library/ruby/issues/195, https://github.com/docker-library/mongo/issues/251, https://github.com/docker-library/php/issues/599, https://github.com/docker-library/buildpack-deps/issues/74).

```console
$ docker run -it --rm python:3.6.4 bash
root@d076a85a583b:/# which gcc
/usr/bin/gcc
root@d076a85a583b:/# pip install numpy
Collecting numpy
  Downloading numpy-1.14.2-cp36-cp36m-manylinux1_x86_64.whl (12.2MB)
    100% |████████████████████████████████| 12.2MB 184kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.14.2
root@d076a85a583b:/# 
```

**Comment by wglambert** [comment]
Since the proposed resolution was not answered I'm assuming the issue is resolved

If you believe this to be in error then let me know and I'll re-open it
