### ISSUE TITLE
updating my kali is always giving me this errors...please what can i do?

### ISSUE THREAD

**Issue by crashoverride95** [docker-library/python#275]
root@crash-override:~# apt-get update
Ign:1 http://deb.leap.se/client stretch InRelease                              
Err:2 http://deb.leap.se/client stretch Release                                
  404  Not Found
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://kali-za.bitcrack.net/kali kali-rolling InRelease                 
Hit:5 http://kali-za.bitcrack.net/kali kali-bleeding-edge InRelease           
Hit:6 http://dl.google.com/linux/chrome/deb stable Release

**Comment by tianon** [comment]
This is definitely not the right place to file this issue; this is the repository for the `python` Docker image.

**Comment by crashoverride95** [comment]
am so sorry... I didn't know.. it won't happen next time
