### ISSUE TITLE
Discussion: Would it make sense to use build numbers in image tags?

### ISSUE THREAD

**Issue by meeech** [docker-library/python#285]
Hi

Based on what happened last week - the breaking of an already published tag, would it make sense to publish images with a 'build' number, so people could ties their tools to a specific image that is guaranteed not to change.

eg: Last week, the image the 3.6.5 tag points to got changed, which broke things. Would it make sense to have 3.6.5.#  - so we still always have the python version number in the tag, but also a build number so people can lock their dep to a specific image, while still having the meaning given by using python:3.6.5.# - still clear you are using python 3.6.5, but tied to a specific image build.

I know we could use the digest, but that's much less friendly.

**Comment by yosifkit** [comment]
Unfortunately, something like build numbers are much too complicated to consider. There are multiple architectures (amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x) and OS's (Linux and Windows) that can all resolve to the same image tag in [`library/python`](https://hub.docker.com/_/python/) via [manifest lists](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list).  Each build or update to an architecture causes a new manifest list to be created as seen here on `node`:  https://github.com/nodejs/docker-node/issues/718#issuecomment-387235963.

I would suggest when pulling an image that you re-tag it with the date/time pulled and then push to your own registry location if tracking the sha256 is not feasible.

**Comment by meeech** [comment]
@yosifkit thanks for the explanation.
