### ISSUE TITLE
python 2.6

### ISSUE THREAD

**Issue by drzraf** [docker-library/python#289]
I can't find an image for Python 2.6
* Python 2.6 is still an interpreter that various software aim to support
* one of the selling-point of Docker is to be able to keep old software running (even in bleeding-edge hosts environment)

**Comment by yosifkit** [comment]
You are welcome to build an image for yourself or your company, but it is not something we can support since it has been security unsupported for almost 5 years (and the last non-security release was 2010).

> Python 2.6.9 is the final security-only source-only maintenance release of the Python 2.6 series. With its release on October 29, 2013, all official support for Python 2.6 has ended. Python 2.6 is no longer being maintained for any purpose.
>
> \- https://www.python.org/dev/peps/pep-0361/#release-lifespan

**Comment by AaronM04** [comment]
@yosifkit can you give any tips on what changes would be needed to the 2.7 Dockerfile to support 2.6?

**Comment by AaronM04** [comment]
Please disregard my previous comment. I created a [Dockerfile for python 2.6](https://github.com/AaronM04/docker-python2.6/blob/master/Dockerfile). @drzraf : I hope this helps.
