### ISSUE TITLE
openssl-dev compatibility issues with the latest python:3.6-alpine image while building the django docker image

### ISSUE THREAD

**Issue by swadhins** [docker-library/python#294]
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2o-r0:
    conflicts:
               libressl-dev-2.6.4-r2[pc:libcrypto=1.0.2o]
               libressl-dev-2.6.4-r2[pc:libssl=1.0.2o]
               libressl-dev-2.6.4-r2[pc:openssl=1.0.2o]
    satisfies: world[openssl-dev]
  libressl-dev-2.6.4-r2:
    conflicts:
               openssl-dev-1.0.2o-r0[pc:libcrypto=2.6.4]
               openssl-dev-1.0.2o-r0[pc:libssl=2.6.4]
               openssl-dev-1.0.2o-r0[pc:openssl=2.6.4]
    satisfies:
               postgresql-dev-10.4-r0[libressl-dev]

**Comment by yosifkit** [comment]
You are going to have to give more information. What Dockerfile are you building? Any important files from build context?

You may be hitting the switch from Alpine 3.4 to Alpine 3.7 in https://github.com/docker-library/python/pull/290. If that is the case, you need to either update your Dockerfile to be compatible with Alpine 3.7 or change your `FROM` to `python:3.6-alpine3.4` in order to stick to Alpine 3.4. Note that the Alpine 3.4 based images are end of life.

**Comment by guillain** [comment]
The same issue for cffi installation:

```
Collecting cffi>=1.7 (from cryptography->pymysql->-r ./requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lkj599e2/cffi/
```

Fix with additionnal package but better if can be integrated in the python image as now we must update all dockefile... :-)

`RUN apk add -U --no-cache gcc build-base linux-headers ca-certificates \
        python3 python3-dev libffi-dev libressl-dev`

**Comment by wglambert** [comment]
Closing as the issue seems resolved
