### ISSUE TITLE
code completion not working on python:latest

### ISSUE THREAD

**Issue by Rodrigo2018** [docker-library/python#295]
Hi, folks!

   When I fire up a container from python:latest and get into the Python interactive interpreter prompt, I cannot use code completion. It is simply not working.

   On the other hand, if I run the same prompt directly from Ubuntu 16.04 shell, code completion works just fine for Python 3.5

   How can I fix the Docker image?

**Comment by Poogles** [comment]
readline provides this feature, I can see it [here](https://github.com/docker-library/python/blob/master/3.6/stretch/slim/Dockerfile#L22).  I've just built this manually and can't seem to recreate the issue.  If I import socket, then write `socket.` and press tab I get all the options.

» I cannot use code completion. 

Can you describe what you're trying to do?

**Comment by Rodrigo2018** [comment]
Hi, Poogles

Thank you very much for your attention to my issue!

Yes. You are right. My problem is that I am building upon python:latest image.

Take a look at my Dockerfile:

FROM python:latest

# PyCharm installation directory.
ENV PYCHARM_HOME=/etc/pycharm/

RUN set -ex \
	&& pip install virtualenvwrapper \
	&& buildPrerequisites=' \
		libcanberra-gtk* \
		libsnappy-dev \
		libxml2-dev \
		libxrender1 \
		libxslt-dev \
		libxtst6 \
		tree \
	' \
	&& apt-get update \
	&& apt-get --assume-yes --no-install-recommends install $buildPrerequisites \
	&& rm --force --recursive /var/lib/apt/lists/* \
	&& wget --output-document=/tmp/pycharm.tar.gz "https://download.jetbrains.com/python/pycharm-community-2018.1.4.tar.gz" \
	&& mkdir --parents ${PYCHARM_HOME} \
	&& tar --directory=${PYCHARM_HOME} --extract --file=/tmp/pycharm.tar.gz --gzip --strip=1 --verbose \
	&& apt-get --assume-yes autoremove \
	&& rm --force --recursive /tmp/*

CMD ["/etc/pycharm/bin/pycharm.sh"]

In order to run a container from this image build, run "xhost +local:docker" from Linux shell first.

Then, if I run PyCharm and open a terminal from within the IDE, the Python command line interpreter completion is not working as it is on the base image...

**Comment by Rodrigo2018** [comment]
That is funny...
I do remember to have reproduced the error on the core interpreter after the build...

But, anyways, you are right! Again!

I notice that if run the core interpreter from a terminal inside PyCharm, it works as you pointed out.
Yet, if I set up a virtual env, then the issue starts to manifest; and command line completion is replaced by plain tabs.

I have always thought that virtual envs, and virtualenvwrapper for that matter, were pretty consistent though...

**Comment by wglambert** [comment]
Closing since issue seems resolved
