### ISSUE TITLE
Python 3.7 release

### ISSUE THREAD

**Issue by Gr1N** [docker-library/python#296]
Hi!

Python 3.7 officially released https://pythoninsider.blogspot.com/2018/06/python-3.html, but there are no new image with 3.7. Do you have any plans (due dates)?

Thanks

**Comment by ChristianWitts** [comment]
There's a PR open #297 for this, so soon™ :)

**Comment by Gr1N** [comment]
Great! Thanks!

**Comment by NullYing** [comment]
Great!

**Comment by csandanov** [comment]
Why alpine-based python 3.7 uses openssl instead of libressl as the rest of 3.x variants?

**Comment by tao12345666333** [comment]
@csandanov  Because we used alpine:3.7, it's libressl version is 2.6.x. Python 3.7 's  `ssl` module is mostly compatible with LibreSSL 2.7.2 and newer.

**Comment by csandanov** [comment]
Ah, I see. Btw, alpine 3.8 has been released and it has LibreSSL 2.7

**Comment by tao12345666333** [comment]
Yes. Alpine 3.8 released at 06/26 and it has LibreSSL 2.7.4.  But docker-alpine has not support 3.8. https://github.com/gliderlabs/docker-alpine/issues/417

**Comment by hwmrocker** [comment]
What is missing for the pull request to be merged?

**Comment by tianon** [comment]
https://github.com/docker-library/python/pull/297 is merged. :+1:
