### ISSUE TITLE
Python 3.7 Alpine 3.8

### ISSUE THREAD

**Issue by askoretskiy** [docker-library/python#300]
Since Alpine 3.8 has been released https://alpinelinux.org/posts/Alpine-3.8.0-released.html, it would be great to have python:3.7-alpine3.8

It contains some nice goodies, like newer OpenSSL.

Probably we would need to wait some days to see an official Alpine 3.8 image.

**Comment by jpds** [comment]
This is blocked on https://github.com/docker-library/official-images/pull/4501

**Comment by tao12345666333** [comment]
I have opened a PR https://github.com/docker-library/python/pull/303
