### ISSUE TITLE
Prevent python from being installed via apt-get

### ISSUE THREAD

**Issue by Starefossen** [docker-library/python#31]
I'm using the **python:2.7-wheezy** docker image. In my docker file I have the following line:

```
RUN apt-get -y --no-install-recommends install libxml2 libxslt1.1 libxml2-dev libxslt1-dev python-libxml2 python-libxslt1
```

This causes apt-get to install python (which is already installed from the `python` box). How can I prevent this?

**Comment by tianon** [comment]
`python-libxml2` and `python-libxslt1` are Debian python packages, so it's normal that they'd install Debian's `python` package via dependencies

I think you'll need to either `pip install` those, or grab source and use `setup.py` or otherwise as appropriate.

**Comment by Starefossen** [comment]
Thanks a lot for the clarification @tianon!
