### ISSUE TITLE
Unable to install Cython on alpine image

### ISSUE THREAD

**Issue by ronlut** [docker-library/python#312]
I think something is missing, but can't understand what.
Trying it on the `python:3.6-alpine3.7` image.

While running `pip install Cython`, I'm getting this error:

` gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c /tmp/pip-install-zsnsb46v/Cython/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-3.6/tmp/pip-install-zsnsb46v/Cython/Cython/Plex/Scanners.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
`

Any help will be appreciated :)

**Comment by wglambert** [comment]
>unable to execute 'gcc': No such file or directory error: command 'gcc' failed with exit status 1

You need `gcc`, the preferred way of handling this is with a `Dockerfile` to install dependencies and then removing them afterwards

```dockerfile
FROM python:3.6-alpine

RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN pip install cython
RUN apk del .build-deps gcc musl-dev
```

```console
$ docker build . -t python_test
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM python:3.6-alpine
 ---> 951c2507873b
Step 2/4 : RUN apk add --no-cache --virtual .build-deps gcc musl-dev
 ---> Running in b7ee5058e9cb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/14) Installing binutils-libs (2.30-r1)
(2/14) Installing binutils (2.30-r1)
(3/14) Installing gmp (6.1.2-r1)
(4/14) Installing isl (0.18-r0)
(5/14) Installing libgomp (6.4.0-r5)
(6/14) Installing libatomic (6.4.0-r5)
(7/14) Installing pkgconf (1.3.10-r0)
(8/14) Installing libgcc (6.4.0-r5)
(9/14) Installing mpfr3 (3.1.5-r1)
(10/14) Installing mpc1 (1.0.3-r1)
(11/14) Installing libstdc++ (6.4.0-r5)
(12/14) Installing gcc (6.4.0-r5)
(13/14) Installing musl-dev (1.1.18-r3)
(14/14) Installing .build-deps (0)
Executing busybox-1.27.2-r11.trigger
OK: 127 MiB in 59 packages
Removing intermediate container b7ee5058e9cb
 ---> 3b4065c2e479
Step 3/4 : RUN pip install cython
 ---> Running in e31a21ce281a
Collecting cython
  Downloading https://files.pythonhosted.org/packages/d2/12/8ef44cede251b93322e8503fd6e1b25a0249fa498bebec191a5a06adbe51/Cython-0.28.4.tar.gz (1.9MB)
Building wheels for collected packages: cython
  Running setup.py bdist_wheel for cython: started
  Running setup.py bdist_wheel for cython: still running...
  Running setup.py bdist_wheel for cython: still running...
  Running setup.py bdist_wheel for cython: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/42/e5/78/66cc607f4cc60167268bb2db2b620d8ab5d236fde01036097e
Successfully built cython
Installing collected packages: cython
Successfully installed cython-0.28.4
Removing intermediate container e31a21ce281a
 ---> e325b2eedc3f
Step 4/4 : RUN apk del .build-deps gcc musl-dev
 ---> Running in ea6058db066c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/14) Purging .build-deps (0)
(2/14) Purging gcc (6.4.0-r5)
(3/14) Purging binutils (2.30-r1)
(4/14) Purging libatomic (6.4.0-r5)
(5/14) Purging libgomp (6.4.0-r5)
(6/14) Purging musl-dev (1.1.18-r3)
(7/14) Purging binutils-libs (2.30-r1)
(8/14) Purging mpc1 (1.0.3-r1)
(9/14) Purging mpfr3 (3.1.5-r1)
(10/14) Purging isl (0.18-r0)
(11/14) Purging gmp (6.1.2-r1)
(12/14) Purging pkgconf (1.3.10-r0)
(13/14) Purging libstdc++ (6.4.0-r5)
(14/14) Purging libgcc (6.4.0-r5)
Executing busybox-1.27.2-r11.trigger
OK: 32 MiB in 45 packages
Removing intermediate container ea6058db066c
 ---> c27a2270270b
Successfully built c27a2270270b
Successfully tagged python_test:latest
```
```console
$ docker run --rm -dit --name python_test python_test
$ docker exec -it python_test sh
/ # pip freeze
Cython==0.28.4
```

**Comment by ronlut** [comment]
Well, that's embarrassing.
Spent about 30 mins before opening this issue, going over Cython's source code to see what is going on with that `Scanners` class totally mislead by the `command 'gcc' failed with exit status 1` message.
Thank you for your help :)

**Comment by streamnsight** [comment]
> the preferred way of handling this is with a `Dockerfile` to install dependencies and then removing them afterwards
> 
> ```dockerfile
> FROM python:3.6-alpine
> 
> RUN apk add --no-cache --virtual .build-deps gcc musl-dev
> RUN pip install cython
> RUN apk del .build-deps gcc musl-dev
> ```

Just a quick comment to point out that using the 3 RUN commands above to delete dependencies will not make your image smaller, because it creates 3 different layers for the image.

To effectively save space by removing the installed build dependencies, the 3 commands needs to be ran into one single RUN command, which creates a single layer:

> ```dockerfile
> FROM python:3.6-alpine
> 
> RUN apk add --no-cache --virtual .build-deps gcc musl-dev \
>     && pip install cython \
>     && apk del .build-deps gcc musl-dev
> ```

Resulting image size:
```
python  3.6-alpine               79.1MB
cython  latest                       112MB
cython 3run                          212MB
```

**Comment by joelgenter** [comment]
If the above doesn't work for others, try installing python3-dev (or python2-dev as appropriate).
