### ISSUE TITLE
Include Git In Images w/ tag

### ISSUE THREAD

**Issue by jaitaiwan** [docker-library/python#319]
Hi Folks,

It's common to use pip with git dependencies and in the case of the docker image we don't have git included. I understand this won't want to be included by everyone, so I thought that having it as a tag would be good: python:git python:slim-git etc.

**Comment by tianon** [comment]
I'm not sure I understand -- the non-slim variants already include `git`:

```console
$ docker pull python:3.7
3.7: Pulling from library/python
Digest: sha256:8e1ab8bc0e6d148e84e779687af0698ef8e6503c01f6d182f1ad7101c066c0ff
Status: Image is up to date for python:3.7

$ docker run --rm python:3.7 git --version
git version 2.11.0
```

**Comment by jaitaiwan** [comment]
@tianon I didn't realise that. I guess then I'm just requesting a git-containing variant of the slim container for pip dependencies.

**Comment by tianon** [comment]
Ah, for `slim` and `alpine` variants, `git` is intentionally not included because it's so trivial to install (and many users don't require it):

```dockerfile
FROM python:3.7-slim
RUN apt-get update && apt-get install -y git
```

(adds ~100MB of additional disk space)

```dockerfile
FROM python:3.7-alpine
RUN apk add --no-cache git
```

(adds ~15MB of additional disk space)
