### ISSUE TITLE
Check Downloaded Files

### ISSUE THREAD

**Issue by amouat** [docker-library/python#32]
Could we add some checking of downloaded files to the Dockerfiles?

At the moment they do things like:

    RUN set -x \
	&& mkdir -p /usr/src/python \
	&& curl -SL  "https://www.python.org/ftp/python/$PYTHON_VERSION/Python$PYTHON_VERSION.tar.xz" \
		| tar -xJC /usr/src/python --strip-components=1 \

There is no guarantee that this file hasn't been tampered with or corrupted. It would be great if we could test a checksum or signature file prior to unpacking. To see how to download files securely, have a look at the Wordpress and MongoDB Dockerfiles:

https://github.com/docker-library/wordpress/blob/990b1b00b8ca4903e11e53e908b1996fbaab3c1a/Dockerfile
https://github.com/docker-library/mongo/blob/fc66d9cbedac47806c7ae05b1b291c4ee32f6e6a/2.8/Dockerfile

**Comment by yosifkit** [comment]
Thanks, we must have missed this when we were adding pgp signature checking to the other images.  I'll ask @Moghedrin to work on it :wink:.

**Comment by tianon** [comment]
Oooh, ".asc" files.  <3

**Comment by amouat** [comment]
Cool, thanks :)
