### ISSUE TITLE
Improper signal handling on alpine

### ISSUE THREAD

**Issue by rchernobelskiy** [docker-library/python#328]
When pressing `Ctrl+C`, or running `docker stop`, there is no effect in the alpine version of python.
Running the `test.py` locally and in stretch version of python, it terminates correctly.

Steps to reproduce:
test.py
```
import threading
import signal

interruptEvent = threading.Event()

def interrupt_handler(sig, frame):
    print('interrupted, exiting.')
    exit(1)

signal.signal(signal.SIGINT, interrupt_handler)
signal.signal(signal.SIGTERM, interrupt_handler)

interruptEvent.wait(30)
print("clean exit")
exit(0)
```

Dockerfile
```
FROM python:3.7-alpine
COPY test.py /app/test.py
ENTRYPOINT ["/usr/local/bin/python", "/app/test.py"]
```

Steps:
```
docker build . -t testsig
docker run -it --rm testsig
<Ctrl+C>
```

**Comment by rchernobelskiy** [comment]
on the alpine version, it seems that the signal handler is called exactly after the time specified in `wait(..)`

**Comment by tianon** [comment]
Looks like it's probably https://stackoverflow.com/a/51109558/433558

**Comment by tianon** [comment]
(Which links to https://bugs.python.org/issue34004, which appears to be the upstream bug tracking this very issue.)

**Comment by rchernobelskiy** [comment]
Yeah that looks right @tianon thanks for looking into it and for the quick reply!
