### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by bitliner** [docker-library/python#33]
Cannot install anything using pip, the exception it throws is the one described [here](https://github.com/pypa/pip/issues/2130)

**Comment by yosifkit** [comment]
As you say https://github.com/pypa/pip/issues/2130#issuecomment-71814028, it seems to be an issue when running on AWS, not with the image.  If there is really a problem with the image, let us know what we can fix.

**Comment by nkadel-skyhook** [comment]
This problem just recurred with the "certifi" package, version 2015.9.6.2. It's soluble by reverting back to version 2015.4.28
