### ISSUE TITLE
debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by santiagobasulto** [docker-library/python#333]
Helllo folks, I just built from `python:2.7-jessie` and got the message:

```
debconf: delaying package configuration, since apt-utils is not installed
```

I ended up installing it anyways for other purposes (and I assume most people might do it). Isn't it worth to put it in the image? Or it's a something I should ask to the people from `docker-library/buildpack-deps`?

**Comment by tao12345666333** [comment]
> > >Is there any harm (barring the warning) caused by not having this package installed?

> > No, it has not yet stopped anything from running. Just a warning, and nothing else.

> > - tianon/docker-brew-ubuntu-core#59 (comment)

> Since this is just a warning, there is no need for us to install an extra package that users cannot remove later.
> - https://github.com/debuerreotype/docker-debian-artifacts/issues/39 

This is just a warning.

**Comment by santiagobasulto** [comment]
Great! Asking just in case.
