### ISSUE TITLE
Having issues with gpg in python:alpine image

### ISSUE THREAD

**Issue by yashbhutwala** [docker-library/python#336]
Hi,

I'm not sure if it's something that I'm doing, but I'm having issues using gpg with specifically the python:alpine image.  I've verified it works using the python:3 image.  This is the error I get:

`/bin/sh: gpg: not found`

`The command '/bin/sh -c gpg --import my_key.asc' returned a non-zero code: 127`

Anyone else having issues import gpg keys on the alpine image, or if you know what I'm doing wrong, please do let me know.

**Comment by wglambert** [comment]
The Alpine variant doesn't include gpg
https://github.com/docker-library/docs/tree/master/python#pythonalpine
>To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Comment by yashbhutwala** [comment]
Thanks @wglambert.  So I tried to install gpg using the following command: 

`apk add --update gpg`

`ERROR: unsatisfiable constraints:
  gpg (missing):
    required by: world[gpg]`

Also, how come gpg is used when building the alpine image here: https://github.com/docker-library/python/blob/0c0365d804c2ef4ee8edef652e6a39cdf461e3b2/3.7/alpine3.8/Dockerfile#L32

**Comment by yashbhutwala** [comment]
Awesome!  Thank you @wglambert for the help.
