### ISSUE TITLE
Multiple python versions included

### ISSUE THREAD

**Issue by dlangeland** [docker-library/python#345]
It is unclear to me if this intentional, but I get this:
```
docker pull python:3.6

$ docker run -it python:3.6 python3 --version
Python 3.6.6
$ docker run -it python:3.6 /usr/bin/python3 --version
Python 3.5.3
```
It seems like multiple Python versions are included in the same image. Is this intentional? 3.6.6 is located in /usr/local/bin/python3.

**Comment by wglambert** [comment]
See https://github.com/docker-library/python/issues/253#issuecomment-354845818 https://github.com/docker-library/python/issues/174#issuecomment-382460956
>This is kind of an unfortunate side-effect of our use of buildpack-deps in the non-slim variants


We have made sure that PATH is set appropriately such that the Python installed by this image is preferred.
https://github.com/docker-library/python/blob/88812635c8ad7ff06a8a3755616a1040df222f3c/3.6/jessie/Dockerfile#L9-L10

**Comment by dlangeland** [comment]
Got it. Thanks for the reply.
