### ISSUE TITLE
Support for Python 2.7, Python 3.6 and Python 3.7 in a single docker image file

### ISSUE THREAD

**Issue by vinay-is** [docker-library/python#353]
Can we have the support of Python 2.7, Python 3.6 and Python 3.7 in a single docker image. I see there are 2 different images one for Python 2.7 and Python 3.6 and other one for Python 2.7 and Python 3.7

In my use case I need to have all three Python 2.7, Python 3.6 and Python 3.7 in a single docker image. So wondering how we can achieve this.

**Comment by tianon** [comment]
We have no plans to create such an image (especially given the discouraged/deprecated nature of Python 2.7 to begin with).

Your best bet would to create your own image (either based from ours adding one version or the other, or based from something like Debian and simply installing both via the distribution package manager).

**Comment by vinay-is** [comment]
Thanks for your feedback. Can you please let me know how I can install via distribution package manager, I am new to Dockers hence asking.

**Comment by tianon** [comment]
That's not really a Docker thing, that's more of a distro thing -- for example, in Debian it'd be something like `apt-get install -y python python3`.
