### ISSUE TITLE
Python version is 3.6.5 in the Docker Image "2.7.15-alpine3.7"

### ISSUE THREAD

**Issue by vinay-is** [docker-library/python#354]
I am using this docker image "2.7.15-alpine3.7"

and the Python3 version in this image is Python 3.6.5 from the name I was expecting the version number of python3 to be something like "3.7.x". So I think the Python3 version in should be changed to "3.7.x" in this Docker image to make it consistent with its name.

**Comment by wglambert** [comment]
Could you post the output of `docker run --rm python:2.7.15-alpine3.7 python -V` also there isn't a `python3` in the image, just `python2`

```console
$ docker run --rm python:2.7.15-alpine3.7 python -V
Python 2.7.15
```

If you want python 3.7 then specifying the version will give the appropriate version
```console
$ docker run --rm python:3.7.0-alpine3.7 python -V
Python 3.7.0
```
```console
$ docker run --rm python:3.7.1-alpine3.7 python -V
Python 3.7.1
```
