### ISSUE TITLE
Multiple Python version included mess cron

### ISSUE THREAD

**Issue by Oliv4945** [docker-library/python#360]
Hi,

As discussed in #345 and #253, Python 3.6, 3.5 and 2.7 are included in the image `python:3.6-stretch`.
It has been answered that `We have made sure that PATH is set appropriately such that the Python installed by this image is preferred.`, but I just found a case where it does not work: my service is a cron runing a python script:
`*/10 * * * * python3 /solvers-server/app/utils/ephemerisUpdate.py >> /tmp/debug.log 2>&1`

In that case python3 links to python3.5 and not python3.6

```
#ls -al /usr/bin/python3
lrwxrwxrwx 1 root root 9 Jan 20  2017 /usr/bin/python3 -> python3.5

#ls -al /usr/local/bin/python3
lrwxrwxrwx 1 root staff 9 Sep  5 03:42 /usr/local/bin/python3 -> python3.6
```

**Comment by tianon** [comment]
Yep, when you run `cron` inside the container, it likely does not preserve `PATH` from the image configuration (and probably sanitizes `PATH` as a core/explicit design feature).  Unfortunately, fixing this is something that I think is out of the scope of the intended use of this image.  We can't possibly include appropriate configuration for fixing `PATH` in every utility which might munge it (`sudo` is another good example of a command which explicitly and intentionally sanitizes/changes `PATH`).

**Comment by tianon** [comment]
I'm not sure I understand the benefit? If we use `dpkg-divert`, it will definitely have the potential to break things that APT tries to do, for example, so I'm still very much of the opinion that this is outside the realm of what this image can reasonably be expected to provide by default.
