### ISSUE TITLE
Issue building arm images with qemu: exec user process caused "no such file or directory

### ISSUE THREAD

**Issue by circa10a** [docker-library/python#363]
In travis I'm running:

`docker run --rm --privileged multiarch/qemu-user-static:register`

But still end up with the following error:

`standard_init_linux.go:190: exec user process caused "no such file or directory"`

[Link to travis.yml](https://github.com/DirtyCajunRice/docker-plexwebsocketcounter/blob/master/.travis.yml)

[Link to build log](https://api.travis-ci.org/v3/job/480257433/log.txt)

**Comment by escoand** [comment]
@circa10a I'm facing the same problem. What was your solution for it?
