### ISSUE TITLE
How about Debian sid?

### ISSUE THREAD

**Issue by KOLANICH** [docker-library/python#364]

**Comment by tianon** [comment]
Also known as "Debian Unstable" (and for good reason -- it's the main place
Debian development occurs, it's essentially Debian's "master branch"); we
(the image maintainers) are not comfortable officially supporting an image
based on Unstable, but it shouldn't be difficult for someone to create from
what we've got (I'm guessing just changing FROM would probably mostly work).

**Comment by KOLANICH** [comment]
>we (the image maintainers) are not comfortable officially supporting an image based on Unstable

Why not? It is known to be unstable, so users use it on own risk. But at least the packages are not rotten.

**Comment by wglambert** [comment]
Since this isn't something we're willing to support I'm going to close; if someone wanted to use Debian sid they can build their own Dockerfile after swapping the `FROM` line
