### ISSUE TITLE
Use checkinstall instead of make install

### ISSUE THREAD

**Issue by KOLANICH** [docker-library/python#367]

**Comment by tianon** [comment]
Why?

**Comment by KOLANICH** [comment]
If I remember right, when programs are installed with `make install`, they are not registered in package manager and it doesn't know that the package is installed. Thks may cause troubles if one installs a package dependent on the one installed from source - the pm will overwrite the built version with the one from from packages.

**Comment by tianon** [comment]
I can't find anywhere that the Python project recommends the use of `checkinstall`, so I'm going to close.  If we can find some upstream documentation suggesting it, I think that would be stronger grounds for reconsidering.
