### ISSUE TITLE
Excessive size of the non-slim python images

### ISSUE THREAD

**Issue by johnmcdowell** [docker-library/python#37]
Perhaps this is not the right place for such a discussion, but I'm curious if it's really good practice to be including so many likely unnecessary modules in the non-slim images.

The slim version is 200MB, and the 2.7 onbuild you use in the example docs is 744MB, as of this writing.

Is this extra 540 MB of cruft really worth the extra transfer and load time?

**Comment by yosifkit** [comment]
The reason for the large size is to make it easy for a dev to not have to worry about system dependencies when doing `pip install` (which makes the `onbuild` image actually possible).  Most of this large size is also shared with the other language stacks (https://registry.hub.docker.com/_/buildpack-deps/).  For those that are worried about size and know which system libraries that they need, we have the slim versions that contain just enough to run the language.

**Comment by johnmcdowell** [comment]
Closing this given it's by design. We could make the docs clearer on the tradeoffs of size versus inclusion effort.
