### ISSUE TITLE
ARMv7 - Processor architecture changed without notice

### ISSUE THREAD

**Issue by DimaK-tracxpoint** [docker-library/python#370]
We have a docker spec, using python:2.7 as a base. Our code needs a C library, which is compiled for "armhf" architecture.
Since about January 22 2019, newly built containers began to fail in run-time. Short investigation revealed that recent builds of python container have different ld architecture, which prevents our library from loading. 
Please advise.

**Old one:**
```
root@xxxxxxxxxxxx:/home/web_relay# uname -a
Linux xxxxxxxxxxxx 4.14.52-0-rpi2 #1-Alpine SMP Tue Jun 26 08:55:40 UTC 2018 armv7l GNU/Linux
root@a092c63949c9:/home/web_relay# ls -la /lib
total 32
drwxr-xr-x  1 root root 4096 Sep  5 12:47 .
drwxr-xr-x  1 root root 4096 Jan 24 13:56 ..
drwxr-xr-x  1 root root 4096 Sep  6 12:10 arm-linux-gnueabihf
lrwxrwxrwx  1 root root   21 Sep  5 12:47 cpp -> /etc/alternatives/cpp
drwxr-xr-x  2 root root 4096 Aug 31 00:00 init
lrwxrwxrwx  1 root root   30 Jan 14  2018 ld-linux-armhf.so.3 -> arm-linux-gnueabihf/ld-2.24.so
drwxr-xr-x  3 root root 4096 Aug 31 00:00 lsb
drwxr-xr-x  3 root root 4096 Aug 31 00:00 systemd
drwxr-xr-x 15 root root 4096 Dec 28  2017 terminfo
drwxr-xr-x  3 root root 4096 Aug 31 00:00 udev

```
**Recent ones:**
```
root@xxxxxxxxxxxx:/home/web_relay# uname -a
Linux xxxxxxxxxxxx 4.14.52-0-rpi2 #1-Alpine SMP Tue Jun 26 08:55:40 UTC 2018 armv7l GNU/Linux
root@xxxxxxxxxxxx:/home/web_relay# ls -la /lib
total 32
drwxr-xr-x  1 root root 4096 Jan 23 10:41 .
drwxr-xr-x  1 root root 4096 Jan 24 13:53 ..
drwxr-xr-x  1 root root 4096 Jan 23 18:30 arm-linux-gnueabi
lrwxrwxrwx  1 root root   21 Jan 23 10:41 cpp -> /etc/alternatives/cpp
drwxr-xr-x  2 root root 4096 Jan 22 15:00 init
lrwxrwxrwx  1 root root   28 Jan 14  2018 ld-linux.so.3 -> arm-linux-gnueabi/ld-2.24.so
drwxr-xr-x  3 root root 4096 Jan 22 15:00 lsb
drwxr-xr-x  3 root root 4096 Jan 22 15:00 systemd
drwxr-xr-x 15 root root 4096 Dec 28  2017 terminfo
drwxr-xr-x  3 root root 4096 Jan 22 15:00 udev
```

**Comment by yosifkit** [comment]
Is it pulling the same arch-specific image? (https://github.com/docker/for-linux/issues/463).

Can you try pulling the specific arch that you want? We push each arch also to a specific namespace:

> -	**Supported architectures**: ([more info](https://github.com/docker-library/official-images#architectures-other-than-amd64))  
>	[`amd64`](https://hub.docker.com/r/amd64/python/), [`arm32v5`](https://hub.docker.com/r/arm32v5/python/), [`arm32v6`](https://hub.docker.com/r/arm32v6/python/), [`arm32v7`](https://hub.docker.com/r/arm32v7/python/), [`arm64v8`](https://hub.docker.com/r/arm64v8/python/), [`i386`](https://hub.docker.com/r/i386/python/), [`ppc64le`](https://hub.docker.com/r/ppc64le/python/), [`s390x`](https://hub.docker.com/r/s390x/python/), [`windows-amd64`](https://hub.docker.com/r/winamd64/python/)

**Comment by tianon** [comment]
This honestly sounds to me like a case of https://github.com/moby/moby/issues/34875, so unfortunately, I don't think there's much we can do at the image level here.
