### ISSUE TITLE
python3.6-alpine pip 19 bug

### ISSUE THREAD

**Issue by stevenmwade** [docker-library/python#372]
Pip 19 has a bug https://github.com/pypa/pip/issues/6197 which is causing builds to break with the `python3.6-alpine`. Are there past versions to be able to pull from in the mean time or will this need to be a manual process?

**Comment by tianon** [comment]
Certainly, that's exactly what https://github.com/docker-library/repo-info is for.

See https://github.com/docker-library/repo-info/blob/master/repos/python/remote/3.6-alpine.md, but especially https://github.com/docker-library/repo-info/commits/master/repos/python/remote/3.6-alpine.md, we see https://github.com/docker-library/repo-info/commit/81ae0ddc810e8cd4bdd0fe49c68ea9357116f81b#diff-9cc79fc4f8d05af146299c9d1e360deb, which has the change we're interested in:

```diff
-# Wed, 26 Dec 2018 13:15:40 GMT
-ENV PYTHON_PIP_VERSION=18.1
-# Wed, 26 Dec 2018 13:15:45 GMT
+# Sat, 26 Jan 2019 13:17:00 GMT
+ENV PYTHON_PIP_VERSION=19.0.1
+# Sat, 26 Jan 2019 13:17:10 GMT
```

But we actually want to go just a _little_ further back to https://github.com/docker-library/repo-info/commit/37e362b59a655315381180f58d2ead205ce8cb4b#diff-9cc79fc4f8d05af146299c9d1e360deb, where `amd64` got that update, which gives us the following image digests:

```diff
-$ docker pull python@sha256:4ae5142f052c4efd0bede8483f8ca43a73e8fcfce5dbf8f581967c2c9bac597b
+$ docker pull python@sha256:ce1e79033c018947249554327f0c803d833e5f17c78f173a2cb1a633f691eb30
```

So if you use `python@sha256:4ae5142f052c4efd0bede8483f8ca43a73e8fcfce5dbf8f581967c2c9bac597b` in place of `python:3.6-alpine`, you should get the older version that still has PIP 18.1.

**Comment by stevenmwade** [comment]
Perfect, I spent almost an hour trying to google search for this exactly and apparently didn't have the Google-fu to find it.
