### ISSUE TITLE
Images with multiple versions?

### ISSUE THREAD

**Issue by JulienPalard** [docker-library/python#373]
I'm reopening https://github.com/docker-library/python/issues/346 because it looks like it make sense, I'm also using tox in my CI and would love to have an official Python docker image with multiple versions packed in it.

At least 3.6 and 3.7, but I can imagine some people needing more.

(In fact I used the https://github.com/docker-library/python/issues/253 issue as a feature þ and it looks like fixed in the 3.7 image)

**Comment by tianon** [comment]
This is not something we plan to officially support in this image.  The matrix on this would be a bit crazy to try and keep track of (and we already have a lot of versions and variants that we explicitly support today).

That being said, it shouldn't be _too_ hard to take what we've got and generalize it to something that can be used to build/embed multiple versions instead, although it's not going to be trivial.

See also https://github.com/pyenv/pyenv, which is a project explicitly designed to help do this sort of thing.

**Comment by warsaw** [comment]
I am supporting "semi-official" images of many Python versions, including the latest for 2.7, and 3.4-3.8 (alpha) plus git head: 

https://quay.io/repository/python-devs/ci-image
https://gitlab.com/python-devs/ci-images/tree/master

**Comment by tianon** [comment]
@warsaw ♥️❗

Would you be interested in being more involved here and/or us involved there? Would you be interested in maintaining the `python` image in any capacity? 😇

(It's definitely great to communicate again; it's been a long time since we last spoke! 👍)
