### ISSUE TITLE
Regression in Pip

### ISSUE THREAD

**Issue by josephcsible** [docker-library/python#380]
I'm using the `python:alpine` Docker image. Last week, an updated version of it was released, which, among other things, upgraded Pip to 19.0.1. This version of Pip contains bug pypa/pip#6197, a regression from Pip 18.1. As a result, some of my images based on this one are failing to build unless I use one of the workarounds listed there. Would it be possible to update the image again to include Pip 19.0.2, which fixes the regression?

**Comment by wglambert** [comment]
https://github.com/docker-library/python/issues/372

**Comment by josephcsible** [comment]
Fixed in docker-library/official-images@31e4aec
