### ISSUE TITLE
Should slim also install libbz2-dev

### ISSUE THREAD

**Issue by alp82** [docker-library/python#39]
When trying to `pip install pytz` i get the following error message:

    tarfile.CompressionError: bz2 module is not available

Imo libbz2-dev should be installed and included before building python.

**Comment by tianon** [comment]
Indeed, I think that should be included in the `buildDeps` (https://github.com/docker-library/python/blob/c6e8f0d345bd475a80d3c85c13861bb9dc2ea116/2.7/slim/Dockerfile#L22).

Additionally, I think we should rename the [`python-zlib` test](https://github.com/docker-library/official-images/blob/ec0348fd7765cbc2dddd2130718a118e45ad9b50/test/tests/python-zlib/container.py) to `python-imports` or something and update it to also make sure `bz2` imports and can do some basic round-tripping like the zlib test does currently. :+1:

**Comment by denibertovic** [comment]
+1 on this. I just encountered it.

**Comment by denibertovic** [comment]
@tianon is there an ETA on this? Can I help with anything?

**Comment by yosifkit** [comment]
@denibertovic, care to make a PR adding the lib to the `buildDeps` of all the slim Dockerfiles?  Feel free to ping myself and @tianon in the PR. :smile:
