### ISSUE TITLE
Is it planned to release a alpine 3.10 based docker image for python 3.7?

### ISSUE THREAD

**Issue by Colin-b** [docker-library/python#398]
Looking at Dockerfile all I can see is alpine 3.9 and alpine 3.10 is available :)

Thanks again

**Comment by lubo** [comment]
This is probably currently stuck on #401.

**Comment by ulgens** [comment]
The issue is closed and PR is merged, but there is no PR about the change to official-images repo yet. How much should we wait? Is it an automated process or someone's responsbility?
