### ISSUE TITLE
Problem with setlocale

### ISSUE THREAD

**Issue by Xalion67** [docker-library/python#400]
Hello.
In the code, i use the `setlocale()` from the library `locale`.
When building a container docker, an error `locale.error: unsupported locale setting`.
Manipulations with locale-gen didn't help. How to solve this problem?

**Comment by wglambert** [comment]
The image by default has these locales:
```console
$ docker run --rm python:slim locale -a
C
C.UTF-8
POSIX
```

You'll want to install the `locales` package, then uncomment whichever lines in `/etc/locale.gen`, then execute a `locale-gen`
And you can verify your locales are available to use with `locale -a`
```console
$ docker build -t python:test - << EOF
FROM python:slim
RUN apt update && apt install -y --no-install-recommends locales; rm -rf /var/lib/apt/lists/*; sed -i '/^#.* ru_RU.UTF-8 /s/^#//' /etc/locale.gen; locale-gen
EOF
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:slim
 ---> 338ae06dfca5
Step 2/2 : RUN apt update && apt install -y --no-install-recommends locales; rm -rf /var/lib/apt/lists/*; sed -i '/^#.* ru_RU.UTF-8 /s/^#//' /etc/locale.gen; locale-gen
 ---> Using cache
 ---> 07f9307e8c08
Successfully built 07f9307e8c08
Successfully tagged python:test

$ docker run -it --rm python:test bash

root@c3faab6652a6:/# locale -a
C
C.UTF-8
POSIX
ru_RU.utf8

root@c3faab6652a6:/# python
Python 3.7.3 (default, Jun 11 2019, 01:11:15) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, str('ru_RU.utf8'))
'ru_RU.utf8'
>>> locale.getlocale(locale.LC_ALL)
('ru_RU', 'UTF-8')
>>>
```

**Comment by Xalion67** [comment]
Thank you very much, you saved me from torment)
I have only one question left.
When I collected the docker image, I had one warning and an error, but the image was still assembled successfully.
**Warning**: `WARNING: apt does not have a stable CLI interface. Use with caution in scripts`
**Error**: `debconf: delaying package configuration, since apt-utils is not installed`

Here is the complete code of my Dockerfile.
```
# Используем базовый образ для нашего
FROM python:stretch

RUN mkdir /shoper_bot

COPY . /shoper_bot

WORKDIR /shoper_bot

RUN pip3 install --no-cache-dir pytelegrambotapi
RUN pip3 install --no-cache-dir apiai

# Устанавливаем тайм зону
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Устанавливаем локаль
RUN apt update && apt install -y --no-install-recommends locales; rm -rf /var/lib/apt/lists/*; sed -i '/^#.* ru_RU.UTF-8 /s/^#//' /etc/locale.gen; locale-gen

RUN locale -a

CMD ["python3", "bot.py"]
```
What could be the reason?

**Comment by wglambert** [comment]
The warning is just a notice that if you're basing scripts around the `apt` interface that things could change
And the error is that without [`apt-utils`](https://packages.debian.org/stretch/cdebconf) installed there won't be any package configuration prompts
>Debconf is a configuration management system for Debian packages. It is used by some packages to prompt you for information before they are installed.

**Comment by Xalion67** [comment]
Thank you, you saved me a lot of time.
