### ISSUE TITLE
Can't pull python:3.7-buster for linux/amd64 - "no matching manifest for linux/amd64 in the manifest list entries"

### ISSUE THREAD

**Issue by nhanb** [docker-library/python#406]
To reproduce:
```
▶ docker pull python:3.7-buster
3.7-buster: Pulling from library/python
no matching manifest for linux/amd64 in the manifest list entries
```

I don't see 3.7 buster on the CI page either: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/python/

**Comment by WhyNotHugo** [comment]
I get the impression that pushing is done after all images are built, and the build is still running (3.7-buster is on that page now, but on the currently running build).

**Comment by nhanb** [comment]
Oh you're right, I didn't realize it was that new. Sorry for the false alarm then.
