### ISSUE TITLE
Cannot mount volumes with spaces on it

### ISSUE THREAD

**Issue by hithwen** [docker-library/python#410]
While docker cli accepts volumes with spaces:
`-v /Users/hithwen/Library/Application\ Support/config:/etc/my-app/config`

When using the pyhton library I get:
```
docker.errors.APIError: 400 Client Error: Bad Request ("create /Users/hithwen/Library/Application\ Support/config: "/Users/hithwen/Library/Application\\ Support/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")
```

Running Docker version 18.09.2

**Comment by yosifkit** [comment]
This sounds like a problem with the Docker Python SDK (https://github.com/docker/docker-py) whereas this repo is for the Docker image containing Python

**Comment by hithwen** [comment]
Ups sorry about that. Reported in https://github.com/docker/docker-py/issues/2394
