### ISSUE TITLE
Latest python3.6-alpine has conflicts with basehash

### ISSUE THREAD

**Issue by ar0ne** [docker-library/python#415]
Hi All, 

Latest `python:3.6-alpine` has some conflicts with [basehash](https://github.com/bnlucas/python-basehash/). Any suggestions on this issue?

Example: https://gist.github.com/ar0ne/153e3e1253ebf67cab11185e12dd196e

Note: Only switching to `python:3.6-alpine3.9` works for now.

**Comment by wglambert** [comment]
>error in BaseHash setup command: "values of 'package_data' dict" must be a list of strings (got '*.py')

Something related to this line https://github.com/bnlucas/python-basehash/blob/master/setup.py#L39

**Comment by yosifkit** [comment]
>The big thing that stands out to me is the installation of `python3-dev` for basically the same reasons we blocked `php-*` packages in docker-library/php#542 (tldr, you get modules compiled against a different version of [python] and [...] two versions of [python] installed).
>
> \- from https://github.com/docker-library/python/issues/378#issuecomment-466187772

And from the build log:

> (2/3) Installing python3 (3.7.3-r0)

Which means there is python 3.6.9 from the image, compiled from source, and python 3.7.3 from alpine packages.

**Comment by ar0ne** [comment]
> > The big thing that stands out to me is the installation of `python3-dev` for basically the same reasons we blocked `php-*` packages in [docker-library/php#542](https://github.com/docker-library/php/pull/542) (tldr, you get modules compiled against a different version of [python] and [...] two versions of [python] installed).
> > - from [#378 (comment)](https://github.com/docker-library/python/issues/378#issuecomment-466187772)
> 
> And from the build log:
> 
> > (2/3) Installing python3 (3.7.3-r0)
> 
> Which means there is python 3.6.9 from the image, compiled from source, and python 3.7.3 from alpine packages.

I tried without `RUN apk add python3-dev`, but still getting this error.

````dockerfile
FROM python:3.6-alpine
RUN apk update
COPY ./requirements.txt requirements.txt 
RUN pip install -r requirements.txt

$ docker run --rm python:3.6-alpine python --version
Python 3.6.9

$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM python:3.6-alpine
 ---> 47444c9104d0
Step 2/4 : RUN apk update
 ---> Running in f84efb563337
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.2-5-g1aa06c833e [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.2-4-gca30a4d858 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10336 distinct packages available
Removing intermediate container f84efb563337
 ---> 1b64158691e0
Step 3/4 : COPY ./requirements.txt requirements.txt
 ---> 4c8566955a55
Step 4/4 : RUN pip install -r requirements.txt
 ---> Running in 2a6bdc9e7362
Collecting basehash==3.0.4 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/fa/5b/9761a8a0ae3dc80dc3565282d40407761d6c0f30b650e173a661e06db532/BaseHash-3.0.4.zip
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nfa38iy4/basehash/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nfa38iy4/basehash/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-nfa38iy4/basehash/
    Complete output (1 lines):
    error in BaseHash setup command: "values of 'package_data' dict" must be a list of strings (got '*.py')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by wglambert** [comment]
Looks like they have an issue open for this error https://github.com/bnlucas/python-basehash/issues/6
>error in BaseHash setup command: "values of 'package_data' dict" must be a list of strings (got '*.py')

Going to close since there doesn't seem to be anything indicating an issue with the image
