### ISSUE TITLE
support for windows 1903

### ISSUE THREAD

**Issue by mgrandau** [docker-library/python#416]
Need to add 1903 as a tag version. If your python is accessing Windows devices it has to match the release.

**Comment by yosifkit** [comment]
> We don't currently have a place for these to build, unfortunately (we currently use a Windows Server 2019 VM which is nice because it can actually be updated properly, but has the downside that semi-annual releases like 1903 don't get included). ￼￼:disappointed:
>
> https://github.com/docker-library/golang/pull/289#issuecomment-509841894

**Comment by tianon** [comment]
Closing via #643 :+1:
