### ISSUE TITLE
FROM python:latest makes apk add unusable

### ISSUE THREAD

**Issue by TheHunter896** [docker-library/python#417]
Hey there,

Don't really know if this belongs here or in alpine's repo:

I'm building a dockerfile to keep alpine and python always to latest version so I don't have to update the dockerfile all the time for projects. 
I have this dockerfile which does that in an imperfect manner:

```Dockerfile
FROM alpine:latest

RUN apk add --update python3 py3-setuptools python3-dev py3-pip
RUN apk install gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev freetds-dev vim -y
RUN pip3 install --upgrade pip

RUN pip install requests pyodbc selenium urllib3

```
Now this works, but if I still have to change the python library names every now and then.

So to solve that I made this Dockerfile:
```Dockefile
FROM alpine:latest
FROM python:latest

RUN apk add --update
RUN apk install gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev freetds-dev vim -y

RUN pip install requests pyodbc selenium urllib3

```
Turns out that when you use the ` FROM python:latest` the APK command fails:
![image](https://user-images.githubusercontent.com/11830423/65055208-0df0e880-d96f-11e9-9150-f2db376da19a.png)

I'm kind of new to this Docker thingie, and I quite like it, is there something that I am missing here or is this a bug?

**Comment by ad-m** [comment]
See https://docs.docker.com/develop/develop-images/multistage-build/ what does mean when there is multiple "FROM" in single Dockerfile.

It's expected to does ```apk``` when ```python:latest``` is used. ```python:latest``` base on ```debian:buster``` which does not support ```apk```, use ```RUN apt``` or ```FROM python:alpine``` instead. See:
```
$ docker run -it python:latest cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by TheHunter896** [comment]
Ahh! Makes a lot of sense! Thanks :)
