### ISSUE TITLE
There is a tmp file: /root/.wget-hsts

### ISSUE THREAD

**Issue by zaoqi** [docker-library/python#418]

**Comment by yosifkit** [comment]
```console
$ docker run -it --rm python ls -al /root/
total 20
drwx------ 1 root root 4096 Sep 11 04:22 .
drwxr-xr-x 1 root root 4096 Sep 24 00:03 ..
-rw-r--r-- 1 root root  570 Jan 31  2010 .bashrc
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
-rw-r--r-- 1 root root  254 Sep 11 04:27 .wget-hsts
```

At 254 bytes I don't see a problem in having the file.  Is there an issue in this file existing? At most it should be increasing security if dependant images use wget as root for `raw.githubusercontent.com`, `www.python.org` or `github.com`

**Comment by wglambert** [comment]
Going to close since the the 254 byte file shouldn't inconvenience anyone or be an issue
