### ISSUE TITLE
Getting ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found while importing Aerospike version 3.8.0

### ISSUE THREAD

**Issue by somudit** [docker-library/python#421]
Hi here's my docker file :

```
FROM python:3.6
RUN python3 -m venv /venv

RUN apt-get -qy update && apt-get -qy install openssl \
curl \
&& rm -rf /var/lib/apt/lists/* 

WORKDIR /service
COPY requirement.txt requirements.txt
RUN /venv/bin/pip install -r requirements.txt

CMD ["/venv/bin/python", "manage.py", "runserver"]
```

Inside requirements.txt I have aerospike==3.8.0
When I run it I get 

`ImportError:/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by /venv/lib/python3.6/site-packages/aerospike.cpython-36m-x86_64-linux-g`

Is there a way I can install glibc to 2.28 version?

I also tried downgrading aerospike python client but they dont have supporting builds for deb 10.
Here's the list of aerospike clients:
https://www.aerospike.com/artifacts/aerospike-client-c/4.3.14/

I had a 10 mnth old image for which this was working in that the deian version was not updated tp 10.

Alternatively is there a way I can downgrade the debian version?

**Comment by wglambert** [comment]
What's your `manage.py` file so I can try reproducing

The image has glibc 2.28-10

**Comment by mudbb** [comment]
Actually my bad, I just realised its happening because I am using multistage builds. These are the steps to reproduce.
Dockerfile:
```
FROM python:3.6 AS build
RUN python3 -m venv /venv

RUN apt-get -qy update && apt-get -qy install openssl \
curl \
&& rm -rf /var/lib/apt/lists/* 

RUN /venv/bin/pip install aerospike==3.8.0

FROM python:3.6-slim-stretch AS production

RUN apt-get update && apt-get -y install curl \
build-essential \
libc6-dev \
mysql-client \
zlib1g-dev \
libssl-dev \
python-dev \
default-libmysqlclient-dev \
&& rm -rf /var/lib/apt/lists/*

COPY --from=build /venv /venv

WORKDIR /service
COPY . /service

CMD ["/venv/bin/python", "test.py"]
```
test.py

```
import aerospike
```

**Comment by wglambert** [comment]
You're combining different Debian releases; `FROM python:3.6-slim-stretch AS production` is Buster

https://packages.debian.org/stretch/glibc-source
2.24-11+deb9u4 on Stretch

https://packages.debian.org/buster/glibc-source
2.28-10 on Buster

In Buster `mysql-client` isn't there, but `default-mysql-client` looks like its replacement

Also installing `python-dev` creates a separate Python install, the one in the image is from upstream
https://github.com/docker-library/python/blob/cdff21a05616b660073278f13dc560005322349c/3.6/buster/Dockerfile#L26


This Dockerfile should work for you
```Dockerfile
FROM python:3.6-slim-buster

RUN python3 -m venv /venv

RUN apt-get -qy update && apt-get -qy install \
        openssl \
        curl \
        build-essential \
        libc6-dev \
        default-mysql-client \
        zlib1g-dev \
        libssl-dev \
        default-libmysqlclient-dev \
        && rm -rf /var/lib/apt/lists/*

RUN /venv/bin/pip install aerospike==3.8.0

WORKDIR /service
COPY . /service

CMD ["/venv/bin/python", "test.py"]
```

```console
$ docker run -it --rm python:test1 bash

root@4bd034fc87f8:/service# /venv/bin/python
Python 3.6.9 (default, Sep 12 2019, 16:33:49) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aerospike
>>> aerospike.__version__
'3.8.0'
```

**Comment by somudit** [comment]
@wglambert Thanks that worked. :)
