### ISSUE TITLE
I was trying to create alpine3.9 based python 3.7 image but facing gpg key issue.

### ISSUE THREAD

**Issue by pmady** [docker-library/python#435]
wget -O python.tar.xz https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tar.xz
Connecting to www.python.org (151.101.188.223:443)
python.tar.xz        100% |********************************| 16.4M  0:00:00 ETA

+ wget -O python.tar.xz.asc https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tar.xz.asc
Connecting to www.python.org (151.101.188.223:443)
python.tar.xz.asc    100% |********************************|   833  0:00:00 ETA

+ mktemp -d
+ export 'GNUPGHOME=/tmp/tmp.clblfH'
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
gpg: keybox '/tmp/tmp.clblfH/pubring.kbx' created
gpg: keyserver receive failed: Network unreachable

**Comment by tianon** [comment]
https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification has some relevant information that might help you resolve this.

(Closing, since it does work for our official builds and our Travis test builds.)
