### ISSUE TITLE
Why there is no '--enable-optimizations'  for python 2.7 images?

### ISSUE THREAD

**Issue by gcavalcante8808** [docker-library/python#436]
Hello Folks,

Looks like the python 2.7 images aren't using the '--enable-optimizations' in the configure step of python compilation (https://github.com/docker-library/python/blob/cf68ae064414062b255c7074c58f46e81b31c92e/2.7/buster/slim/Dockerfile#L62). Is there any problem or reason to do so?

I just built an image locally with the flag and it worked.

Thanks in advance.

**Comment by wglambert** [comment]
There was a large discussion on this in https://github.com/docker-library/python/issues/160

And a pr close in https://github.com/docker-library/python/pull/357#issuecomment-475803486 due to the extraordinarily longer build times

**Comment by tianon** [comment]
If you look at the build logs for your local build with the flag added right after `./configure ...` runs, you'll probably see something to the effect of "ignoring unknown flag" because Python 2.x doesn't actually support/use this flag (and thus ignores it, which is why your build still works).

**Comment by blopker** [comment]
It looks like the 2.7 Dockerfiles are built off the "caveman" template. This template does not seem to have the optimization flag. We build our own Pythons so I do know that 2.7 does support the optimization flag. Maybe it should be added to the caveman template.

**Comment by tianon** [comment]
I could've sworn this wasn't supported back when we did #357 but either way, I've got #440 open with this change now. :+1:
