### ISSUE TITLE
Support for socket AF_BLUETOOTH

### ISSUE THREAD

**Issue by sergioisidoro** [docker-library/python#444]
Python 3 has documentation for support of Bluetooth with `AF_BLUETOOTH` socket -- [docs](https://docs.python.org/3/library/socket.html)

However, it seems that (at least for linux) it needs bluetooth.h (from e.g. libbluetooth-dev) for that to work, otherwise we get 

`AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'`

Some other issues mentioning this case are, for example 

* https://github.com/ContinuumIO/anaconda-issues/issues/1035
* https://stackoverflow.com/questions/29107537/missing-socket-af-bluetooth-in-anaconda-python

I was wondering if it is possible to add `bluetooth.h` to the build deps, since this part of the standard documentation

**Comment by wglambert** [comment]
Closing with the merge of https://github.com/docker-library/python/pull/445
