### ISSUE TITLE
Size optimizations

### ISSUE THREAD

**Issue by lubo** [docker-library/python#448]
Hi. I've come across a couple of size optimizations, which may sound interesting. By default, Alpine Linux builds packages with `-Os` GCC flag, which optimizes compiled binaries for size. By setting `CFLAGS="-Os"`, I was able to reduce size of `3.8-alpine3.11` image from 112 MB to 83.9 MB (25% smaller). Also, Alpine Linux runs `strip` on all compiled binaries. AFAIK we can imitate that by setting `LDFLAGS="-Wl,--strip-all"`, which strips all symbols from compiled binaries. After setting it, the image size was further reduced to 67.3 MB (40% smaller). Any thoughts?

**Comment by tianon** [comment]
Interesting!  I'm a bit wary of sacrificing performance for size (as `-Os` might), but I think stripping is probably very reasonable.

**Comment by lubo** [comment]
I've stumbled upon [GCC Compiler Tests At A Variety Of Optimization Levels Using Clear Linux](https://www.phoronix.com/scan.php?page=article&item=clear-gcc6-opts&num=1). Although it was done on Clear Linux, I'd guess the performance ratios are roughly the same on Alpine. As you can see, one size doesn't fit all, but `-Os` does IMO pretty well.

**Comment by J0WI** [comment]
See also https://github.com/tianon/dockerfiles/pull/76#discussion_r365464747

**Comment by autoferrit** [comment]
Any chance this change might make it in? This could be a big benefit for users of this image. Is there any reason NOT to do either `CFLAGS="-Os"` or `LDFLAGS="-Wl,--strip-all"`?

**Comment by J0WI** [comment]
`-Os` overwrites `--enable-optimizations` and has a significant impact on performance: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11129

**Comment by lubo** [comment]
Thanks @J0WI for pointing that out. But isn't this phenomenon specific to Python? Could we still considered it for other apps like PHP? Also, `LDFLAGS="-Wl,--strip-all"` should be safe in this case.

**Comment by autoferrit** [comment]
That makes sense. I tested the LDFLAGS locally and worked well for building. I made PR #483 for this in case we want to implement it.

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/python/pull/483 :+1:
