### ISSUE TITLE
bullseye support

### ISSUE THREAD

**Issue by FireballDWF** [docker-library/python#450]
Request for tags/images based on  bullseye (testing).

**Comment by wglambert** [comment]
https://github.com/docker-library/golang/issues/316
>Given that Bullseye is still the "Debian Testing" distribution (and thus not security-supported, might include breakage, etc) and is not currently "frozen" we have no plans to support it yet.

**Comment by oliversalzburg** [comment]
So how about now?

**Comment by yosifkit** [comment]
Already done: https://github.com/docker-library/python/pull/633
