### ISSUE TITLE
Include tox?

### ISSUE THREAD

**Issue by rpavlik** [docker-library/python#452]
I was a bit surprised to see that tox was not installed by default in these images, given that it's suggested by the setuptools documentation. It would be a useful inclusion to allow uniform driving of CI tests.

**Comment by tianon** [comment]
It's not included by default because while it's a *common* tool for Python users in CI, it's not included in the standard Python bundle downloaded from https://www.python.org/ (whereas `pip` is, for example).

**Comment by emonty** [comment]
Also - people use these images as base images for production workloads, so tossing in interactive dev tools like tox (while an awesome tool) would bloat them.

That said - making a tox docker image with

```
FROM python
RUN pip install tox
```

will get you just what you want.

**Comment by rpavlik** [comment]
I mostly use tox on CI, but "wontfix" is fine.
