### ISSUE TITLE
/usr/lib/python2.7/site-packages is ignored by python

### ISSUE THREAD

**Issue by Gladskih** [docker-library/python#457]
In my docker file I run `apk add` with some package which also includes python module.
It's ok on clear alpine base with `apk add python` and so on.
But when I try to use `python:2.7-alpine` as base image I get import error from my script using that module (placed in /usr/lib/python2.7/site-packages/)
The problem is that python sys.path does not contain it:
`['', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages']`

As a workaround I can use
`export PYTHONPATH=/usr/lib/python2.7/site-packages:$PYTHONPATH`

I lost about 3 hour of my life with this problem.

**Comment by wglambert** [comment]
Previous issue on this https://github.com/docker-library/python/issues/43#issuecomment-376351096

>For cases like those, our compiled Python isn't likely to be sufficient for the package's needs, and it will likely make assumptions about the way Debian/Ubuntu distribute and compile Python, so in those cases you're definitely better off installing Python from Debian or Ubuntu directly to then install their .deb file on top.


>if you need packages from Debian, you should probably go FROM debian:xxx and install Python itself from Debian too

**Comment by Gladskih** [comment]
I does not use something from Debian or Ubuntu - only alpine repositories and packages.

**Comment by wglambert** [comment]
Alpine in this regard isn't any different, if you need that package then you should probably go `FROM alpine` and install Python and that package from Alpine's repo as our compiled Python may not be sufficient for what the package expects.

What package/module is it?

**Comment by Gladskih** [comment]
It's Suricata IDS and suricatasc.py.
But why not build "official" image with `apk add python`? Why do you compile it from source instead?

**Comment by wglambert** [comment]
So for that you could either compile it from [source](https://github.com/OISF/suricata/releases) in a Dockerfile `FROM python`
Or install the package in a Dockerfile `FROM alpine` with any required dependencies

https://github.com/docker-library/faq#why-do-so-many-official-images-build-from-source

**Comment by Gladskih** [comment]
Yes, it's what I did before. Thank you for assistance.
But the idea of compilation from sources ignoring repositories looks like we have a huge methodology inconsistency problem.

**Comment by tianon** [comment]
The versions of Python in the repositories of the stable Alpine and Debian releases are going to (usually intentionally) lag behind upstream's "latest and greatest" which is the biggest reason we compile from source in this particular case.

**Comment by Gladskih** [comment]
I thought there are some strong reasons why it lags (like regression testing or security review). Repository for me is like quality mark.
