### ISSUE TITLE
import re not working with python image in docker hub

### ISSUE THREAD

**Issue by SnehashishGiri** [docker-library/python#467]
import re not working with any docker image distribution
i tried using 
FROM python:3.8.2-buster
FROM python:3.8.2
Nothing worked for import re

**Comment by wglambert** [comment]
Seems to work just fine
https://docs.python.org/3/howto/regex.html#performing-matches

```console
$ docker run -it --rm python:3.8.2

Python 3.8.2 (default, Mar 31 2020, 15:23:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> p = re.compile('[a-z]+')
>>> p
re.compile('[a-z]+')
```

Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by SnehashishGiri** [comment]
Thank you. It worked
