### ISSUE TITLE
Not able to install pywin32 

### ISSUE THREAD

**Issue by SnehashishGiri** [docker-library/python#468]
I am trying to build an python app in docker container but  pywin32 not getting installed.
FROM python:3.8.2
WORKDIR /usr/src/app
RUN python -m pip install -U pip
RUN pip install wmi
RUN python -m pip install pywin32

Its throwing error as 
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by SnehashishGiri** [comment]
Tried with 
RUN python -m pip install pypiwin32 
Getting error 
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223 (from pypiwin32)

**Comment by wglambert** [comment]
`No matching distribution found for pywin32>=223`
Are you able to install this outside of a container environment?

**Comment by SnehashishGiri** [comment]
Yes i have a windows 10 Laptop. I am able to install it

**Comment by SnehashishGiri** [comment]
Link to pywin32
https://pypi.org/project/pywin32/
Link to pypiwin32
https://pypi.org/project/pypiwin32/
Both are not working in docker container.
This is a Python extensions for Microsoft Windows Provides access to much of the Win32 API, the ability to create and use COM objects, and the Pythonwin environment.

**Comment by tianon** [comment]
That module is for Windows only; it won't work in a Linux container.

You need to switch to Windows containers if you want a chance at that
module working (but even then, it may or may not work inside a container,
since the Windows container environment is more minimal than a standard
Windows installation).

**Comment by SnehashishGiri** [comment]
What would be the solution to it. As in Windows Container too its not working

**Comment by SnehashishGiri** [comment]
In Windows Container getting error for all pip command.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001636302E3D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001636302E580>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001636302E6D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016363018B50>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016363018610>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

**Comment by tianon** [comment]
That looks to me like https://github.com/docker-library/python/issues/359

**Comment by tianon** [comment]
I've just tested this again today with the latest `python:3.8` image, and it appears to be fixed/working?

```console
$ docker pull python:3.8
3.8: Pulling from library/python
Digest: sha256:8e7dd58a4cb8a8b703ae2fe90cd67e79576524ff388426331151b50a5850b359
Status: Image is up to date for python:3.8
docker.io/library/python:3.8

$ docker run -it --rm python:3.8 powershell
Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\> pip install pywin32
Collecting pywin32
  Downloading pywin32-300-cp38-cp38-win_amd64.whl (9.3 MB)
     |????????????????????????????????| 9.3 MB 3.3 MB/s 
Installing collected packages: pywin32
Successfully installed pywin32-300
PS C:\> pip install pypiwin32
Collecting pypiwin32
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
Requirement already satisfied: pywin32>=223 in c:\python\lib\site-packages (from pypiwin32) (300)
Installing collected packages: pypiwin32
Successfully installed pypiwin32-223
```

**Comment by GeekyChunk** [comment]
use python on wine
