### ISSUE TITLE
Have python3 using bullseye-slim

### ISSUE THREAD

**Issue by plum117** [docker-library/python#474]
Hi,

I wanted to use openJdk 14 wich is natively supported by debian:bullseye-slim.

Could it be possible to have at least python 3.8 built with debian:bullseye-slim?

Thanks

**Comment by plum117** [comment]
See https://github.com/docker-library/python/pull/475

**Comment by tianon** [comment]
I think https://github.com/docker-library/golang/issues/316#issuecomment-577420220 still sums up my current opinion on this very well. 😔

**Comment by plum117** [comment]
Thanks, I was not aware of this post! Sounds like a good reason

**Comment by yosifkit** [comment]
Duplicate #450.
