### ISSUE TITLE
GPG server problem (and additional versions)

### ISSUE THREAD

**Issue by Hartorn** [docker-library/python#476]
Hello there, 

I was reusing the content of the dockerfile, except I was changing the `FROM` part to make cuda image and ubuntu-based image, and I had problem for a while with the gpg commands failing randomly.

After searching a bit, it looks like adding && echo "disable-ipv6" >> ${GNUPGHOME}/dirmngr.conf \` after `export GNUPGHOME="$(mktemp -d)" \` did make the trick for me, and I don't have the problem anymore. So I figured I would drop a comment here, in case you had the problem too.

Else, I was wondering if you guys were open to make more variant of python image, like on top of ubuntu, cuda images and so on ?
If yes, I would be happy to try and give a hand.
If no, well I understand you have to keep the versions limited for maintenance.

Keep up the good work :)

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by yosifkit** [comment]
Yeah, we'd rather not add maintenance with more OS variants.  Thanks for understanding!

**Comment by Hartorn** [comment]
Ok, thanks for the fast return, will close this then
Maybe I will try to make some on my own, and post it here later, as 'unofficial' image

Cheers !
