### ISSUE TITLE
Can't run pip anymore

### ISSUE THREAD

**Issue by Luni-4** [docker-library/python#477]
Since this commit https://github.com/docker-library/python/commit/b818e9441c088295165edf79a791503f1fe7f6f7 I get the following error when I try to build [this](https://github.com/mozilla/task-boot/blob/master/Dockerfile) image:

```
#10 45.65     error: could not create 'build': Read-only file system
#10 45.65     ----------------------------------------
#10 45.65 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/src/taskboot/setup.py'"'"'; __file__='"'"'/src/taskboot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2anvbqko/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/task-boot Check the logs for full command output.
```

Thanks in advance for your help! :)

**Comment by tianon** [comment]
I don't think this is necessarily `pip`'s fault (nor this image) -- that `Dockerfile` seems kind of odd to me (although admittedly, I'm not a "`pip` power user").  I'm not able to reproduce with a simpler invocation of `pip`:

```console
$ cat Dockerfile
FROM python:3.7-alpine3.11
RUN pip install sh

$ docker build . --pull
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.7-alpine3.11
3.7-alpine3.11: Pulling from library/python
Digest: sha256:8acbf2568aaf64337a9ef2d4f15e0813566957b93fa6954c165335d1a54ca617
Status: Image is up to date for python:3.7-alpine3.11
 ---> 61681f520204
Step 2/2 : RUN pip install sh
 ---> Running in 92e8c7976a5e
Collecting sh
  Downloading sh-1.13.1-py2.py3-none-any.whl (40 kB)
Installing collected packages: sh
Successfully installed sh-1.13.1
Removing intermediate container 92e8c7976a5e
 ---> de094f2089a1
Successfully built de094f2089a1
```

Perhaps you could create a smaller reproducer without using BuildKit and the experimental `Dockerfile` syntax?

**Comment by Luni-4** [comment]
> Perhaps you could create a smaller reproducer without using BuildKit and the experimental `Dockerfile` syntax?

Yep, you were right, I was able to build the image without using BuildKit. Thanks a lot for your help @tianon! :smiley:
