### ISSUE TITLE
arm32v6 only alpine based images?

### ISSUE THREAD

**Issue by huntipl** [docker-library/python#481]
Hey, I have couple of Pi0s with docker installed and looking for best python image for them. 
Is there any reason why all images I can see on dockerhub for arm32v6/python are alpine based?

**Comment by yosifkit** [comment]
Debian doesn't support `arm32v6`, only `arm32v5` and `arm32v7`. So if you need Debian, the only Debian builds that would work on the Pi Zero are the `arm32v5` ones  (https://wiki.debian.org/RaspberryPi).

**Comment by huntipl** [comment]
Thanks! Because I got Raspbian Buster running on arm32v6 I assumed that slim image should be also available. That clears thing out.
