### ISSUE TITLE
Alpine 3.12 support?

### ISSUE THREAD

**Issue by outime** [docker-library/python#492]
Alpine 3.12 was released few days ago so I absolutely don't expect it to be ready at all but I wanted to open this issue to track the progress or at least to know if there's any ETA for this. Thanks!

**Comment by tianon** [comment]
There is now! (https://github.com/docker-library/python/pull/493)

(and the ETA is "soon" :smile:)

**Comment by outime** [comment]
@tianon thank you! I guess it'll take some time [to show up](https://hub.docker.com/_/python?tab=tags&page=1) right?

**Comment by tianon** [comment]
Yeah, a bit; see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what for more details. :+1:
