### ISSUE TITLE
vs_buildtools installed into python3.7 Windows Container

### ISSUE THREAD

**Issue by chenbr** [docker-library/python#498]
Is there a image that contains vs build tools? I ask since I need to to install say cytoolz and anything else that gets installed via source from pypi. 
I've also been through the route of trying to install them into the python:3.7.7-windowsservercore-1809 image but they silently fail. Obviously using https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019 to no avail.

**Comment by tianon** [comment]
Yeah, unfortunately not.  If you have a container with the VS tools in it already, you might be able to `COPY --image=python:...` to get our Python into that container (I haven't tested that theory, but I think Python on Windows is pretty self-contained).

There might also be a package in one of the various packaging ecosystems around Windows (chocolatey, etc) that could help install the necessary build tools.
