### ISSUE TITLE
Python 3.8.4 bump included backwards incompatible change to setuptools

### ISSUE THREAD

**Issue by riconnon** [docker-library/python#511]
Upgrading from the `python:3.8.3-alpine3.12` image to `python:3.8.4-alpine3.12` results in a major upgrade of the provided `setuptools` from `47.1.1` to `49.2.0`

This means that this "bugfix" release upgrade which includes security patches also makes a backwards incompatible change making it difficult for consumers of this image to perform security updates.

**Comment by riconnon** [comment]
Further, it occurs to me that if I was simply using the `python:3.8-alpine3.12` or `python:3.8-alpine` tags then this would have manifested even worse, as a silent breakage of my builds without changing anything.

**Comment by yosifkit** [comment]
Hmm, we don't update setuptools directly, but it seems that `get-pip.py` just pulls the newest regardless of pip version being installed (the two images are installing the same version of pip).

**Comment by yosifkit** [comment]
Closing since `get-pip.py` is updating setuptools automatically when it is run.
