### ISSUE TITLE
Removing CWD causes warnings in subsequent commands

### ISSUE THREAD

**Issue by aureq** [docker-library/python#514]
Hi,

When removing `/usr/src/python` the current working directory is also the directory being removed. This causes subsequent commands to complain about not being able to locate the current working directory.

https://github.com/docker-library/python/blob/6e9789038db7717724bc89adaaf13a86882512db/3.8/buster/slim/Dockerfile#L75-L76

As a potential fix, changing the current working directory to / would prevent these warnings : 
```bash
&& make install \
&& cd / \
&& rm -rf /usr/src/python \
```

I guess this is mostly a cosmetic change but I'm not sure if the warnings could cause  problems with the commands after.

**Comment by tianon** [comment]
Yeah, this would probably make sense (although I think it is mostly cosmetic -- we haven't seen any issues with the commands we run after that needing their working directory to exist).

**Comment by tianon** [comment]
Fixed as part of #687 :+1:
