### ISSUE TITLE
python tkinter

### ISSUE THREAD

**Issue by michelejoyce** [docker-library/python#515]
I am running a simple python tkinter script. It has a single button.
When running this script outside of a container (using an interpreter line), it works as expected.
But, when I create an image and run it ..pushing the button does nothing. The subroutine is called only when the GUI is exited. 

```
import tkinter as tk
from tkinter import *

class GUI(tk.Frame) :
   def __init__(self,master=None) :
      #Build the main gui
      Frame.__init__(self,master)

      a = Button(master, text = "PUSH ME NOW PLEASE ",command=lambda: self.makeAlarm())
      a.pack()

   def makeAlarm(self) :
      print("ALARM")

root = tk.Tk()
gui = GUI(root)
gui.mainloop()
```

**Comment by yosifkit** [comment]
Are you using the `slim` or Alpine-based variants? https://github.com/docker-library/python/issues/484#issuecomment-628776773

**Comment by michelejoyce** [comment]
Yes, I'm using python:3.8-slim.
What should I use instead?

Here's my Dockerfile:


#base image
FROM python:3.8-slim

WORKDIR /code

ARG CUSTOM_CRT_URL

WORKDIR /

RUN apt-get update \
    && apt-get install -y librdkafka-dev wget git bash curl jq gcc python3-tk \
    && git clone https://github.com/JeffersonLab/graphical-alarm-client \
    && cd ./graphical-alarm-client/scripts \
    && mkdir /scripts \
    && cp * /scripts \
    && cd / \
    && chmod -R +x /scripts \
    && if [ -z "$CUSTOM_CRT_URL" ] ; then echo "No custom cert needed"; else \
          wget -O /usr/local/share/ca-certificates/customcert.crt $CUSTOM_CRT_URL \
          && update-ca-certificates \
          && export OPTIONAL_CERT_ARG=--cert=/etc/ssl/certs/ca-certificates.crt \
          ; fi \
    && pip3 install --no-cache-dir -r ./graphical-alarm-client/requirements.txt $OPTIONAL_CERT_ARG \
    && rm -rf ./graphical-alarm-client

COPY src/ .

CMD [ "python", "./hello.py"]


________________________________

**Comment by tianon** [comment]
From https://github.com/docker-library/python/issues/484#issuecomment-628776773:

> In order to keep the `slim` images actually slim the library is not kept on purpose. ...
> You should be able to just install the `tk` package from apt, ...

Once you do that, you should have a working `tkinter` module in Python.  The alternative is to use the non-`slim` (default) variants instead, which will already include `tk`.
