### ISSUE TITLE
readline module missing in python:2.7-slim

### ISSUE THREAD

**Issue by crepererum** [docker-library/python#53]
```
Python 2.7.10 (default, Jun  9 2015, 21:06:35) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named readline
```

See https://docs.python.org/2/library/readline.html

Someone could argue that the python-slim only contains software relevant for servers, but sometimes it would be very helpful to get some debug interfaces working. For example iPython works way better when the `readline` module is available.

**Comment by tianon** [comment]
`readline` is a normal module (just like `curses`), so I'm definitely +1 to this working (and have added it to the tests in https://github.com/docker-library/official-images/issues/832)
