### ISSUE TITLE
Upgrade version of pip to 7.x.y

### ISSUE THREAD

**Issue by cancan101** [docker-library/python#54]
Right now I get a lot of:
```
You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by tianon** [comment]
Are you sure you're using the latest version of the image?

https://github.com/docker-library/python/blob/6d962f44cb44c9e8272345aad396f705e723c27b/3.4/Dockerfile#L30 installs 7.0.3

**Comment by cancan101** [comment]
I am extending the `python:2-onbuild` image. I built with `--no-cache` and I still get those warnings.

**Comment by tianon** [comment]
Can you try adding "--pull"?

**Comment by cancan101** [comment]
Ah, okay. That worked.
