### ISSUE TITLE
windowsservercore-ltsc2019 image?

### ISSUE THREAD

**Issue by duckinator** [docker-library/python#545]
Is there a chance an image based on windowsservercore:ltsc2019 could be added?

The upstream URLs can be found [on Docker Hub](https://hub.docker.com/_/microsoft-windows-servercore?tab=description):

> **Featured Tags**
> * ltsc2019 (LTSC) docker pull mcr.microsoft.com/windows/servercore:ltsc2019
> * 2004 (SAC) docker pull mcr.microsoft.com/windows/servercore:2004

Information about the lifecycle for LTSC (Long-Term Servicing Channel) releases can be found on [docs.microsoft.com](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19#long-term-servicing-channel-ltsc):

> This is the release model you're already familiar with (formerly called the “Long-Term Servicing Branch”) where a new major version of Windows Server is released every 2-3 years. Users are entitled to 5 years of mainstream support and 5 years of extended support. This channel is appropriate for systems that require a longer servicing option and functional stability. Deployments of Windows Server 2019 and earlier versions of Windows Server will not be affected by the new Semi-Annual Channel releases. The Long-Term Servicing Channel will continue to receive security and non-security updates, but it will not receive the new features and functionality.

This is related to #416 ("support for windows 1903"), but my understanding is that it may be less of a maintenance burden to add the LTSC branch?

**Comment by tianon** [comment]
My understanding from https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle (and from the Windows Server 2019 instance we have which hasn't received any major base updates and is still functionally 1809) is that LTSC 2019 really still *is* 1809 (note the "OS build" column at that link where 2019 and 1809 have the same version).

**Comment by duckinator** [comment]
Ah, okay, I didn't realize they were the same. I'll go ahead and close this then. :+1:
