### ISSUE TITLE
Is it possible to include the location of site-packages as ENV?

### ISSUE THREAD

**Issue by sindre-nistad** [docker-library/python#546]
In my use case, I need to add some corporate certificate into certify.
Currently, the path was given as `/usr/local/lib/python3.8/site-packages`, but that need to be changed whenever a new minor version of python is released.

I've tried to set it as a environment variable (it is used in multiple stages);

`ENV SITE_PACKAGE="/usr/local/lib/python${PYTHON_VERSION::3}/site-packages"` in order to strip the patch version from `PYTHON_VERSION`, but that causes docker-compose to fail with 

```
ERROR: Service 'api' failed to build : failed to process "/usr/local/lib/python${PYTHON_VERSION::3}/site-packages": unsupported modifier (:) in substitution
```

Any suggestion on how this could be done properly? Without having to write the version.
One possibility would be to include an new `ENV` statement in the python Docker image.

**Comment by wglambert** [comment]
Docker doesn't support arrays for environment variables, so it seems the array gets truncated to just `python`
Same issue as https://github.com/docker-library/php/issues/1059#issuecomment-700062115

```console
$ docker build -t python:test - << EOF
FROM python:3.8
ENV SITE_PACKAGE="/usr/local/lib/python${PYTHON_VERSION::3}/site-packages"
EOF
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.8
 ---> bbf31371d67d
Step 2/2 : ENV SITE_PACKAGE="/usr/local/lib/python/site-packages"
 ---> Running in e9b3edb47a36
Removing intermediate container e9b3edb47a36
 ---> 8b0338dc2d31
Successfully built 8b0338dc2d31
Successfully tagged python:test

$ docker run -it python:test bash
root@bf0334717092:/# echo $SITE_PACKAGE
/usr/local/lib/python/site-packages
```

**Comment by yosifkit** [comment]
`::` is not one of the valid substitutions done by the Dockerfile parser.

Variable replacement expressions in Dockerfile statements that are not interpreted by [`SHELL`](https://docs.docker.com/engine/reference/builder/#shell) (ie. anything but the shell form for `RUN`, `CMD`, and `ENTRYPOINT`), are limited to just a couple valid expressions: https://docs.docker.com/engine/reference/builder/#environment-replacement
