### ISSUE TITLE
Wrong sha256 when updating to new versions

### ISSUE THREAD

**Issue by vikahl** [docker-library/python#553]
- I cloned the repo
- Ran `$ ./update.sh 3.8`
- Built the normal Debian 3.8 image with `docker build .`

This gives me an error for the pip SHA256 checksum:

```
2020-10-15 20:25:03 (3.18 MB/s) - ‘get-pip.py’ saved [1885433/1885433]

+ echo a7596be200c2597d05d0cbc092ab04359c68ff9f50e80878ba4a9e236f24b656 *get-pip.py
+ sha256sum --check --strict -
sha256sum: WARNING: 1 computed checksum did NOT match
get-pip.py: FAILED
```

Only diff is the checksum. Am I doing something wrong when building the images?

```diff
3.8/buster$ git diff Dockerfile
diff --git a/3.8/buster/Dockerfile b/3.8/buster/Dockerfile
index ea85676..f75e2a4 100644
--- a/3.8/buster/Dockerfile
+++ b/3.8/buster/Dockerfile
@@ -73,7 +73,7 @@ RUN cd /usr/local/bin \
 ENV PYTHON_PIP_VERSION 20.2.3
 # https://github.com/pypa/get-pip
 ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
-ENV PYTHON_GET_PIP_SHA256 6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
+ENV PYTHON_GET_PIP_SHA256 a7596be200c2597d05d0cbc092ab04359c68ff9f50e80878ba4a9e236f24b656
```

**Comment by yosifkit** [comment]
Running `update.sh` doesn't change anything for me. Do you perhaps have a proxy that might be messing with things and so getting a sha256 of the wrong thing?

**Comment by yosifkit** [comment]
Have you tried building the checked in version?

**Comment by vikahl** [comment]
> Have you tried building the checked in version?

Yes, that works.

> Running `update.sh` doesn't change anything for me. Do you perhaps have a proxy that might be messing with things and so getting a sha256 of the wrong thing?

There shouldn't be any proxies involved on my end, but something is strange:

```shell
$ curl -fsSL https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py | sha256sum
a7596be200c2597d05d0cbc092ab04359c68ff9f50e80878ba4a9e236f24b656  -

$ curl -o get-pip.py -fsSL https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py && sha256sum get-pip.py
6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c  get-pip.py
```

_As this isn't directly related to the images, feel free to close the issue. But if anyone have ideas on the above I'm very happy to hear them_
