### ISSUE TITLE
Installation of gcc 10 on python:3.8-slim started failing recently

### ISSUE THREAD

**Issue by yhf8377** [docker-library/python#555]
I have a Dockerfile like this:

````
FROM python:3.8-slim

RUN echo 'deb http://deb.debian.org/debian testing main' >> /etc/apt/sources.list \
    && apt-get update && apt-get install --no-install-recommends -y gcc g++
...
````

I used this docker file to install gcc 10 to my build environment. This worked fine until recently (I have a nightly build that started failing since yesterday).

The error messages are:

````
Setting up g++ (4:10.2.0-1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Processing triggers for libc-bin (2.31-4) ...
E: Could not configure 'libc6:amd64'.
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
````

Is there any work around for this?

**Comment by tianon** [comment]
This is definitely due to mixing buster and bullseye (testing) -- you might have luck with something like https://unix.stackexchange.com/a/592703/153467, but your error message is a bit different, so this will likely require a slightly different solution (perhaps some other package that has to be pre-upgraded before you can install what you're actually after).

**Comment by yhf8377** [comment]
I made it working by adding `-o APT::Immediate-Configure=false`. So the new command is

````
RUN echo 'deb http://deb.debian.org/debian testing main' >> /etc/apt/sources.list \
    apt-get install -y --no-install-recommends -o APT::Immediate-Configure=false gcc g++
````

It just stoke me that it worked perfectly fine before I pulled the most recent `python:3.8-slim`. So I am just reporting this in case there was some change that had caused this. Thank you for your help!

**Comment by tianon** [comment]
Glad you got this figured out -- there isn't really anything more we can do here, so I'm going to close. :+1:
