### ISSUE TITLE
libapache2-mod-wsgi-py3 on python 3.8 and 3.9 image

### ISSUE THREAD

**Issue by hansioan** [docker-library/python#559]
I have a python 3.8 image in which I install apache2 and `libapache2-mod-wsgi-py3` which I need for Django. 

I install `libapache2-mod-wsgi-py3` , my pip packages etc. and when I go to my localhost to check if my Django app runs I get an apache2 error that in my `wsgi.py` file: `no module named 'django'`.

This error comes fromt the fact that `libapache2-mod-wsgi-py3` that gets installed is for python 3.7 and not 3.8 and that's why I get the error. If I start from a python 3.7 image it works fine. 

I tried with python 3.9 again an error, same as for 3.8. 

Should it not be the case that if I install `libapache2-mod-wsgi-py3` in a python 3.8 image it should work for 3.8 or is that something I need to do?

Thank you

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

If you're installing libapache2-mod-wsgi-py3 from Debian's package repo then it's also installing Python 3.7 and more from the repo as well 
```console
$ docker run -it --rm python:3.8-slim bash
root@73a5a57e1eb6:/# apt update && apt install libapache2-mod-wsgi-py3
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]      
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]                    
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:5 http://deb.debian.org/debian buster-updates/main amd64 Packages [7856 B]
Get:6 http://security.debian.org/debian-security buster/updates/main amd64 Packages [248 kB]
Fetched 8401 kB in 3s (3172 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apache2-bin bzip2 file krb5-locales libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
  libbrotli1 libcurl4 libgdbm-compat4 libgssapi-krb5-2 libicu63 libjansson4 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblua5.2-0 libmagic-mgc libmagic1 libmpdec2
  libnghttp2-14 libperl5.28 libpsl5 libpython3-stdlib libpython3.7 libpython3.7-minimal
  libpython3.7-stdlib librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 libxml2
  mime-support perl perl-modules-5.28 publicsuffix python3 python3-minimal python3.7 python3.7-minimal
  xz-utils
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom www-browser bzip2-doc krb5-doc krb5-user
  sensible-utils libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap
  libsasl2-modules-otp libsasl2-modules-sql perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl make libb-debug-perl liblocale-codes-perl python3-doc python3-tk
  python3-venv python3.7-venv python3.7-doc binutils binfmt-support
The following NEW packages will be installed:
  apache2-bin bzip2 file krb5-locales libapache2-mod-wsgi-py3 libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libbrotli1 libcurl4 libgdbm-compat4 libgssapi-krb5-2
  libicu63 libjansson4 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
  liblua5.2-0 libmagic-mgc libmagic1 libmpdec2 libnghttp2-14 libperl5.28 libpsl5 libpython3-stdlib
  libpython3.7 libpython3.7-minimal libpython3.7-stdlib librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1 libxml2 mime-support perl perl-modules-5.28 publicsuffix python3
  python3-minimal python3.7 python3.7-minimal xz-utils
0 upgraded, 47 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.0 MB of archives.
After this operation, 129 MB of additional disk space will be used.
```

**Comment by hansioan** [comment]
This is the part about apache and `libapache2-mod-wsgi-py3`
```docker
RUN apt-get -y update \
    && apt-get install -y apache2 apache2-utils ssl-cert libapache2-mod-wsgi-py3 \
    && apt-get install -y default-libmysqlclient-dev
```

As you mentioned  I am installing `libapache2-mod-wsgi-py3` using the regular command: `apt-get -y update && apt-get install libapache2-mod-wsgi-py3 ` (as seen above, and I am aware that I am using `apt-get` but I don't think the issue is from `apt-get`). 

As you also mentioned "installing libapache2-mod-wsgi-py3 from Debian's package repo then it's also installing Python 3.7", which is true, but still the default `python` points to python3.8

The question is why does installing `libapache2-mod-wsgi-py3` also installs python3.7 and even worse why is `libapache2-mod-wsgi-py3` using python3.7? 

In any case, I managed to make python3.8 work by starting from an ubuntu 20.04 image and installing 3.8 there and when I install  libapache2-mod-wsgi-py3 in that image it works fine , doesn't download python3.7 and my Django project works fine.

It's just a bit weird that in a docker environment specifically for python 3.8 there are these issues where python3.7 appears because  libapache2-mod-wsgi-py3 is installed. I understand that not all users of the `python:3.8` image will care about apache, but for the ones who do care it seems weird and complicated to have to deal with python3.7. 

I think the solution might be what is presented at:
https://stackoverflow.com/questions/43330231/500-internal-server-error-mod-wsgi-apache-importerror-no-module-named-django/43354916#43354916
but it feels like too much of a hassle given that the ubuntu:20.04 alternative works.

Thank you

**Comment by tianon** [comment]
There's a fair amount of historical discussion around mixing our Python with Debian's Python in https://github.com/docker-library/python/issues/43 (and why our Python can't reasonably be a drop-in replacement for Debian's, but we also can't block install of Debian's Python like we do in the PHP images because Python is so commonly used for system-level utilities in Debian itself).

**Comment by tianon** [comment]
So I guess the other way to put this is that if you want `libapache2-mod-wsgi-py3` to work in this image and use our Python instead of Debian's, you're going to have to compile mod-wsgi from source against our Python plus Debian's `httpd` headers (something that's likely to be somewhat involved, but to what degree I couldn't really wager a guess since I'm unfortunately totally unfamiliar with mod-wsgi).

**Comment by hansioan** [comment]
Yeah,  like you mentioned, having to to compile mod-wsgi doesn't look like a trivial task and in my case at least I went with another option which was easier for me and it also fit my needs.
Thanks

**Comment by shamanthb** [comment]
> Yeah, like you mentioned, having to to compile mod-wsgi doesn't look like a trivial task and in my case at least I went with another option which was easier for me and it also fit my needs. Thanks

@hansioan 
Would you care to share what solution you ended up using?
