### ISSUE TITLE
Could the source be copied before pip install?

### ISSUE THREAD

**Issue by ziadsawalha** [docker-library/python#56]
Some projects [break up their requirements files](https://pip.readthedocs.org/en/1.1/requirements.html#recursive-requirements) and then reference them from requirements.txt.

Others include a `-e .` to install the package.

Both those cases will fail with this image because the source is copied after the pip install command. What do you think about moving the source copy command to before the pip install (then you also don't need to copy the requirements.txt file separately).

```
FROM python:3.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY . /usr/src/app  #<-- includes requirements.txt and any `-r` dependencies in it
ONBUILD RUN pip install --no-cache-dir -r requirements.txt
```

**Comment by yosifkit** [comment]
Duplicate in django: https://github.com/docker-library/django/issues/7#issuecomment-99616772

**Comment by ziadsawalha** [comment]
Ah, thanks @yosifkit - I tried searching PRs and issue for an explanation but missed that.
