### ISSUE TITLE
Block the installation of Debian's Python packages

### ISSUE THREAD

**Issue by J0WI** [docker-library/python#571]
Similar to https://github.com/docker-library/php/pull/542

Edit: in the case of Python it might be a bit risky since a lot of internal tools depends on it. Thoughts?

**Comment by tianon** [comment]
Yeah, we've discussed this before (although I'm struggling to find references ATM), and the conclusion is that in Python's case this is way too dangerous because there are so many system-level packages/tools that use Python that we can't reasonably block it (unlike PHP).

**Comment by yosifkit** [comment]
Closing since this isn't really safe to do like in the PHP images.
