### ISSUE TITLE
Can't pull python 3.9.2 on amd64

### ISSUE THREAD

**Issue by BrianKopp** [docker-library/python#579]
When I try to pull the python 3.9.2 docker images, I get the following output:

```sh
> docker pull python:3.9.2-alpine
3.9.2-alpine: Pulling from library/python
no matching manifest for linux/amd64 in the manifest list entries

> docker pull python:3.9.2-slim
3.9.2-slim: Pulling from library/python
no matching manifest for linux/amd64 in the manifest list entries
```

I can pull python 3.9.1 just fine.

```sh
> docker pull python:3.9.1-alpine
3.9.1-alpine: Pulling from library/python
ba3557a56b15: Pull complete 
ffd49e023448: Pull complete 
4d208653d5b9: Pull complete 
3123b734f0d4: Pull complete 
4f9b55c25d69: Pull complete 
Digest: sha256:e48dd378740e8dc680553ec91a2f8d80a87743a4ec43494695c21a2323a749ee
Status: Downloaded newer image for python:3.9.1-alpine
docker.io/library/python:3.9.1-alpine
```

System info:

```sh
> docker --version
Docker version 20.10.3, build 48d30b5b32
> uname -a
Linux archlinux.host.local 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux
```

**Comment by tianon** [comment]
That's because the build is still in-progress (https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/python/420/).

See also https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what for a full overview of the lifecycle from a commit here all the way through to an image available on Docker Hub via manifest list. :+1:

**Comment by BrianKopp** [comment]
Oh, so did these just ship today?

**Comment by tianon** [comment]
Yep, hot off the presses: https://blog.python.org/2021/02/python-392-and-388-are-now-available.html

**Comment by BrianKopp** [comment]
awesome thanks!
