### ISSUE TITLE
it install python again when install python3-dev with image: 3.8.8-alpine3.13

### ISSUE THREAD

**Issue by gainskills** [docker-library/python#594]
Docker build file
```
# Base Docker image
FROM python:3.8.8-alpine3.13
RUN apk update && apk upgrade && apk add --no-cache --virtual build-deps gcc python3-dev 
```

Docker builds log:
```
OK: 13884 distinct packages available
OK: 11 MiB in 35 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/54) Installing libgcc (10.2.1_pre1-r3)
(2/54) Installing libstdc++ (10.2.1_pre1-r3)
(3/54) Installing binutils (2.35.1-r1)
(4/54) Installing libgomp (10.2.1_pre1-r3)
(5/54) Installing libatomic (10.2.1_pre1-r3)
(6/54) Installing libgphobos (10.2.1_pre1-r3)
(7/54) Installing gmp (6.2.1-r0)
(8/54) Installing isl22 (0.22-r0)
(9/54) Installing mpfr4 (4.1.0-r0)
(10/54) Installing mpc1 (1.2.0-r0)
(11/54) Installing gcc (10.2.1_pre1-r3)
(12/54) Installing pkgconf (1.7.3-r0)
(13/54) Installing python3 (3.8.8-r0)
(14/54) Installing python3-dev (3.8.8-r0)
```

Does it cause by the system variable for the Python version?

Thanks,

**Comment by wglambert** [comment]
In the container Python is built from source, so yeah installing `python3-dev` has Python from the repo's as a dependency which gets you two Pythons
PHP has the same issue but for that image the Debian PHP packages are blocked https://github.com/docker-library/php/pull/542

Although for Python: https://github.com/docker-library/python/issues/571#issuecomment-760534252
>this is way too dangerous because there are so many system-level packages/tools that use Python that we can't reasonably block it (unlike PHP).
