### ISSUE TITLE
Unable to execute 'gcc': No such file or directory

### ISSUE THREAD

**Issue by dyrnade** [docker-library/python#60]
I was using pip to install cryptography lib and i get above errors. Dockerfile seems to install gcc however it doesnt have gcc. 

unable to execute 'gcc': No such file or directory
unable to execute 'gcc': No such file or directory

    No working compiler found, or bogus compiler options
    passed to the compiler from Python's distutils module.
    See the error messages above.
    (If they are about -mno-fused-madd and you are on OS/X 10.8,
    see http://stackoverflow.com/questions/22313407/ .)
error: Setup script exited with 1

**Comment by yosifkit** [comment]
Which image are you using (`python:3`, `python:2`, `python:slim`)?  What is its image id?

**Comment by dyrnade** [comment]
Sorry forgot to write , python:slim image

**Comment by yosifkit** [comment]
Yeah, `slim` [removes gcc](https://github.com/docker-library/python/blob/15798abb6cfb145344462a345db4b572227fb859/3.4/slim/Dockerfile#L55) to keep it as small as possible. With the slim image you'll need to install any build dependencies that you require for your pip installs. To keep the image slim, you'll also want to remove packages after you are done (in the same `RUN` that they are installed on) Something like the following with all the other packages you will need during the `pip install`.
```dockerfile
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc and-build-dependencies \
    && rm -rf /var/lib/apt/lists/* \
    && pip install cryptography \
    && apt-get purge -y --auto-remove gcc and-build-dependencies
# the --no-install-recommends helps limit some of the install so that you can be more explicit about what gets installed
```

**Comment by jennolsen84** [comment]
@dyrnade if you really care about the size, the best way to do this is to build python wheels (by using an image that inherits from python:3) and save them in an external directory.  Then when building your slimmer image you can just mount that wheelhouse and do a pip install. This is not trivial, but if size is important you can do this strategy.

https://glyph.twistedmatrix.com/2015/03/docker-deploy-double-dutch.html

**Comment by lithiumlab** [comment]
im getting the same error in python 2.7
any suggestions?
using linux alpine

**Comment by tianon** [comment]
The `slim` and `alpine` variants both only include the absolute bare minimum necessary to use the image.  If your usage requires tools such as `gcc`, then you will need to do something like `apk add --no-cache gcc`.

**Comment by lithiumlab** [comment]
Thanks.
Solved it with:
```
RUN mkdir /app
ADD /app/requirements.txt /app/requirements.txt
WORKDIR /app
RUN apk --update add python py-pip openssl ca-certificates py-openssl wget
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python-dev py-pip build-base \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && apk del build-dependencies

```

**Comment by mikkiweesenaar** [comment]
@yosifkit
I get the following error on your suggestion:
```
E: Unable to locate package and-build-dependencies
The command '/bin/sh -c apt-get update         && apt-get install -y --no-install-recommends gcc and-build-dependencies         && rm -rf /var/lib/apt/lists/*         && pip3 install -r /tmp/requirements.txt         && apt-get purge -y --auto-remove gcc and-build-dependencies' returned a non-zero code: 100
```

**Comment by sharego** [comment]
@mikkiweesenaar  i guess `and-build-dependencies` means which some thing you need else, you should replace it to real package names like `python-dev`

**Comment by no-col** [comment]
I'm trying to use skaffold run to run. I locate a Dockfile file. His error may be as follows.
`ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xxwb5a8q/google-cloud-profiler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xxwb5a8q/google-cloud-profiler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2sb5abnl/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-xxwb5a8q/google-cloud-profiler/
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/cpu_profiler.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/backoff.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/__init__.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/builder.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/profile_pb2.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/client.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    copying googlecloudprofiler/pythonprofiler.py -> build/lib.linux-x86_64-3.7/googlecloudprofiler
    running build_ext
    building 'googlecloudprofiler._profiler' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/googlecloudprofiler
    creating build/temp.linux-x86_64-3.7/googlecloudprofiler/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Igooglecloudprofiler/src -I/usr/local/include/python3.7m -c googlecloudprofiler/src/clock.cc -o build/temp.linux-x86_64-3.7/googlecloudprofiler/src/clock.o -std=c++11
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xxwb5a8q/google-cloud-profiler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xxwb5a8q/google-cloud-profiler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2sb5abnl/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
FATA[0248] failed to build: build failed: build failed: building [nocol666/emailservice]: build artifact: unable to stream build output: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1`




My Dockerfile file is as follows
`FROM python:3.7-slim as base

FROM base as builder

RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        g++ \
    && rm -rf /var/lib/apt/lists/*

# get packages
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM base as final
# Enable unbuffered logging
ENV PYTHONUNBUFFERED=1

RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        wget

# Download the grpc health probe
RUN GRPC_HEALTH_PROBE_VERSION=v0.2.0 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

WORKDIR /email_server

# Grab packages from builder
COPY --from=builder /usr/local/lib/python3.7/ /usr/local/lib/python3.7/

# Add the application
COPY . .

EXPOSE 8080
ENTRYPOINT [ "python", "email_server.py" ]`

**Comment by ricoms** [comment]
why all examples provided as solutions are incomplete examples?
