### ISSUE TITLE
Any plan to have support for precise

### ISSUE THREAD

**Issue by ashrafuzzaman** [docker-library/python#61]
Hi guys,
Do you have any plan to support legacy system like `ubuntu precise`, as a lot of existing production environment is still built on `precise`. If you like I would love to come up with a pull request.

**Comment by yosifkit** [comment]
We actually only have the python images based on `debian`, so `ubuntu` images are not something we have looked to do.  Are there specific python libraries that you need from `precise`?  From my understanding, running python in a container means that I don't have to care what "OS" it is packaged inside of, be it debian, ubuntu, or centos, it will just work.  Using the non-slim versions I need only to `pip install` my dependencies and my python application can be up and running.

**Comment by ashrafuzzaman** [comment]
Sorry for taking so much time to reply. In ideal world we should be able to install packages using pip. But that is not the case. For an example installing [pil](http://codeinthehole.com/writing/how-to-install-pil-on-64-bit-ubuntu-1204/) is different in different os.

**Comment by tianon** [comment]
I think https://github.com/docker-library/python/pull/65 and https://github.com/docker-library/python/issues/104 are relevant discussions along a similar vein to this one.

I can say for sure that we won't be adding a `precise` variant unless there is a _really_ strong justification for doing so.

**Comment by eromoe** [comment]
Many software installation are different by platfom. I'd like to use python docker base on ubuntu, because I only know installation steps on ubuntu.

**Comment by yosifkit** [comment]
Thank you for your contribution and time.

Unfortunately this is not something we want to support and maintain. For most users, just having "python" at a specific version fulfills all their requirements. They don't need to care about the underlying distribution it is running within. If they are running their own application, in python for example, and they are unable to run it in our Debian, Alpine, or Windows Server Core based python images, then they are free to install python and their required dependencies within CentOS, Ubuntu, or other base distribution image.

For many images here are the variants that we maintain with short descriptions and why we have them:

 - `debian`
   - what: the default image that is based on [Debian](https://www.debian.org/) but doesn't usually say `debian` in the name
   - why: the smallest mainline distro using glibc; stable set of libraries provided though `apt`; we have familiarity with Debian; it is similar enough to Ubuntu for most users
 - `slim`:
   - what: a smaller version of the Debian based image; to make it really easy to use, many of the language images include commonly used libraries and development headers; this variant doesn't install them
 - `stretch` (or `wheezy`)
   - what: Debian based image built on the next (or previous) stable [release of Debian](https://www.debian.org/releases/)
   - why: to help transition major base image bumps without affecting users drastically
 - `alpine`
   - what: based on the [Alpine Linux](https://alpinelinux.org/) image (which itself is only about 4-5MB)
   - why: gives users an even smaller image to base their software on; caveat is that not everything is libc agnostic and may not work with musl libc
 - `windowsservercore`
   - what: Windows based image that only runs on Windows; based on [`microsoft/windowsservercore` image](https://hub.docker.com/r/microsoft/windowsservercore/)
   - why: allow users to run software written for Windows in a container
 - `nanoserver`
   - what: smaller Windows based image that only runs on Windows; based on [`microsoft/nanoserver`](https://hub.docker.com/r/microsoft/nanoserver/) (base image ~333MB vs ~5GB)

**Comment by antinescience** [comment]
@yosifkit - appreciate the in-depth response. You note that there exists a `stretch` tag based on the next stable release of Debian, but it doesn't appear like that exists in Dockerhub; nor do the `wheezy` tags exist for 3.5 or 3.6. Is this something y'all would entertain a PR for? I'd be happy to do the legwork if it's something of interest, I just don't want to step on toes if it's already in progress.

**Comment by yosifkit** [comment]
That was just a general description of the types of variants that we have.  We only have `wheezy` tags for the older versions of python since that is where users are most likely to run into compatibility with newer system libraries.  As for a `stretch` based image for python, we have not yet seen a need for it, but does make sense for Python 3.6+. Maybe we should add it with the bump to 3.6.2 at the [end of June](https://www.python.org/dev/peps/pep-0494/)?  Given that [python 3.7 is about a year away](https://www.python.org/dev/peps/pep-0537/), `stretch` should definitely be the default; adding a `stretch` variant to 3.6 will give the option to try `stretch` while still having the default `jessie` available.
