### ISSUE TITLE
docker: No valid trust data for 3.9.5-slim

### ISSUE THREAD

**Issue by raratiru** [docker-library/python#612]
I am updating a docker-container and I realized that the python version is still `3.9.0`.

**The issue:** 
```bash
$ export DOCKER_CONTENT_TRUST=1
$ docker run -it --rm --name container_name python:3.9.5-slim bash
docker: No valid trust data for 3.9.5-slim.
```

**The trap:**
```bash
$ export DOCKER_CONTENT_TRUST=1
$ docker run -it --rm --name container_name python:3.9-slim bash  # 3.9-slim NOT 3.9.5-slim
# echo $PYTHON_VERSION
3.9.0
```

**Comment by wglambert** [comment]
We don't have any control over or involvement in the signing process of the images we publish
https://github.com/docker-library/official-images/issues/6838

**Comment by raratiru** [comment]
OK, thank you! That left me speechless...
