### ISSUE TITLE
Bytecode cache (__pycache__) should be precompiled for standard library

### ISSUE THREAD

**Issue by mila** [docker-library/python#615]
Python images do not have bytecode cache (`__pycache__`) for the Python standard library. The following command outputs nothing:

```
docker run --rm python:3.9 ls /usr/local/lib/python3.9/__pycache__/
```

This means that Python compiles bytecode when run for the first time. For Docker images, it effectively means that the bytecode has to be compiled on every execution. When I run Docker containers as a non-root user, this fails because of unsufficient permissions.

The performance impact of this is negligible and difficult to measure, but others (Debian, pip) precompile Python bytecode, so I assume that it has some positive impact.

**Comment by tianon** [comment]
We currently intentionally remove the `.pyc` files because when we leave them in, the image is ~30MB larger (and they regenerate very quickly, as you've noted). :grimacing: :sweat_smile:

**Comment by mila** [comment]
OK, good to know. Thanks!
