### ISSUE TITLE
Broken Multi Arch Support

### ISSUE THREAD

**Issue by blackdog308** [docker-library/python#636]
I have been using the below docker build to run tests on my GitLab runner instance.

Around one week ago, the docker set up starting failing. I checked my git history and confirmed that there were no changes to any of the build scripts.

As such I think it must be from the changes made around a week ago in the docker container.

The requirement for the microsoft images is to install the drivers to connect to an MSSQL server with pyodbc

Any ideas? 

Error 

``` Reading package lists...
 Building dependency tree...
 Reading state information...
 Some packages could not be installed. This may mean that you have
 requested an impossible situation or if you are using the unstable
 distribution that some required packages have not yet been created
 or been moved out of Incoming.
 The following information may help to resolve the situation:
 The following packages have unmet dependencies:
  libodbc1 : PreDepends: multiarch-support but it is not installable
  odbcinst1debian2 : PreDepends: multiarch-support but it is not installable
 E: Unable to correct problems, you have held broken packages.
```
Docker Build Info

```image: "python:3.7"

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - mkdir -p .pip
  - pip install -U pip
  - apt-get update -y
  - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/msprod.list
  - apt-get update -y
  - ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
  - apt-get install unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc python3-dev -y
  - apt-get install python-pyodbc -y
  - pip --cache-dir=.pip install -r requirements.txt
 ```

**Comment by blackdog308** [comment]
Also have tried switching to the Debian dependencies as per the the Microsoft instructions:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

```
  - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  - curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
  - apt-get update -y
  - ACCEPT_EULA=Y apt-get install -y msodbcsql17
  - ACCEPT_EULA=Y apt-get install -y mssql-tools
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
  - source ~/.bashrc
  - ACCEPT_EULA=Y apt-get install -y unixodbc-dev
  - apt-get install unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc python3-dev -y
  - apt-get install python-pyodbc -y
```

**Comment by yosifkit** [comment]
That is probably because the default Debian base was updated from `buster` (10) to `bullseye` (11) and so many OS packages have changed. Microsoft hasn't listed a new [apt repo for Debian 11 yet](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17). You can stick with `buster` by adding `-buster` to the python image you are using: e.g. `python:3.7-buster`.

**Comment by m1stermanager** [comment]
big help. thanks a ton

**Comment by blackdog308** [comment]
> That is probably because the default Debian base was updated from `buster` (10) to `bullseye` (11) and so many OS packages have changed. Microsoft hasn't listed a new [apt repo for Debian 11 yet](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17). You can stick with `buster` by adding `-buster` to the python image you are using: e.g. `python:3.7-buster`.

Thanks @yosifkit Learnt something new today about the way the OS works within the image.
