### ISSUE TITLE
Should the python 3.7 base image have access to the lib python-dev packaged for the same version?

### ISSUE THREAD

**Issue by elsmorian** [docker-library/python#638]
Currently we use Python 3.7 from the `python:3.7-slim` and we also use the `libpython3.7-dev` package from Buster to build things etc.

The update to Bullseye broke this. I understand why - python 3.9 is now the default in Bullseye, so it makes sense the all OS python packages are updated too, so `libpython3.7-dev` is unavailable now, and `libpython3.9-dev` is now available. I know we can pin the version of the OS to eg. use `python:3.7-slim-buster` to lock in both the OS and Python versions.

So I can see why it happened and it makes sense from knowing where each package is coming from etc. But it also feels odd to run a python3.7 container, and only have access to a different python version's header files etc?

**Comment by tianon** [comment]
See https://github.com/docker-library/python/issues/480 for some previous discussion of this (which also has links to other threads where this has been discussed as well).

The short version is that I would never recommend installing _anything_ `python` related from Debian (or Alpine) inside these images, and we would block the ability to do so if it weren't likely to break so many packages.

I'm kind of curious why you need this though -- you should be able to find the header files in `/usr/local/include/` already. :confused:
