### ISSUE TITLE
Alpine problem with CPython loading - py3-pillow

### ISSUE THREAD

**Issue by instantlinux** [docker-library/python#642]
## Problem description

I cannot use the `py3-pillow` package from the alpine package repository:
```
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)
```

## Expected result

I should be able to install any of the packaged wheels from the pkgs.alpinelinux.org on this python:3.9.5-alpine3.14 image, and import them in the usual way.

## Steps to reproduce

```
$ docker run -it --rm python:3.9.5-alpine3.14 sh
/ # apk add --update py3-pillow
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
 ...
/ # python3
Python 3.9.5 (default, Jun 29 2021, 01:36:28) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/usr/lib/python3.9/site-packages')
>>> import PIL.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)
```
## Other information
If I run the alpine:3.14 base image, this does not happen: the py3-pillow package seems to work OK.
```
$ docker run -it --rm alpine:3.14 sh
/ # apk add --update python3 py3-pillow
/ # python3
Python 3.9.5 (default, May 12 2021, 20:44:22) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL.Image
>>> 
```

**Comment by instantlinux** [comment]
I will also note this: the maintainers of `pip` provide this disclaimer when using it to install packages into a container image:
```
 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
To summarize the conundrum we users face when designing a `Dockerfile`:
* The Python Packaging Authority says one should install packages using system distro packages rather than `pip`
* The Docker library maintainers say one should use `pip` to install packages

The rock has met the hard place.

**Comment by yosifkit** [comment]
> - The Python Packaging Authority says one should install packages using system distro packages rather than pip

Though I am not sure where this is stated, I would guess that it specifically applies when using the **distribution supplied** `python` since then you will more likely be installing a version of a library that is compatible for that version of python (and probably even tested to work).

But if you are using the `python` from these Docker images, it is compiled from source (in order to provided the most up-to-date `python`) and so you could eventually run into issues when trying to mix python libraries (like `py3-pillow`) made for the Alpine-provided (`apk add`)  python.
