### ISSUE TITLE
Question: How are vulnerabilities patched?

### ISSUE THREAD

**Issue by pollyMath** [docker-library/python#646]
Hi, Team!
This is more of a general docker question.... we have a security tool in our CICD pipeline which would scan last built image and report vulnerable packages according to I guess updated vulnerable packages database.
Anyway, since an image with high vulnerable packages is bad, we are meant to go fix it immediately... but I am confused; aren't base images such as the python ones patched automatically for vulnerable dependencies? Or is it really just built once, version pinned and then one needs to keep patching his Dockerfiles or change to later base image.
Sorry if this is not the place to ask.

**Comment by wglambert** [comment]
See https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
And https://github.com/docker-library/openjdk/issues/449#issuecomment-763027011, https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.

A CVE doesn't imply having an actual vulnerability, and often is even a false positive (given how most distributions handle versioning/security updates in stable releases). If there are actionable items we can resolve, we're happy to do so (and do so actively). We update all Debian based images to include any updates in apt packages at least monthly (we regenerate the base images and then rebuild all dependent images).

**Comment by pollyMath** [comment]
Thanks!! :)
