### ISSUE TITLE
Add 3.7.12-stretch tag

### ISSUE THREAD

**Issue by johnthagen** [docker-library/python#665]
3.7 has been the latest supported version on `stretch`, but as of [3.7.12](https://www.python.org/downloads/release/python-3712/) there doesn't seem to be a `3.7.12-stretch` image built. It would be great if 3.7 images could continue to be built for `stretch` for the remaining lifetime of 3.7.

**Comment by wglambert** [comment]
With Debian Bullseye's release in August the Stretch variants were removed as we only maintain two tracks per distro, given the large load of compilation that happens for each variation https://github.com/docker-library/python/pull/633
