### ISSUE TITLE
Python 3.9.9 released

### ISSUE THREAD

**Issue by daveisfera** [docker-library/python#668]
https://www.python.org/downloads/release/python-399/

**Comment by wglambert** [comment]
The commit's in there https://github.com/docker-library/python/commit/3d43bcf8ddd26ae85fd6a63a7e1d502b445c9cce

Just waiting for a PR to push it to Dockerhub https://github.com/docker-library/python#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by daveisfera** [comment]
Awesome! Thanks
