### ISSUE TITLE
Expired GPG key hard coded into container. 

### ISSUE THREAD

**Issue by drahamim** [docker-library/python#669]
https://github.com/docker-library/python/blob/9242c448c7e50d5671e53a393fc2c464683f35dd/3.8/buster/Dockerfile#L23

It looks like the buster release.gpg was updated october 9th 2021 and this hard coded key is the old one.

**Comment by drahamim** [comment]
Closing this issue. I might be wrong.

**Comment by tianon** [comment]
That key fingerprint is that of Łukasz Langa, who is the release manager for Python 3.8: https://www.python.org/dev/peps/pep-0569/#release-manager-and-crew

(and thus the key which the Python 3.8 release artifacts are signed)

Fetching the key and then listing it, I see it doesn't expire until 2025-05-11 (and even that's more a suggestion than a hard fast rule -- the cryptographic bits are still useful/usable for verifying artifacts if the key itself is marked as "expired"):

```console
root@76407889f751:/# gpg --keyserver pgp.mit.edu --recv-keys 'E3FF2839C048B25C084DEBE9B26995E310250568' 
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: key B26995E310250568: 1 duplicate signature removed
gpg: key B26995E310250568: 1 signature reordered
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key B26995E310250568: public key "\xc5\x81ukasz Langa (GPG langa.pl) <lukasz@langa.pl>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@76407889f751:/# gpg --fingerprint
/root/.gnupg/pubring.kbx
------------------------
pub   rsa4096 2015-05-11 [SC] [expires: 2025-05-11]
      E3FF 2839 C048 B25C 084D  EBE9 B269 95E3 1025 0568
uid           [ unknown] \xc5\x81ukasz Langa (GPG langa.pl) <lukasz@langa.pl>
uid           [ unknown] \xc5\x81ukasz Langa <lukasz@edgedb.com>
uid           [ unknown] \xc5\x81ukasz Langa <lukasz@python.org>
uid           [ unknown] \xc5\x81ukasz Langa (Work e-mail account) <ambv@fb.com>
uid           [ unknown] [jpeg image of size 24479]
sub   rsa4096 2015-05-11 [E] [expires: 2025-05-11]
```

**Comment by drahamim** [comment]
Yeah. I kinda jumped the gun. I am seeing issues using the python3.8-buster image in a github action with Debian's gpg key for their package repos. not sure if thats an issue with the base container or github-actions. Again closed this issue as what I initially opened it for i verified was incorrect.
