### ISSUE TITLE
python 2.7.11

### ISSUE THREAD

**Issue by mattrobenolt** [docker-library/python#67]
See: https://www.python.org/downloads/release/python-2711/

I will try and do a PR later if nobody else gets around to it.

**Comment by tianon** [comment]
Thanks for the prod!

**Comment by mattrobenolt** [comment]
Oh, didn't realize it was that trivial. :) Thanks!

**Comment by yosifkit** [comment]
We try to have an [update.sh](https://github.com/docker-library/python/blob/master/update.sh) in every repo :smile:.
