### ISSUE TITLE
time.time() fails on slim

### ISSUE THREAD

**Issue by thealtofwar** [docker-library/python#674]
Copied from https://bugs.python.org/issue45960:

Given a docker container on raspbian 10.11
based on bullseye:

docker run --rm -it --entrypoint sh python:3.10-slim

time.time() fails with error
```
# python
Python 3.10.0 (default, Nov 18 2021, 00:56:34) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```
based on buster:

docker run --rm -it --entrypoint sh python:3.10-slim-buster
```
python
Python 3.10.0 (default, Nov 18 2021, 02:00:41) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.time()
1638433441.9555993
>>> exit()
```
works as expected

**Comment by tianon** [comment]
This is likely related to https://github.com/moby/moby/issues/40734 -- you'll need to update Docker and libseccomp on your host.  (See also #634)
