### ISSUE TITLE
vulnerability scan failed on python:3.9.9-alpine3.14 and python:3.9.9-alpine3.15

### ISSUE THREAD

**Issue by matanmarciano** [docker-library/python#680]
vulnerability scan failed on python:3.9.9-alpine3.14 and python:3.9.9-alpine3.15 because of expat version (2.4.1-r0).
There is any solution?

Thanks!

**Comment by dlafreniere** [comment]
I'm also seeing a vulnerability reported for `expat@2.4.1-r0`

expat-dev is being installed via APK https://github.com/docker-library/python/blob/master/3.8/alpine3.15/Dockerfile#L49

Checking alpine https://pkgs.alpinelinux.org/packages?name=expat-dev&branch=edge they seem to have the fixed version (2.4.3-r0) available, so I think the docker image just needs to be rebuilt and it should be okay

**Comment by wglambert** [comment]
This PR https://github.com/docker-library/official-images/pull/11684 is going to update to 3.9.10 and get the latest package updates

**Comment by tianon** [comment]
The supported versions have been (re)built now. :+1:
