### ISSUE TITLE
`python:3.9.9` not available for architectures other than Windows

### ISSUE THREAD

**Issue by aitorres** [docker-library/python#681]
As of its most recent push, the `python:3.9.9` tag is pointing to an [image](https://hub.docker.com/layers/python/library/python/3.9.9/images/sha256-a92164c66896f0517da9d713848a82cc4f0bed1c6586a58d9e395ca26ea7957c?context=explore) that only has support for Windows architectures. I'm unable to pull / use this tag on other architectures at the moment.

Is there any ETA on when the tag will start working with other architectures, besides Windows? Thank you so much!

**Comment by mishok13** [comment]
Additionally, [`python:3.10.1`](https://hub.docker.com/layers/python/library/python/3.10.1/images/sha256-c000b009a6e64351e6b789fe637e87b8f72b9d0918e11f06f55e0185af8f321d?context=explore) has suffered the same fate.

**Comment by yosifkit** [comment]
Some architecture builds take a little longer than others (since they build from source). The tags on Docker Hub are updated with new architectures as they are available. It looks like they are all showing up now.

**Comment by yosifkit** [comment]
Wait, that is strange. The new image version is `3.9.10` and so shouldn't change old manifest lists. :thinking: why was the `3.9.9` manifest modified? cc @tianon Is this a bug or just a hiccup in the manifest put-shared job?

If you still need the older image, it is still in https://hub.docker.com/r/amd64/python, but a reminder that it will never be updated.

**Comment by tianon** [comment]
Sorry folks, this is my bad -- I broke this by getting too clever in https://github.com/docker-library/official-images/pull/11684, but https://github.com/docker-library/official-images/pull/11694 should fix it properly.

**Comment by tianon** [comment]
(Technically, 3.11.0a3 _also_ suffered the same fate, but I don't think anyone's holding their breath for that specific alpha release :joy:)

**Comment by arthurio** [comment]
@tianon Thanks a lot for jumping quickly on this. Do you have an ETA for when the tags will be available again?
