### ISSUE TITLE
Cleaning documentation after installing packages

### ISSUE THREAD

**Issue by klamas1** [docker-library/python#685]
```
# du -sh /usr/share/doc/
67M	/usr/share/doc/
```
This is >20% of the image size.
Why not do `apt-get clean && rm -rf /var/lib/apt/lists/\* /usr/share/doc/\*` together with each run `apt-get install ...` ?

**Comment by tianon** [comment]
This is an artifact of the "batteries included" approach of the default tags; to illustrate better:

```console
$ docker pull python:3.10-bullseye
3.10-bullseye: Pulling from library/python
Digest: sha256:b2b7195df0273d6a1e46764f09b70f4c1e807cceb039fc79ab9dca5e2e248303
Status: Downloaded newer image for python:3.10-bullseye
docker.io/library/python:3.10-bullseye
$ docker pull python:3.10-slim-bullseye
3.10-slim-bullseye: Pulling from library/python
Digest: sha256:ca2a31f21938f24bab02344bf846a90cc2bff5bd0e5a53b24b5dfcb4519ea8a3
Status: Image is up to date for python:3.10-slim-bullseye
docker.io/library/python:3.10-slim-bullseye

$ docker images python:3.10*
REPOSITORY:TAG              IMAGE ID       CREATED      SIZE
python:3.10-slim-bullseye   2052f0475488   6 days ago   123MB
python:3.10-bullseye        cecf555903c6   6 days ago   917MB

$ docker run --rm python:3.10-bullseye du -hs /usr/share/doc/
61M	/usr/share/doc/
$ docker run --rm python:3.10-slim-bullseye du -hs /usr/share/doc/
1.8M	/usr/share/doc/
```

If you want a minimal image, I recommend using the `-slim` variants.

**Comment by klamas1** [comment]
Great, but why is /usr/share/doc/ even there?
Who uses them?)

**Comment by tianon** [comment]
For the non-slim image, the contents there come from the various `-dev` packages that are installed -- the documentation is included as part of the package, so it's included in the image which installs that package.

In the slim image, it's slimmed specifically by avoiding installing as many packages as possible _and_ happens to be based on the Debian image's "slim" variants which include `dpkg` exclusions to remove documentation.  The ~1.8MB you see there are going to be primarily `copyright` files which often include the full text of the relevant open source licenses included with each package, and my understanding is that often those files are required to be included for (legal) distribution of the software.
