### ISSUE TITLE
python/3.10/alpine3.15/ build error - make: /bin/sh: Operation not permitted

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [docker-library/python#689]
I'm trying to build an image using [Dockerfile](https://github.com/docker-library/python/blob/master/3.10/alpine3.15/Dockerfile) and I have an error
```
+ nproc
+ nproc=8
+ make -j 8 'EXTRA_CFLAGS=-DTHREAD_STACK_SIZE=0x100000' 'LDFLAGS=-Wl,--strip-all'
make: /bin/sh: Operation not permitted
make: *** [Makefile:516: profile-run-stamp] Error 127
```

**Comment by wglambert** [comment]
Looks like https://github.com/docker-library/php/issues/1177#issue-934311606
If your Docker version is older than 20.10 you'll encounter that issue from Alpine 

https://alpinelinux.org/posts/Alpine-3.14.0-released.html
>The faccessat2 syscall has been enabled in musl. This can result in issues on docker hosts with older versions of docker (<20.10.0) and libseccomp (<2.4.4), which blocks this syscall.

**Comment by michal-jagiello-tmpl** [comment]
👍 works, thanks @wglambert
