### ISSUE TITLE
Container `arm32v5/python:3.7-buster` shows `armv7l` as architecture

### ISSUE THREAD

**Issue by umbynos** [docker-library/python#698]
Running `docker run --rm --platform linux/arm/v5 arm32v5/python:3.7-buster uname -m`
shows `armv7l`

**Comment by tianon** [comment]
Unfortunately, `uname` gives you information about the _kernel_, not userspace.  If you use `dpkg --print-architecture` instead, you'll see that the userspace there is Debian's `armel` architecture.
