### ISSUE TITLE
[question]Requesting a New Docker file format

### ISSUE THREAD

**Issue by krishna3008** [docker-library/python#703]
Is the docker file format is same for the python 2.7
I have a package written on 2.7 and updating it to 3 is tougher.
I want to use 2.7 in docker file
Is there in chnages to be done?

**Comment by tianon** [comment]
We no longer support Python 2.x (as upstream no longer supports it).  If this is really something you want to pursue, I'd suggest starting with the last commit where we still had 2.7: https://github.com/docker-library/python/tree/f1e613f48eb4fc88748b36787f5ed74c14914636

Alternatively, I'd suggest considering switching from Python to PyPy (https://hub.docker.com/_/pypy) which still actively supports a Python 2.7 variation (and has no plans to stop any time soon that I'm aware of).
