### ISSUE TITLE
Add Windows Server images

### ISSUE THREAD

**Issue by s-weigand** [docker-library/python#704]
Currently there are only `windowsservercore` images available which use [mcr.microsoft.com/windows/servercore](https://hub.docker.com/_/microsoft-windows-servercore) as base image.
This image is missing some ddls which causes some modules in packages like `PySide6` to crash at import time.
E.g.:
```python
    from PySide6.QtMultimedia import QCamera
E   ImportError: DLL load failed while importing QtMultimedia: The specified module could not be found.
```
While this is also true for the linux images and GUI related packages there you can simply install the missing libraries, while windows needs a changed base image.

In our case I just copied the contents of the [windowsservercore-ltsc2022 Dockerfile](https://github.com/docker-library/python/blob/a4b368154b7e3c33c76385f1be7a998fcf3123eb/3.9/windows/windowsservercore-ltsc2022/Dockerfile) (ofc specifying where it came from)

And replaced the `servercore` base image with the full blown `server` image, which fixed the issue.
```diff
- FROM mcr.microsoft.com/windows/servercore:ltsc2022
+ FROM mcr.microsoft.com/windows/server:ltsc2022
```

So it would be nice if we could just pull windows server based images from docker hub instead of building it ourselves.

PS: Thanks for maintaining this project ❤

**Comment by tianon** [comment]
Unfortunately, this isn't something we're going to support.  However, I think you should be able to do something like this instead of copying our full `Dockerfile` if you don't care about the registry changes the Python installer does (which should be ~fine, I think):

```dockerfile
FROM mcr.microsoft.com/windows/server:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# set up PATH
RUN $newPath = ('C:\Python\Scripts;C:\Python;{0}' -f $env:PATH); \
	Write-Host ('Updating PATH: {0}' -f $newPath); \
	[Environment]::SetEnvironmentVariable('PATH', $newPath, [EnvironmentVariableTarget]::Machine)

# https://github.com/docker-library/python/pull/557
ENV PYTHONIOENCODING UTF-8

COPY --from=python:3.10-windowsservercore-ltsc2022 /Python /Python

# you can skip this bit, but it helps make sure it actually worked
RUN Write-Host 'Verifying "python --version" ...'; \
	python --version; \
	Write-Host 'Verifying "pip --version" ...'; \
	pip --version

CMD ["python"]
```
