### ISSUE TITLE
Build from python:3.11-rc-bullseye base fails, same build from python:3.10-bullseye succeeds

### ISSUE THREAD

**Issue by hughsw** [docker-library/python#707]
I'm not certain if I'm posting this issue in the correct forum -- please point me to the correct site for reporting issues if necessary.

The following Dockerfile succeeds when it uses `FROM python:3.10-bullseye`, but it fails when it uses `FROM python:3.11-rc-bullseye`:

```
FROM python:3.11-rc-bullseye
#FROM python:3.10-bullseye

RUN pip3 install uvloop
```

The failure occurs during the install of uvloop in the work that logs as `Building wheels for collected packages: uvloop`.  The python:3.10-bullseye seems to already have the binaries because it does not even do the wheel building.

The failure is reported as follows:
```
...
#6 23.50       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -I/tmp/pip-install-2r_zoi9q/uvloop_d4f76d62ae2247a49a8e4a2e0fcc00d9/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-3.11/uvloop/loop.o -O2
#6 23.50       uvloop/loop.c:214:12: fatal error: longintrepr.h: No such file or directory
#6 23.50         214 |   #include "longintrepr.h"
#6 23.50             |            ^~~~~~~~~~~~~~~
#6 23.50       compilation terminated.
#6 23.50       error: command '/usr/bin/gcc' failed with exit code 1
```

Thanks.

**Comment by tianon** [comment]
... I'm confused. :grimacing:  Why are you installing `python3` in an image that already contains a different build of Python? :sweat_smile:

Regarding `uvloop` specifically though, it appears the 3.11 incompatibility is a known issue: https://github.com/MagicStack/uvloop/issues/450 :see_no_evil:

**Comment by hughsw** [comment]
Thanks for the pointer to the repo where the issue is discussed.

Regarding the Dockerfile: I had pared this down from dev work that has RUN steps that work for a variety of base images, including ones that needed the python3 install.  It is confusing now that you point it out!  I've edited the code above to be minimal.
