### ISSUE TITLE
Request: Add a python 3.6.9 image 

### ISSUE THREAD

**Issue by thepaulchee** [docker-library/python#709]
Hi,

We are working with medical images which requires the use of iSyntax from Philips. Unfortunately, they only support python 3.6.9. Is it possible to upload a slim image of that?

Thanks
Paul

**Comment by wglambert** [comment]
It is done 🎆
```console
$ docker run --rm python:3.6.9-slim python -V
Unable to find image 'python:3.6.9-slim' locally
3.6.9-slim: Pulling from library/python
000eee12ec04: Pull complete
ddc2d83f8229: Pull complete
3571e8aba018: Pull complete
4a7b90e0e057: Pull complete
99974a434243: Pull complete
Digest: sha256:0f0e98b6938bab4030306c101e7f5f91e833f2f0515fcabbc9ca7f2fd5a6ece1
Status: Downloaded newer image for python:3.6.9-slim
Python 3.6.9
```

**Comment by yosifkit** [comment]
Note that the `3.6.9` images are no longer supported and last pushed 2 years ago (https://hub.docker.com/_/python?tab=tags&page=1&name=3.6.9-slim), but they will remain available to pull.
