### ISSUE TITLE
Missing documentation on firewall configuration (Connection refused with any port on python:3)

### ISSUE THREAD

**Issue by martilidad** [docker-library/python#710]
Finding a title is hard, so I just assumed it is my fault and there is only documentation missing. 
I can't get Networking to work with the python:3 image. 
I can't establish a connection with the image at all. **Even within the same container!**
Here is the Problem reduced as far as I could:
```
docker run -it python:3 /bin/bash
root@766bf6d1a64e:/# apt-get update && apt-get install netcat -y
root@766bf6d1a64e:/# netcat -l 1234
```
2nd shell:

```
docker exec -it <container-name> /bin/bash
root@766bf6d1a64e:/# netcat -v localhost 1234
localhost [127.0.0.1] 1234 (?) : Connection refused
```
On any other docker image there is no problem doing this. Linux or Docker for Windows.

**Comment by wglambert** [comment]
Since your container isn't forwarding any ports to it (such as `-p 1234:1234`) then no port on the host will be directed to it, however you can still connect to the container through its IP

Example
```console
$ docker run -d --rm --name python python sleep infinity
a227cde6b35a01c2e3897860653b3bd09094714583badee09bb3d61a63fc7833
$ docker exec -it python bash
root@a227cde6b35a:/# apt update && apt install -y netcat
. . .
root@a227cde6b35a:/# netcat -l 1234 &
[1] 304
root@a227cde6b35a:/# exit

$ docker inspect python | grep -i ipaddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",
$ netcat -v 172.17.0.2 1234
172.17.0.2: inverse host lookup failed: Unknown host
(UNKNOWN) [172.17.0.2] 1234 (?) open
```

The solution you're looking for is either running the container with `-p 1234:1234` to forward that specific port, or use `--network host` to forward every port that's listening in the container

As for adding it to the documentation see my comment here https://github.com/docker-library/mongo/issues/530#issuecomment-1067030230

**Comment by martilidad** [comment]
Please read my question again. I use only networking **within** the container.
I tested it again. it's broken with python:3.
```
"RepoTags": [
    "python:3"
],
"RepoDigests": [
    "python@sha256:ad7fb5bb4770e08bf10a895ef64a300b288696a1557a6d02c8b6fba98984b86a"
],
```
But works with python:latest.
```
"RepoTags": [
    "python:latest"
],
"RepoDigests": [
    "python@sha256:6441e2f0bd2e566de0df6445cb8e7e395ea1a376dd702de908d70401d3700961"
],
```

**Comment by martilidad** [comment]
Shouldn't they be the same image anyway?

**Comment by wglambert** [comment]
Oh the `netcat` command isn't listening on 1234 as expected. You need `netcat -l -p 1234`
```console
$ docker run -it python@sha256:ad7fb5bb4770e08bf10a895ef64a300b288696a1557a6d02c8b6fba98984b86a bash
root@16a3e7aece7a:/# apt update && apt install -y netcat net-tools
. . .
root@16a3e7aece7a:/# netcat -l 1234 &
[1] 305
root@16a3e7aece7a:/# netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:39243           0.0.0.0:*               LISTEN
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
```
The port given isn't interpreted by the `-l` option so it picked a random port. Doing it again with `-p 1234` will show that specific port as listening
```console
root@16a3e7aece7a:/# netcat -l -p 1234 &
[2] 307
root@16a3e7aece7a:/# netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:39243           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
root@16a3e7aece7a:/# netcat -v localhost 1234
localhost [127.0.0.1] 1234 (?) open
```

**Comment by wglambert** [comment]
The `latest` image uses netcat version `OpenBSD netcat (Debian patchlevel 1.217-3)` which will listen on port 1234 with the command `netcat -l 1234` 
Whereas the older image that uses netcat version `[v1.10-41.1]` requires `-p 1234` to listen on that specific port

**Comment by martilidad** [comment]
Oh wow, thank you for solving my issue. :)
I never would have expected this.
