### ISSUE TITLE
Docker Alpine, Unable to install pywin32 from pip requirements.txt

### ISSUE THREAD

**Issue by prithvi2k2** [docker-library/python#717]
Actually the main requirement is web3.py, which is dependent on pywin32

Seems like #468 has re-surfaced or maybe I did something wrong?

For more details, I also opened a detailed issue on web3 repo [here](https://github.com/ethereum/web3.py/issues/2423)

**Comment by yosifkit** [comment]
Closing given the discussion on the linked web3 issue.

tl;dr:
> As the "win32" indicates, pywin32 is a Windows-only package which wraps Windows system calls. It does not, can not, and will never work on a Linux system 

So, this is not possible in the Linux-based python images and installing in a windows-based image works (https://github.com/docker-library/python/issues/468#issuecomment-733197632).
