### ISSUE TITLE
Installing packages that require header files

### ISSUE THREAD

**Issue by ChiliConSql** [docker-library/python#72]
How do I go about installing pylibmc. I am getting the following error with "pip install pylibmc":
pylibmcmodule.h:42:36: fatal error: libmemcached/memcached.h: No such file or directory
#include <libmemcached/memcached.h>

apt-get and apt-cache don't appear to be available.

**Comment by vinitkumar** [comment]
@ChiliConSql Did you manage to get it fixed?
