### ISSUE TITLE
3.10-slim-bullseye image pulling error

### ISSUE THREAD

**Issue by kakaru1331** [docker-library/python#720]
Hello.

I have trouble with pulling python image on certain tag.
This error occurs target on the 3.10-slim-bullseye tag.
I will attach the detailed error log below.

Thank you :)
```console
=> ERROR [internal] load metadata for docker.io/library/flask_service:python-3.10-slim-bullseye                                                                                                                         2.2s 
------
 > [internal] load metadata for docker.io/library/flask_service:python-3.10-slim-bullseye:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
ERROR: Service 'tracing' failed to build : Build failed
```

**Comment by wglambert** [comment]
The image you're trying to pull `flask_service:python-3.10-slim-bullseye` doesn't exist
But the image `python:3.10-slim-bullseye` pulls just fine
```console
$ docker run -it --rm python:3.10-slim-bullseye bash
Unable to find image 'python:3.10-slim-bullseye' locally
3.10-slim-bullseye: Pulling from library/python
1fe172e4850f: Pull complete
caf521ccaac6: Pull complete
b3278b635dc9: Pull complete
4298f8ff43f9: Pull complete
56eb47d0c00a: Pull complete
Digest: sha256:ad719a882ac0594bdc92abccff22e5b6713bbf9893320264fd9e8affd8a6f470
Status: Downloaded newer image for python:3.10-slim-bullseye
```

**Comment by kakaru1331** [comment]
Sry. I attached the wrong log that has nothing to do with the main text.
I consider It has been occured for my corporate proxy.
Anyway thank you!

**Comment by RamyQabel** [comment]
(new_phage_commander_env) phagegenome@DESKTOP-QQBHUA8:~/PhageCommander/phagecommander$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; preset: enabled)
     Active: active (running) since Tue 2025-02-11 12:23:58 CST; 1h 31min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 534 (dockerd)
      Tasks: 10
     Memory: 85.2M ()
     CGroup: /system.slice/docker.service
             └─534 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.421097364+08:00" level=info msg="Loading containers: start."
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.858855694+08:00" level=info msg="Loading containers: done."
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.915539985+08:00" level=warning msg="WARNING: No blkio throttle.read_bps_device support"
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.915614648+08:00" level=warning msg="WARNING: No blkio throttle.write_bps_device support"
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.915631316+08:00" level=warning msg="WARNING: No blkio throttle.read_iops_device support"
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.915638812+08:00" level=warning msg="WARNING: No blkio throttle.write_iops_device support"
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.915672642+08:00" level=info msg="Docker daemon" commit="26.1.3-0ubuntu1~24.04.1" containerd-sna>
Feb 11 12:23:57 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:57.916158392+08:00" level=info msg="Daemon has completed initialization"
Feb 11 12:23:58 DESKTOP-QQBHUA8 systemd[1]: Started docker.service - Docker Application Container Engine.
Feb 11 12:23:58 DESKTOP-QQBHUA8 dockerd[534]: time="2025-02-11T12:23:58.394779033+08:00" level=info msg="API listen on /run/docker.sock"
[+] Building 30.2s (3/3) FINISHED                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 702B                                                                                                                               0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.12-slim                                                                                         30.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                      0.0s
------
 > [internal] load metadata for docker.io/library/python:3.12-slim:
------
Dockerfile:2
--------------------
   1 |     # Use an official Python runtime as a parent image
   2 | >>> FROM python:3.12-slim
   3 |
   4 |     # Install necessary libraries
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: python:3.12-slim: failed to resolve source metadata for docker.io/library/python:3.12-slim: failed to authorize: DeadlineExceeded: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp 205.251.196.144:443: i/o timeout
[+] Building 30.2s (3/3) FINISHED                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 703B                                                                                                                               0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.10-slim                                                                                         30.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                      0.0s
------
 > [internal] load metadata for docker.io/library/python:3.10-slim:
------
Dockerfile:2
--------------------
   1 |     # Use an official Python runtime as a parent image
   2 | >>> FROM python:3.10-slim
   3 |
   4 |     # Install necessary libraries
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: python:3.10-slim: failed to resolve source metadata for docker.io/library/python:3.10-slim: failed to authorize: DeadlineExceeded: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp 69.63.184.142:443: i/o timeout
[+] Building 30.2s (3/3) FINISHED                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 704B                                                                                                                               0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.11-slim                                                                                         30.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                      0.0s
------
 > [internal] load metadata for docker.io/library/python:3.11-slim:
------
Dockerfile:2
--------------------
   1 |     # Use an official Python runtime as a parent image
   2 | >>> FROM python:3.11-slim
   3 |
   4 |     # Install necessary libraries
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: python:3.11-slim: failed to resolve source metadata for docker.io/library/python:3.11-slim: failed to authorize: DeadlineExceeded: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp 69.63.184.142:443: i/o timeout
(new_phage_commander_env) phagegenome@DESKTOP-QQBHUA8:~/PhageCommander/phagecommander$ docker run --rm -it phagecommander
Unable to find image 'phagecommander:latest' locally
docker: Error response from daemon: pull access denied for phagecommander, repository does not exist or may require 'docker login'.
See 'docker run --help'.
(new_phage_commander_env) phagegenome@DESKTOP-QQBHUA8:~/PhageCommander/phagecommander$

**Comment by LaurentGoderre** [comment]
@RamyQabel can you try again? We were investigating an issue.
