### ISSUE TITLE
python3.7 posix broken

### ISSUE THREAD

**Issue by rwong2888** [docker-library/python#722]
Getting this error
```
File "/usr/local/lib/python3.7/site-packages/Crypto/Random/OSRNG/posix.py", line 66
except IOError, e:
                  ^
SyntaxError: invalid syntax
```

Comparing posix.py between working and broken

```
 ❯ diff posix.py /Users/rwong/tmp/2022-04-22/bad/site-packages/Crypto/Random/OSRNG/posix.py                                 [11:24:09]
32c32
< from .rng_base import BaseRNG
---
> from rng_base import BaseRNG
66c66
<             except IOError as e:
---
>             except IOError, e:
```

python:3.7 updated 7 hours ago. Looks to have broken posix.
https://hub.docker.com/layers/python/library/python/3.7/images/sha256-0827a545174692[%E2%80%A6]de6f275c61cffffdec172af2220bb05cb3e0eb8e6efce?context=explore

**Comment by rwong2888** [comment]
This was caused by pipenv 2022.4.21; Reverted to pipenv 2022.4.8 to resolve
https://pypi.org/project/pipenv/#history

**Comment by rwong2888** [comment]
Opened https://github.com/pypa/pipenv/issues/5074

**Comment by marek22k** [comment]
I have the error too and I don't use pipenv, is there any other workaround?
