### ISSUE TITLE
Hosts in containerspec get reordered

### ISSUE THREAD

**Issue by Pabosik** [docker-library/python#729]
Hey everyone,

the issue is simple - when you specify a hosts dictionary in ContainerSpec, the order of keys changes before it gets written inside /etc/hosts of the conatiner in question.

Example: 
`hosts = {"c": "10.0.0.40", "b": "10.0.0.40", "a": "10.0.0.40" }`

would get added into /etc/hosts as:
```
10.0.0.40 a
10.0.0.40 b
10.0.0.40 c
```

Is this not a bug? The order of aliases in etc/hosts matters and the fact that it gets arbitrarily reordered is just... not how it should work in my opinion.

Also, it should be added like this:
`10.0.0.40 c b a`
but it seems that docker simply does not allow that at the moment, so... that's sad, but we can still do something about the ordering, cant we? :)

If there is a way to do it and I just missed it, then I apologize. I have tried with tuples, lists, long strings separated by whitespaces or commas, nothing works... either the order is wrong, or just the first entry gets added.

Thanks in advance

**Comment by tianon** [comment]
I'm sorry, I'm a little bit confused -- I'm not sure what this has to do with the https://hub.docker.com/_/python image that this is the repository for? :sweat_smile:

The image definitely does not control how the container orchestration system creates `/etc/hosts` within the container. :see_no_evil:

**Comment by Pabosik** [comment]
I am so sorry... Wrong repo 🙈. Been a bit too deep down that rabbit hole, didn't notice. My mistake! :)
