### ISSUE TITLE
Request update of alpine to 3.16.1

### ISSUE THREAD

**Issue by rajivbandi** [docker-library/python#740]
Alpine image version 3.16.1 has been released and it addresses 2 security vulnerabilities.
Hence, I request that the relevant python alpine 3.16 image also be upgraded.

**Comment by tianon** [comment]
The images are `FROM alpine:3.16` which follows the `3.16.x` line. In official images, we rebuild all dependent images when an image is updated, so it has already been rebuilt. :+1:
