### ISSUE TITLE
pip freeze raises an error in a build process

### ISSUE THREAD

**Issue by marceloslacerda** [docker-library/python#741]
Pip freeze raises an error in `python:3.10-bullseye`

```
Step 4/4 : RUN pip freeze
 ---> Running in 73584b0705d3
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
```

I've tried experimenting a little and found that the following Dockerfile is able to produce the error consistently:

```
FROM python:3.10-bullseye
RUN echo > ./requirements.txt
# Comment the following line and the build finishes normally
RUN pip install --no-cache -r requirements.txt
RUN pip freeze

```

I'm building the image with `docker build --rm -t test-freeze .`

I'm running docker `Docker version 20.10.5, build 55c4c88`

**Comment by marceloslacerda** [comment]
Changing `python:3.10-bullseye` to `FROM python:3.10.5-bullseye` produces the same result.

I've just tested in a different machine and the `pip freeze` works fine. Very puzzling.

**Comment by wglambert** [comment]
Looks like the same issue as https://github.com/docker-library/python/issues/713

Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by marceloslacerda** [comment]
All the comments are listed. I upgraded docker and the host packages, rebooted, removed every relevant cache (docker containers and images) and the parent image (python:3.10.5-bullseye) and the build worked then.

I'll reopen this issue if the problem repeats.
