### ISSUE TITLE
Question: Can't find linux/amd64 image for 3.10.6-slim?

### ISSUE THREAD

**Issue by jonyscathe** [docker-library/python#742]
Hi,

Not sure if I am doing something wrong here...
When I run `docker pull python:3.10.5-slim` then it works fine.
When I run `docker pull python:3.10.6-slim` then I get:
`no matching manifest for linux/amd64 in the manifest list entries`

**Comment by williamjacksn** [comment]
Same problem, but with 3.10.6-alpine3.16.

https://hub.docker.com/_/python?tab=tags&page=1&name=3.10.6

Seems there are no linux/amd64 manifests for any 3.10.6 images.

**Comment by benz0li** [comment]
Many `OS/ARCH` are missing for the `3.10.6` images.

Compare https://hub.docker.com/_/python?tab=tags&page=1&name=3.10.5 to https://hub.docker.com/_/python?tab=tags&page=1&name=3.10.6.

**Comment by dschunack** [comment]
we miss also the AMD64 ARCH.

**Comment by jonyscathe** [comment]
Manifests seem to be there now
