### ISSUE TITLE
 [REQUEST] updating sqlite3

### ISSUE THREAD

**Issue by MartinHotmann** [docker-library/python#747]
Refering to: https://discuss.python.org/t/request-updating-sqlite3-to-latest-version/18051

I would like to ask if the person, who is responsible for the official python images might want to update sqlite3 to it's very latest version?

image: [python:3-alpine](https://hub.docker.com/layers/python/library/python/3-alpine/images/sha256-c37301b8439432638163231fd441845fce3511dde0ec6f2e7e131b5b91e6ffea?context=explore)
sqlite: [3.38.5](https://www.sqlite.org/changes.html)

latest availavle version: [3.39.2](https://www.sqlite.org/changes.html) (as of time writing)

Thanks in advance!!!

**Comment by MartinHotmann** [comment]
I now have worked around this problem. I have two image builder versions:

1. which creates all the dependencies from source, then pushes them to persistent storage.
2. which is the real image and on build time overwrites the current ones with the one from persistent storage.

the required files (for 3.39.2) are: [libsqlite3-3.92.2.zip](https://github.com/docker-library/python/files/9304084/libsqlite3-3.92.2.zip)

> ```
> /usr/local/lib/libsqlite3.so.0.8.6
> /usr/local/lib/libsqlite3.so
> /usr/local/lib/libsqlite3.so.0
> /usr/local/lib/libsqlite3.a
> /usr/lib/libsqlite3.so.0.8.6
> /usr/lib/libsqlite3.so.0
> ```


With this, I just have to build it once and not on every image build.
Anyway having all dependencies already updated and maintained centrally in the official image would be nice!

Hope that helps. Open for feedback and a discussion about this.

**Comment by yosifkit** [comment]
For these images, we focus on building upstream Python releases; other than the Python source, we do not want to add dependencies that are outside of the OS-provided packages (Debian and Alpine). So, for the images as they are now, we are beholden to the versions of [`libsqlite3-0`](https://packages.debian.org/bullseye/libsqlite3-0) and [`sqlite-libs`](https://pkgs.alpinelinux.org/packages?name=sqlite-libs&branch=v3.16) as are packaged and available in the respective OS distribution release. We do not build language or service images based on unstable or development releases of OS's.

For Alpine, it looks like they have [`3.39.2` in their "edge"](https://pkgs.alpinelinux.org/packages?name=sqlite-libs&branch=edge) repos, but until it is in an OS release, we are unable to use it. It will likely be in Alpine 3.17 which should happen around November or December judging by their previous release cadence (https://alpinelinux.org/releases/).

Debian does have the update [(`3.39.2`) in their `testing` repository](https://packages.debian.org/bookworm/libsqlite3-0) (aka `bookworm`), but there is not yet a date set for the release (https://wiki.debian.org/DebianReleases).
