### ISSUE TITLE
[REQUEST] slim-alpine

### ISSUE THREAD

**Issue by MartinHotmann** [docker-library/python#755]
I saw that there are already multiple images. But since `slim` is also available for debian etc, I would love to test it on alpine, since I use alpine.

I ATM use:

`FROM python:3-alpine`
and would like to test:
`FROM python:3-slim-alpine`
if available.

So it would be cool to see slim releases being created with the other distros as well:

- alpine
- debian (already available)
- windows

BTW: python 3.10.7 would be nice as well, since somehow it did not go through.

**Comment by yosifkit** [comment]
The Alpine-based images are already built in the slim way; they can't really be any smaller and still run `python3`.

---

> BTW: python 3.10.7 would be nice as well, since somehow it did not go through.

https://github.com/docker-library/python#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet  the PR is already open: https://github.com/docker-library/official-images/pull/13108.

**Comment by MartinHotmann** [comment]
True, sorry - my fault.
Just checked:

```
$ python3.9 --version
sh: python3.9: not found
```

Thanks!
