### ISSUE TITLE
release 3.8.14 ?

### ISSUE THREAD

**Issue by bukzor-sentryio** [docker-library/python#756]
I see you've committed the change. Did you forget to release?

https://github.com/docker-library/python/commit/5b3bf4f263944abbe8905aa73c7abbbfb0a4db9f

**Comment by yosifkit** [comment]
https://github.com/docker-library/python#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet  the PR is already open: https://github.com/docker-library/official-images/pull/13108.
