### ISSUE TITLE
ARM v7 alpine missing

### ISSUE THREAD

**Issue by jetexe** [docker-library/python#763]
`3.10.7-alpine` supported architectures:
- `linux/386`
- `linux/amd64`
- `linux/arm/v6`
- `linux/arm/v7`
- `linux/arm64/v8`
- `linux/ppc64le`
- `linux/s390x`

`3.10.8-alpine` supported architectures:
- `linux/386`
- `linux/amd64`
- `linux/arm/v6`
- `linux/arm64/v8`
- `linux/ppc64le`
- `linux/s390x`

`linux/arm/v7` is missing in current release

**Comment by yosifkit** [comment]
The `arm32v7` python images are still in queue for building. See the badges at the bottom of the readme: https://github.com/docker-library/python/tree/ebf80a991af84e5301655dafbbf3a63d9691847b#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by aliculPix4D** [comment]
@yosifkit the linux/mips64le architecture is still in queue for building, but apparently builds are just failing constantly. Any idea when this will be fixed? Thanks

Extra info:
Issue opened by my college: https://github.com/python/cpython/issues/98397
This causes the Dependabot to propose wrong updates to `3.11.0rc2`.
