### ISSUE TITLE
mips64le builds for 3.10.8 are failing

### ISSUE THREAD

**Issue by yosifkit** [docker-library/python#765]
The linux/mips64le architecture is still in queue for building, but apparently builds are just failing constantly. Any idea when this will be fixed? Thanks

Extra info:
Issue opened by my college: https://github.com/python/cpython/issues/98397
This causes the Dependabot to propose wrong updates to `3.11.0rc2`.

_Originally posted by @aliculPix4D in https://github.com/docker-library/python/issues/763#issuecomment-1283566668_

**Comment by tianon** [comment]
I don't think this is going to be fixed -- we've disabled `mips64le` support for now, and we're happy to reconsider adding it if we see evidence that it will be building successfully again.
