### ISSUE TITLE
No longer able to build images for arm v6.  I get errors that the base image doesn't exist however I can pull it fine.

### ISSUE THREAD

**Issue by danfinn** [docker-library/python#771]
This was working the last time I built this image a month or two ago, nothing has changed on my end that I'm aware of.  I'm building a pretty simple python app on my mac.

The Dockerfile uses:
```
FROM python:3.10-slim-buster
```

I can pull this image successfully:
```
docker pull --platform 'linux/arm/v6' python:3.10-slim-buster
3.10-slim-buster: Pulling from library/python
e4ea50bd37db: Already exists
a076b1badbba: Already exists
38bd03a77a53: Pull complete
2c7200a323b5: Pull complete
ada38b46765d: Pull complete
Digest: sha256:c2b2fbfcb541f6012e98911afc371be734d2f9c1f875f6e5a5aa0e461c35411d
Status: Downloaded newer image for python:3.10-slim-buster
```

however when I try to build with it I get the following error:
```
docker buildx build --platform 'linux/arm/v6' -t dfinn/multisma:5 . --push --output=type=registry
[+] Building 1.4s (4/4) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 392B                                                                                                                                                                  0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.10-slim-buster                                                                                                                      1.3s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                         0.0s
------
 > [internal] load metadata for docker.io/library/python:3.10-slim-buster:
------
Dockerfile:2
--------------------
   1 |     #FROM arm32v6/python:3.10-slim-buster
   2 | >>> FROM python:3.10-slim-buster
   3 |
   4 |     WORKDIR /app
--------------------
error: failed to solve: python:3.10-slim-buster: no match for platform in manifest sha256:c2b2fbfcb541f6012e98911afc371be734d2f9c1f875f6e5a5aa0e461c35411d: not found
```

**Comment by wglambert** [comment]
`arm32v6/python` only has Alpine variants https://hub.docker.com/r/arm32v6/python/
`arm32v5/python` only has bullseye and slim-bullseye https://hub.docker.com/r/arm32v5/python/
`arm32v7/python` and `arm64v8/python` have every variant https://hub.docker.com/r/arm64v8/python/ and https://hub.docker.com/r/arm32v7/python/

**Comment by danfinn** [comment]
@wglambert I sort of suspected that but what had me confused was the ability to docker pull an arm v6 version of 3.10-slim-buster?  why does that work?

**Comment by wglambert** [comment]
python:3.10-slim-buster never had arm32v6 builds https://githistory.xyz/docker-library/repo-info/blob/master/repos/python/remote/3.10-slim-buster.md

https://github.com/docker-library/repo-info/blob/b691eeabc75823b723207ae032e3004520f6f6e9/repos/python/remote/3.10-buster.md

**Comment by danfinn** [comment]
Hmm...not sure how docker is able to pull it then.  I know there was a 3.8 slim buster build, that is what I'm currently using but I ran into these issues this morning when I needed to make some changes to the container.

**Comment by tianon** [comment]
When you specify something like `linux/arm/v7`, it implies a platform _vector_ such that it will prefer v7, fall back to v6, and fall back to v5 if necessary (since the hardware is typically compatible and the variants are generally additive).

**Comment by tianon** [comment]
What I think you're running into is that Debian Buster is now LTS (https://wiki.debian.org/LTS), and as such no longer supports `armel` (which is `linux/arm/v5`, the fallback from `v6`).

**Comment by danfinn** [comment]
I think you might be right although this still leaves me a little confused.  I just changed my Dockerfile to use

```
FROM python:3.10-slim-bullseye
```

and I'm now able to run this build command for multiple archs:

```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v6 -t dfinn/multisma:5 . --push --output=type=registry
```

and it appears to be working but what doesn't add up here is that it seems like this should not be working for arm32v6 since that only has Alpine based images.

**Comment by tianon** [comment]
Ah, that _is_ a bug, and it looks like it's fixed in the next version of Docker: https://github.com/moby/moby/pull/43675 :+1:
