### ISSUE TITLE
Github CI Badge Error on README

### ISSUE THREAD

**Issue by heytorvas** [docker-library/python#779]
Because a breaking change by shields.io, the build status badge related a Github CI is showing an error on [README](https://github.com/docker-library/python/blob/master/README.md?plain=1#L17).
Previously, was used by pipeline name and, after the change, requires a filename.

To resolve this issue, needs update image url to :
`https://img.shields.io/github/actions/workflow/status/docker-library/python/ci.yml?branch=master&label=GitHub%20CI`

ps: i tried create a Pull Request to fix this little issue but i don't have permission :/

**Comment by ad-m-ss** [comment]
> ps: i tried create a Pull Request to fix this little issue but i don't have permission :/

Please create a fork first or share the full error message.

**Comment by heytorvas** [comment]
Only needs update README file with the new image url.

At this moment, the file is this way:
![image](https://user-images.githubusercontent.com/45018537/208768068-53ac3e5e-5294-4c5d-bd22-8d440eef70b0.png)

With fix update related above, will be:
![image](https://img.shields.io/github/actions/workflow/status/docker-library/python/ci.yml?branch=master&label=GitHub%20CI)
