### ISSUE TITLE
Python 3.9 Alpine Images fail Dockle Linting Tests

### ISSUE THREAD

**Issue by tanzim-bgl** [docker-library/python#793]
Hi,

I am trying to create an image using Python 3.9 based on Alpine. 

Currently, given a simple Dockerfile, when i run Dockle against this image, the vulnerability DKL-DI-0004 is raised, saying that apk add --no-cache should be used. 

For other users, is it possible to change the specific dockerfile build process to make sure all calls to apk add have --no-cache within it. The last image that conforms to this is from 2 years prior `python:3.9.0-alpine3.12`

Steps to reproduce 

```
FROM python:3.9-alpine3.17
RUN apk add --no-cache --update curl && apk add --no-cache --update bash
```

Running dockle after building the image....

`docker build --no-cache -t test:1.0 . && dockle test:1.0`

Result from dockle:
`FATAL   - DKL-DI-0004: Use "apk add" with --no-cache...`

I can see that within the layers of the latest python:3.9-alpine3.17 image, this line...

https://github.com/docker-library/python/blob/master/3.9/alpine3.17/Dockerfile#L110

`find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec scanelf --needed --nobanner --format '%n#p' '{}' ';' \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
		| xargs -rt apk add --no-network --virtual .python-rundeps \
	; \
	apk del --no-network .build-deps; \
	\
	python3 --version`

uses apk add without --no-cache which i suspect trips up dockle. 

This vulnerability is quite severe according to Dockle and was hoping this could be fixed as I do not want to bypass Dockle liniting. 

Any suggestions? I think it is better to raise this upstream rather than building it from source.

**Comment by tianon** [comment]
I don't know what Dockle is, but it's definitely wrong here -- `--no-network` should be a _stronger_ exclusion than `--no-cache` (we use `--no-network` because we know all the things we're asking it to install are already installed, where using `--no-cache` would uselessly re-download the package list files).

**Comment by tanzim-bgl** [comment]
I understand, this seems like it has no effect to use --no-cache if the network is not being used. 

Dockle is a docker linter where it looks at the layers that make up an image. 
It looks for the commands/flags --no-cache https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#dkl-di-0004

From what you have said, it seems like the upstream maintainer for dockle may need to revisit their linter and their rules. 

Thanks for your comments.
