### ISSUE TITLE
Update PYTHON_SETUPTOOLS_VERSION  in python 3.8-slim-buster

### ISSUE THREAD

**Issue by manikantanallagatla** [docker-library/python#796]
Given this risk, https://github.com/advisories/GHSA-r9hx-vwmv-q579, any plans to update PYTHON_SETUPTOOLS_VERSION to 65.5.1 in python 3.8-slim-buster?

**Comment by yosifkit** [comment]
Duplicate https://github.com/docker-library/python/issues/781

https://github.com/docker-library/python/issues/781#issuecomment-1372524712
