### ISSUE TITLE
Don't you plan to support mips64le architecture in the version after 3.11？

### ISSUE THREAD

**Issue by starZane** [docker-library/python#799]

**Comment by tianon** [comment]
See https://github.com/docker-library/python/issues/765 :disappointed:

**Comment by yosifkit** [comment]
`3.11` doesn't currently build on `mips64le` and also is not a supported architecture in the python project. 

- https://github.com/docker-library/python/pull/734
- https://github.com/python/cpython/issues/93619
- https://peps.python.org/pep-0011/
