### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by tkbstudios** [docker-library/python#802]
Console log: [pastebin 1](https://pastebin.com/w8Ne1UUv)
Dockerfile: [pastebin 2](https://pastebin.com/7CdrDGUS)

Docker Desktop: Docker Desktop 4.16.3 (96739)
Docker Engine: v20.10.22

## Build command used:
`docker build --platform linux/arm64 -t tkbstudios/myapp:0.0.2 ./`

## Issue
Stuck on the following for over 15 minutes:
`RUN set -eux;   apk add --no-cache --virtual .build-deps   gnupg   tar   xz     bluez-dev   bzip2-dev   dpkg-dev dpkg   expat-dev   findutils   g  926.4s`

## Expected behavior:
Build the image for linux/arm64.

**Comment by tianon** [comment]
I'm not sure why you're trying to build a modified version of _our_ `Dockerfile` instead of just building `FROM python:xxx` ?

**Comment by tkbstudios** [comment]
I am trying to move a script inside the docker container. The script is a server with over 5600 lines I've made and it needs a docker container to limit resources due to over 3K clients connecting to it at peak times.

**Comment by tianon** [comment]
Sure, but why are you building our entire `Dockerfile` for that instead of just something like this?

```dockerfile
FROM python:x.y
COPY my-huge-script /.../
```

**Comment by tkbstudios** [comment]
Well the issue is:
I'm trying to build the python image with my script for arm64/arm64v8 (raspberry pi 4 model B) and it doesn't work, your Dockerfile worked without the script so I though it would also work when I put the script in it.
Do you maybe have a Dockerfile somewhere for that or which python base image should I use for arm64/arm64v8?
