### ISSUE TITLE
python3.8.10: Cannot use the tab key to complete the command on the version python:3.8.10

### ISSUE THREAD

**Issue by tongtaott** [docker-library/python#806]
I want to use the tab key automatically complete the command on the version python:3.8.10,but it failed,similarly,I failed to view historical commands by using up and down keys on the keyboard. But when I did the same thing on the version 3.8.10-alpine, I succeeded.
What shall I do?

**Comment by tongtaott** [comment]
感谢您的来信，您的邮件我已收到！我会尽快处理！

**Comment by tianon** [comment]
Sorry, wrong button in the wrong open window :facepalm: :bow:

**Comment by tianon** [comment]
I can't reproduce :bow:

https://asciinema.org/a/JAD5BPlbEG6H4e6AE4ov7K7iT
