### ISSUE TITLE
python:slim does not contain _dbm

### ISSUE THREAD

**Issue by iwamot** [docker-library/python#814]
### python:slim

```
$ docker run python:slim python -c 'import dbm.ndbm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/dbm/ndbm.py", line 3, in <module>
    from _dbm import *
ModuleNotFoundError: No module named '_dbm'

$ docker run python:slim find /usr/local/lib/python3.11/lib-dynload/ -name '*dbm*' -print
/usr/local/lib/python3.11/lib-dynload/_gdbm.cpython-311-x86_64-linux-gnu.so
```

### python

```
$ docker run python python -c 'import dbm.ndbm'

$ docker run python find /usr/local/lib/python3.11/lib-dynload/ -name '*dbm*' -print
/usr/local/lib/python3.11/lib-dynload/_dbm.cpython-311-x86_64-linux-gnu.so
/usr/local/lib/python3.11/lib-dynload/_gdbm.cpython-311-x86_64-linux-gnu.so
```

Is it possible to include it? Or could you please advise me how to use it?

**Comment by tianon** [comment]
Hmm, interesting -- I'm not sure what we're missing -- I've tried looking in Debian's `python3.X` package sources for clues, and I'm coming up empty. :confused:

Given that the non-`slim` is working, it's likely that we need to install some additional package from https://github.com/docker-library/buildpack-deps/blob/65d69325ad741cea6dee20781c1faaab2e003d87/debian/bullseye/Dockerfile (or one of the dependencies of those), but it's difficult to narrow down which one. :sweat_smile:

**Comment by iwamot** [comment]
Thank you for your response.
