### ISSUE TITLE
`python:3.9` - Failed run `apt update` from the last version of the image

### ISSUE THREAD

**Issue by aviadpriel** [docker-library/python#837]
as titled

today morning we found that our builds failed  
we are using `python:3.9`

when we run `apt update` the build failed

it looks that it fails because of the upgrade to `bookworm`

we get this errors
```
#5 [build 2/4] RUN apt-get update &&     apt-get install -y --no-install-recommends     poppler-utils
#5 sha256:fdb97fe2ebc3fcf79626c6628756f871cc0d6b0fc02ba21a2949fe33d31a2373
#5 0.240 Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
#5 0.247 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
#5 0.248 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#5 0.277 Err:1 http://deb.debian.org/debian bookworm InRelease
#5 0.277   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY F8D2585B8783D481
#5 0.303 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
#5 0.303   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
#5 0.329 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
#5 0.329   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
#5 0.330 Reading package lists...
#5 0.337 W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY F8D2585B8783D481
#5 0.337 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
#5 0.337 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
#5 0.337 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
#5 0.337 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
#5 0.337 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
#5 0.337 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
#5 0.337 E: Sub-process returned an error cod
```

**Comment by Cookiehook** [comment]
We're seeing the same issues on python:3.10. Worked around by using python:3.10-bullseye for now.

**Comment by aviadpriel** [comment]
yes, same for python:3.9-bullseye

but we have couple of security fixes on Debian 12 that we want to get

**Comment by a1723** [comment]
The main question is: Will it be fixed in python:xx images or now we must always used images with "bullseye" postfix ?

**Comment by yosifkit** [comment]
I am unable to reproduce. I'd suggest updating docker and libseccomp on the host. Newer base OS's use newer system calls and an older libseccomp can block them since they are unknown to it. You can verify that it is libseccomp by running the bookworm image with `--security-opt seccomp=unconfined`.

This is similar to the update to Ubuntu focal: https://github.com/docker-library/mongo/issues/606#issuecomment-1424965831

```console
$ docker run -it python:3.9-bookworm bash
Unable to find image 'python:3.9-bookworm' locally
3.9-bookworm: Pulling from library/python
bba7bb10d5ba: Already exists
ec2b820b8e87: Already exists
284f2345db05: Already exists
fea23129f080: Already exists
7c62c924b8a6: Already exists
b2210932934e: Pull complete
ee9c01829d92: Pull complete
d6285f41f1b6: Pull complete
Digest: sha256:98f018a1afd67f2e17a4abd5bfe09b998734ba7c1ee54780e7ed216f8b8095c3
Status: Downloaded newer image for python:3.9-bookworm
root@0b679f272394:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [24.2 kB]
Fetched 9176 kB in 1s (7771 kB/s)
Reading package lists... Done
root@0b679f272394:/#
```

**Comment by jimbudarz** [comment]
I see the same for python:3.8-slim and others after the update from buster -> bookworm.

**Comment by keever** [comment]
This broke our ci docker build jobs that used `python:3.9-slim` We used docker v24.0.2 to do the build.

**Comment by muasif80** [comment]
It seems like the pointers for the latest image tags are moved to bookworm. The `python:3.9-slim-bullseye` might work instead of `python:3.9-slim` or may be `python:3.9-slim-buster` will work too. The official 3.9 image github update shows that the version is updated from `buster` to `bookworm`.

**Comment by jacobeturpin** [comment]
Can confirm that our builds were also impacted using `python:3.8-slim`. Modifying to `python:3.8-slim-bullseye` resolved the issue, so we're temporarily using that until the issue is resolved.

**Comment by TemaSM** [comment]
We're using `python:3.9.1` and confirming that our CI was broken by switching to `bookworm` (ref: #822).
<details>
  <summary>Gitlab CI output (stripped)</summary>

  ```shell
  ...
$ apt-get update && apt-get install -y postgresql-client
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 https://dl.google.com/linux/chrome/deb stable InRelease [1825 B]
Get:5 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1080 B]
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'oldstable' to 'oldoldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'oldstable' to 'oldoldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'oldstable-updates' to 'oldoldstable-updates'
$ createdb test
/bin/bash: line 147: createdb: command not found
...
  ```
  
</details>

**Comment by mitsuo0114** [comment]
Same here in out CI tool. I could solved with downgrading.

I'm assuming following change in Debian may have some affect to CI.
https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#python3-pep-668
---
5.2.2. Python Interpreters marked externally-managed
The Debian provided python3 interpreter packages (python3.11 and pypy3) are now marked as being externally-managed, following [PEP-668](https://peps.python.org/pep-0668/). The version of python3-pip provided in Debian follows this, and will refuse to manually install packages on Debian's python interpreters, unless the --break-system-packages option is specified.

If you need to install a Python application (or version) that isn't packaged in Debian, we recommend that you install it with pipx (in the pipx Debian package). pipx will set up an environment isolated from other applications and system Python modules, and install the application and its dependencies into that.
---

**Comment by aebm** [comment]
Hi, that is a "problem" with the change of the debian base image used. It seems related to seccomp and it is mentioned here https://github.com/debuerreotype/docker-debian-artifacts/issues/197#issuecomment-1590169930

Example (PS: Don't run you containers with more privileges that necessary =) )

```bash
docker run --name=dummy --rm -ti python:3.11-slim bash -c 'apt-get update && apt-get install -y less && echo OK'
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [28.3 kB]
Fetched 9180 kB in 2s (4697 kB/s)                         
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

vs

```bash
docker run --name=dummy --rm -ti --privileged python:3.11-slim bash -c 'apt-get update && apt-get install -y less && echo OK'
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [28.3 kB]
Fetched 9180 kB in 2s (4844 kB/s)                          
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  less
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 131 kB of archives.
After this operation, 321 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 less amd64 590-2 [131 kB]
Fetched 131 kB in 0s (3313 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package less.
(Reading database ... 8386 files and directories currently installed.)
Preparing to unpack .../archives/less_590-2_amd64.deb ...
Unpacking less (590-2) ...
Setting up less (590-2) ...
OK
```

**Comment by tianon** [comment]
The proper fix is updating libseccomp2 (and Docker/runc) on your host. :+1:

**Comment by yosifkit** [comment]
(basically the same comment as https://github.com/docker-library/redis/issues/365#issuecomment-1599633849)

Root cause: it is Docker with `libseccomp` so a newer syscall used in Debian Bookworm packages/libs is being blocked. (Thanks for confirming @aebm)

`libseccomp` lets you configure allowed syscalls for a process. Docker sets a default seccomp profile for all containers such that only certain syscalls are allowed and everything else is blocked (so, newer syscalls that are not yet known to `libseccomp` or `docker` are blocked).

- verify that it is `libseccomp` by running the Bookworm-based image with `--security-opt seccomp=unconfined`
  - use only as a test; it is less secure to keep running them "unconfined"
  - learn more: https://docs.docker.com/engine/security/seccomp/
- one fix:
  - update `libseccomp` and `docker` on the host running the containers
- one workaround:
  - switch to the `*bullseye` images (in the `python` images, these will continue to be maintained/updated until the respective Python end of life or the next Debian release, Debian Trixie)

**Comment by chazapp** [comment]
We've encountered this issue running docker builds on CircleCI runners using an old machine image (`ubuntu-2004:202101-01`). Updating the machine config to `ubuntu-2004:current` solved the issue for us.

**Comment by aporwal18** [comment]
Facing this same issue, any proper fix to this?

**Comment by yosifkit** [comment]
> Facing this same issue, any proper fix to this?

https://github.com/docker-library/python/issues/837#issuecomment-1599640563:

>   - update `libseccomp` and `docker` on the host running the containers

**Comment by davidt99** [comment]
I'm having this issue on Mac, on python 3.11. I have the latest docker installed, but `licseccomp` is not used in Mac as far as I know, any suggestions?

**Comment by k0d3r1s** [comment]
@davidt99 on mac I found a workaround: exit 0, so `apt-get update` becomes `bash -c "apt-get update; exit 0"`. probably not proper solution but it works for now

**Comment by ad-m-ss** [comment]
> I'm having this issue on Mac, on python 3.11. I have the latest docker installed, but `licseccomp` is not used in Mac as far as I know, any suggestions?

Docker on Mac usually uses Linux VM. Linux VM uses `libseccomp`.

**Comment by k0d3r1s** [comment]
which `libseccomp` version is required for this to be working?

**Comment by openbrian** [comment]
Just a comment here.  If you're running your builds in a dockerized Jenkins, for example, you'll also be using docker:dind (docker in docker).  You may need to upgrade docker here.  docker pull docker:dind

**Comment by skabbit** [comment]
I verify, that switching to `python:3.7-slim-buster` (or `python:3.7-buster` in my case) resolved this issue with NO_PUBKEY.

Also, faced this issue only while using `docker:18.09.7-dind` runner in CI/CD, but cannot reproduce it on docker v20.10.13 manually running docker cmd.

**Comment by mke21** [comment]
I've got this problem running in gitlab-ci with the worker running on a private Kubernetes cluster.  I'm not sure how to fix it apart from using the older bullseye image which obviously is a stopgap solution. This is the setup for the build:

``` yaml
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:stable-dind

image: docker:stable
```

**Comment by sergei-lobanov** [comment]
Any plans for a normal fix?

**Comment by tianon** [comment]
> Any plans for a normal fix?

https://github.com/docker-library/python/issues/837#issuecomment-1599631543

> The proper fix is updating libseccomp2 (and Docker/runc) on your host. 👍

**Comment by fgoura** [comment]
I am using python:3.11-slim for building my docker image and I am getting same error :

Reading package lists...
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481

Is this issue fixed in any slim version ?

**Comment by tianon** [comment]
No, the issue isn't caused by our images directly, so cannot be "fixed" in the images.  You need to update your host:

> > Any plans for a normal fix?
> 
> [#837 (comment)](https://github.com/docker-library/python/issues/837#issuecomment-1599631543)
> 
> > The proper fix is updating libseccomp2 (and Docker/runc) on your host. 👍

**Comment by fgoura** [comment]
Regarding the fix :
I tried installing the libseccomp2 but it says it is already on the latest version
```
libseccomp2 is already the newest version (2.5.4-1+b3).
libseccomp2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by tianon** [comment]
@anilrajrimal1 it's likely https://github.com/docker-library/official-images/issues/16829 (or a full disk, which might be the disk of a VM if you're on Docker Desktop or similar)
