### ISSUE TITLE
Adduser does not populate HOME anymore

### ISSUE THREAD

**Issue by dfioravanti** [docker-library/python#838]
Hi everyone,

I am not sure if this is a bug in the image, Debian or if it expected behaviour. I am using `python:3.11-slim` image. Until yesterday when I ran `adduser --system nonroot` it would populate `$HOME` with `/home/nonroot/`. Today I rebuilt the image and it is set to `/nonexistent`. Was this intentional or is it a bug? In case it helps both working and not working images are on `Bookworm`.

I cannot find any reference to this change anywhere but maybe I have missed something. If it was intentional I have to say that it absolutely breaks python's ability to find the root for the current user. In case it helps someone else, I switched to `useradd -m` and that fixed it

**Comment by lod** [comment]
The details for adduser creating home directories for system users changed between Debian Buster and Bookworm.
The behavior in both versions is detailed in their man pages.

If you are creating a user to execute container scripts as USER it really should be a normal user, not a system user.
Having a system user exist in /home/ would be rather weird, no other system user does that.

The change bug report is at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=679746

Behavior is described under the Add a system user heading
https://manpages.debian.org/buster/adduser/adduser.8.en.html
https://manpages.debian.org/bookworm/adduser/adduser.8.en.html

**Comment by tianon** [comment]
To put that another way, it wasn't something intentional in _this_ image, but rather a change in the underlying OS that has now been upgraded. :sweat_smile:

(Amusingly, `adduser` _almost_ didn't make it into what's installed by default for Bookworm, and probably won't be in Trixie, so I'd suggest planning accordingly either to install `adduser` explicitly in the future or to switch to `useradd` which is slightly lower level.)

**Comment by dfioravanti** [comment]
Yeah, I switched to `useradd`. To be honest if it did not make the cut it would have been better because the cause would have been obvious. Oh well, thanks for the suggestions.
