### ISSUE TITLE
Remove/freeze python 3.2

### ISSUE THREAD

**Issue by mattrobenolt** [docker-library/python#84]
Lots of python libraries are dropping support for python 3.2.

Specifically, `virtualenv` 14.0.0 (https://virtualenv.pypa.io/en/latest/changes.html) and `pip` 8.0.0 (https://pip.pypa.io/en/stable/news/).

`urllib3` has dropped 3.2: https://github.com/shazow/urllib3/pull/787 This means that `requests` (https://github.com/kennethreitz/requests) will be dropping 3.2 since it depends on `urllib3`.

So given that this is the trend, I propose we either remove 3.2 from here, or explicitly lock it so dependencies don't get updated like in #83.

**Comment by yosifkit** [comment]
:+1: We were planning to drop it once it hit end of life, which should be [February 2016](https://www.python.org/dev/peps/pep-0392/#lifespan).  So a freeze for now is perfectly reasonable.

**Comment by tianon** [comment]
Oh, EOL is literally next month -- why not just drop it?  Is there any way
to know whether a final "goodbye" release is planned?

**Comment by alex** [comment]
There's no final release planned to the best of my knowledge.

**Comment by tianon** [comment]
Cool, thanks @alex :heart:

Let's axe it. :+1:
