### ISSUE TITLE
python:3.7-slim: python 3.7.17 update is having issues on `netcat` package installation

### ISSUE THREAD

**Issue by epulla** [docker-library/python#842]
Hello there! 👋 

There was a [python version update](https://github.com/docker-library/python/commit/00b80a3dfc595e9c58ec52cc9ae8349cf10767a4#diff-b7f2739136da50c5c94c4e53d04af0e8b3328fdbe2b7a4c16957414beb2d867c) 2 weeks ago in the python:3.7 docker image about upgrading python version from `3.7.16` to `3.7.17` and for some reason, this last version (`3.7.17`) prevents me from installing the `netcat` package using the following dockerfile command:

```dockerfile
FROM public.ecr.aws/docker/library/python:3.7-slim
RUN set -ex \
  && apt-get update -yqq \
  && apt-get install -y -qq \
  --no-install-recommends \
  ...
  netcat \
  ...
```

Because I always get the following error:
```
E: Package 'netcat' has no installation candidate
```

Is there any reason that is causing this installation issue? I'll remain attentive to your comments, thanks!

P.S. I have to downgrade python docker image version (`3.7.16-slim`) to install `netcat` again.

**Comment by yosifkit** [comment]
The images that don't specify a specific Debian release (`*-bullseye`) recently upgraded from Debian Bullseye to Bookworm (the new Debian Stable).

You can choose to stay on the Bullseye based images by adding `-bullseye`. The `*-bullseye` images will continue to be maintained/updated until the respective Python end of life or the next Debian release, Debian Trixie. 

If you want to stay on the new Bookworm images, then the issue is just a change in packages in Bookworm in that you have to pick one now:

```console
$ docker run -it --rm python:3.7-slim bash
Unable to find image 'python:3.7-slim' locally
3.7-slim: Pulling from library/python
5b5fe70539cd: Already exists
f4b0e4004dc0: Pull complete
54839127b48b: Pull complete
cc32dd3f11d8: Pull complete
5202327b6b64: Pull complete
Digest: sha256:9e6385f10c1ba72abd94d9cc8f74ac96f719f95deefad8ad452740837928b43d
Status: Downloaded newer image for python:3.7-slim
root@dc834ccde32d:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [29.2 kB]
Fetched 9181 kB in 1s (8086 kB/s)
Reading package lists... Done
root@dc834ccde32d:/# apt-get install netcat
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package netcat is a virtual package provided by:
  netcat-openbsd 1.219-1
  netcat-traditional 1.10-47
You should explicitly select one to install.

E: Package 'netcat' has no installation candidate
root@dc834ccde32d:/#
```

**Comment by epulla** [comment]
Thanks for the clarification @yosifkit :) I will close this issue now.
