### ISSUE TITLE
Unable to do pip-sync

### ISSUE THREAD

**Issue by iamMohamed** [docker-library/python#853]
We ran our project in ECS and using ECR

Last month the build was a success but yesterday I triggered the build I got the below error, I made some research on this but I am unable to find the issue.
It's is helpful if I got some guidance.

#11 11.52 OK: 1157 MiB in 92 packages
--
263 | #11 11.86 Traceback (most recent call last):
264 | #11 11.86   File "/usr/local/bin/pip-sync", line 5, in <module>
265 | #11 11.86     from piptools.scripts.sync import cli
266 | #11 11.86   File "/usr/local/lib/python3.9/site-packages/piptools/scripts/sync.py", line 17, in <module>
267 | #11 11.86     from .. import sync
268 | #11 11.86   File "/usr/local/lib/python3.9/site-packages/piptools/sync.py", line 11, in <module>
269 | #11 11.86     from pip._internal.commands.freeze import DEV_PKGS
270 | #11 11.86 ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze' (/usr/local/lib/python3.9/site-packages/pip/_internal/commands/freeze.py)
271 | #11 ERROR: executor failed running [/bin/sh -c pip install "pip-tools<7.0"  && apk add --no-cache --virtual .build-deps     build-base     cargo     git     jpeg-dev     libffi-dev     libxslt-dev     postgresql-dev  && pip-sync  && apk del .build-deps  && pip uninstall -y pip-tools]: exit code: 1
272 | ------
273 | > [ 5/10] RUN pip install "pip-tools<7.0"  && apk add --no-cache --virtual .build-deps     build-base     cargo     git     jpeg-dev     libffi-dev     libxslt-dev     postgresql-dev  && pip-sync  && apk del .build-deps  && pip uninstall -y pip-tools:
274 | ------
275 | executor failed running [/bin/sh -c pip install "pip-tools<7.0"  && apk add --no-cache --virtual .build-deps     build-base     cargo     git     jpeg-dev     libffi-dev     libxslt-dev     postgresql-dev  && pip-sync  && apk del .build-deps  && pip uninstall -y pip-tools]: exit code: 1
276 |  
277 | [Container] 2023/07/18 13:11:25 Command did not exit successfully DOCKER_BUILDKIT=1 docker build --build-arg DJANGO_SENTRY_RELEASE="$IMAGE_TAG" --file Dockerfile.aws --progress=plain --cache-from $IMAGE_URI:latest --tag "$IMAGE_URI":"$IMAGE_TAG" .
278 | exit status 1
279 | [Container] 2023/07/18 13:11:25 Phase complete: BUILD State: FAILED_WITH_ABORT
280 | [Container] 2023/07/18 13:11:25 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: DOCKER_BUILDKIT=1 docker build --build-arg DJANGO_SENTRY_RELEASE="$IMAGE_TAG" --file Dockerfile.aws --progress=plain --cache-from $IMAGE_URI:latest --tag "$IMAGE_URI":"$IMAGE_TAG" .
281 | . Reason: exit status 1
282 |

**Comment by tianon** [comment]
I don't know what `pip-sync` is, but I don't think it's something we include in the image, right? :sweat_smile:

(The error message there sounds like this is something going wrong in `pip-sync` itself)

It's possible this is related to #835 (and friends) and is thus libseccomp related (proper fix being to update libseccomp2, runc, and Docker on your host, workaround being to switch to the `-bullseye` images explicitly), but I would've thought it'd fail sooner in that case.

**Comment by iamMohamed** [comment]
Hello @tianon I appreciate your thought, I thought that any batch update from the image side would cause the issue because it worked fine last week.
Thanks.

**Comment by ad-m-ss** [comment]
We may update `pip` version,  but this is still an issue of `pip-sync` of compatibility with official `pip` version. You can use `virtualenv` to downgrade & pin `pip` in the container if you need specific version.

**Comment by yosifkit** [comment]
Thanks for checking @ad-m-ss. I'll go ahead and close since it is fixed in the `pip-tools` package.
