### ISSUE TITLE
lzma module was not found in python:3-slim

### ISSUE THREAD

**Issue by fbrr** [docker-library/python#86]
When I try to import the module [lzma](https://docs.python.org/3/library/lzma.html):

```
Python 3.5.1 (default, Jan 13 2016, 18:56:49) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/lzma.py", line 26, in <module>
    from _lzma import *
ImportError: No module named '_lzma'
```
It seems that the library ```liblzma-dev``` is needed to build this module. See  [setup.py] (https://github.com/python/cpython/blob/master/setup.py#L1418) script.

**Comment by yosifkit** [comment]
Oh, that is supposed to work with the standard library :disappointed:.  Looks like we forgot `liblzma-dev` as one of the `buildDeps` (oh, and `xz-dev` on the alpine images too).  Luckily for the slim images, it looks like `liblzma5` is already installed so it shouldn't have much affect on the slim image size.

**Comment by fbrr** [comment]
Yes, the library is installed but the development library is required in order to build the module. When I build the slim image adding ```liblzma-dev``` in the dependencies, the module is constructed.

Unfortunately I have not tried with the other images.

**Comment by ushuz** [comment]
@fbrr @yosifkit I submitted a pull request #90 addressing this issue a couple weeks ago, any thoughts?

**Comment by fbrr** [comment]
Indeed, with these dependencies the module works!.

I guess this closes the issue. Thank you.

**Comment by foolswood** [comment]
I'm hitting this in alpine, would be nice to have the fix.

**Comment by answerquest** [comment]
how does one install this thing in a pipenv-created virtual environment?
