### ISSUE TITLE
new tags for alpine 3.18.3 release on dockerhub?

### ISSUE THREAD

**Issue by tooptoop4** [docker-library/python#860]

**Comment by yosifkit** [comment]
There won't be any new tags, but we automatically rebuild all dependent images when a parent image is updated. Since the Alpine update was merged (https://github.com/docker-library/official-images/pull/15156), so now all the Official Images `FROM` them will also be rebuilt.

**Comment by tooptoop4** [comment]
@yosifkit how long does it take to rebuild?
