### ISSUE TITLE
Missing `3.11.5-buster` image

### ISSUE THREAD

**Issue by johnthagen** [docker-library/python#863]
There is a [`3.11.4-buster`](https://hub.docker.com/layers/library/python/3.11.4-buster/images/sha256-35a9527e56796de39e7132531a63f13c97e77ea1ca182bd4dd47c3e4be11f466?context=explore) image published, but not a `3.11.5`.

Since 3.11.5 fixed some important security issues, we were hoping to use it:

- https://www.python.org/downloads/release/python-3115/

We target `buster` currently in order to package binaries that have a certain low GLIBC version that `buster` provides.

**Comment by yosifkit** [comment]
We only support two OS releases at a time for each Linux distribution that we support, so two Alpine and two Debian releases. Debian Buster based images were dropped when Debian Bookworm was added (https://github.com/docker-library/python/pull/822) and hasn't been updated since then.

**Comment by johnthagen** [comment]
Understood. 😢
