### ISSUE TITLE
Python 3.12-rc [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chebbah05028** [docker-library/python#865]
**my input is
dockerfile :

```
# syntax=docker/dockerfile:1
FROM python:3.12-rc

WORKDIR /home/myname/kubectl/ex_docker/ex1/

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./main.py" ]
```

my project directory is "/home/myname/kubectl/ex_docker/ex1/src"
my project file name is "main.py" It contains : 

```
import sys 

print("welcome from my container")
print("My Python version is {}".format(sys.version))

```
Then the command was run
docker run -it --rm --name my-running-script -v "$PWD":"$PWD"/src -w "$PWD"/src python:3.12-rc python main.py
 Output Error : 
python: can't open file '/home/myname/kubectl/ex_docker/ex1/main.py': [Errno 2] No such file or directory

docker image is : 

```
```
        REPOSITORY        TAG       IMAGE ID       CREATED             SIZE
        mypy              latest    d7ff3ea4100e   About an hour ago   1.02GB
        getting-started   latest    62e21984a96d   15 hours ago        268MB
        python            3.12-rc   46330068bf60   8 days ago          1.02GB
        <none>            <none>    22c957c35e37   3 weeks ago         1.01GB
        hello-world       latest    9c7a54a9a43c   4 months ago        13.3kB
```

```

**

**Comment by chebbah05028** [comment]
The issue was resolved using the following link: https://www.geeksforgeeks.org/how-to-run-a-python-script-using-docker/

**Comment by chebbah05028** [comment]
The issue was resolved using the following link: https://www.geeksforgeeks.org/how-to-run-a-python-script-using-docker/

**Comment by LaurentGoderre** [comment]
Awesome! Glad it works for you now!
