### ISSUE TITLE
3.12 for buster?

### ISSUE THREAD

**Issue by samruddhikhandale** [docker-library/python#870]
Hi 👋 

Thank you for adding support for `3.12` python so quick ✨ 

Would you be adding a support for the `buster` variant? Thanks

**Comment by ad-m-ss** [comment]
Debian buster does not have security support ( https://endoflife.date/debian ).

**Comment by yosifkit** [comment]
We generally only create `python` images for the two most recent releases of the distributions that we build for. So, currently that ends up being Debian Bookworm and Bullseye and Alpine 3.18 and 3.17.

Related: https://github.com/docker-library/python/issues/863

**Comment by samruddhikhandale** [comment]
Great, thanks for the information!
