### ISSUE TITLE
Package libavformat was not found in the pkg-config search path

### ISSUE THREAD

**Issue by gugaucb** [docker-library/python#871]
The last update remove the libavformat package. When I try install the av lib, I received the error below. Is it possible include the libavformat package again in the image?

24.75   Downloading av-10.0.0.tar.gz (2.4 MB)
24.84      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 25.7 MB/s eta 0:00:00
24.94   Installing build dependencies: started
26.70   Installing build dependencies: finished with status 'done'
26.71   Getting requirements to build wheel: started
26.88   Getting requirements to build wheel: finished with status 'error'
26.88   error: subprocess-exited-with-error
26.88   
26.88   × Getting requirements to build wheel did not run successfully.
26.88   │ exit code: 1
26.88   ╰─> [11 lines of output]
26.88       Package libavformat was not found in the pkg-config search path.
26.88       Perhaps you should add the directory containing `libavformat.pc'
26.88       to the PKG_CONFIG_PATH environment variable
26.88       Package 'libavformat', required by 'virtual:world', not found
26.88       Package 'libavcodec', required by 'virtual:world', not found
26.88       Package 'libavdevice', required by 'virtual:world', not found
26.88       Package 'libavutil', required by 'virtual:world', not found
26.88       Package 'libavfilter', required by 'virtual:world', not found
26.88       Package 'libswscale', required by 'virtual:world', not found
26.88       Package 'libswresample', required by 'virtual:world', not found
26.88       pkg-config could not find libraries ['avformat', 'avcodec', 'avdevice', 'avutil', 'avfilter', 'swscale', 'swresample']
26.88       [end of output]

**Comment by LaurentGoderre** [comment]
As a default stance, we try to follow what the underlying distro and technology do their release and as such we don't include additional packages in base images.

**Comment by yosifkit** [comment]
Sounds similar to https://github.com/docker-library/python/issues/836?  Did you perhaps move from a `bullseye` image to the `bookworm` based image?
