### ISSUE TITLE
LANG C.UTF-8 issue status?

### ISSUE THREAD

**Issue by nfantone** [docker-library/python#887]
I've noticed that almost every image on here has these lines defined:

```docker
# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8
```

It looks like the [linked issue was closed back in 2017](https://github.com/python/cpython/issues/64045#issuecomment-1093637237) and it might not be relevant anymore. I'm curious: are there any particular reasons to keep this around?

**EDIT**: Just saw that there was [a failed attempt to remove `LANG` before](https://github.com/docker-library/python/pull/570) — however, the cause of those errors seems unclear and we're still linking to an issue that has been closed/resolved for several years.

**Comment by LaurentGoderre** [comment]
@tianon @yosifkit I wonder if we can try removing it to 3.13 since it's in a RC state. If it works we can just keep it for versions prior to 3.13

**Comment by tianon** [comment]
Yeah, we should probably update to link to the latest failed attempt to remove it (https://github.com/docker-library/python/pull/570, I think).  The failures there make me very hesitant to try again without concrete evidence that we won't create similar problems again.
