### ISSUE TITLE
include python-gdb.py in base containers

### ISSUE THREAD

**Issue by jennolsen84** [docker-library/python#89]
This file is relatively small, but helps a lot while debugging with gdb.  Even if it is compressed, it would help a lot!

It is in `/usr/src/python` before it gets wiped.  Will you accept a PR if I submit one?

https://docs.python.org/devguide/gdb.html#gdb-7-and-later

**Comment by tianon** [comment]
Sorry for the delay!  If there's a simple way we can help enable `gdb` usage, I'm definitely +1!

Does `gdb`'s "auto-load-safe-path" have a default value we could take advantage of?

**Comment by heckad** [comment]
Any updates on this?

**Comment by tianon** [comment]
Still blocked on figuring out _how_ we can enable it safely/reliably -- if you've got something working, sharing it would be helpful. :sweat_smile:
