### ISSUE TITLE
Python 3.12.1 released

### ISSUE THREAD

**Issue by daveisfera** [docker-library/python#893]
https://www.python.org/downloads/release/python-3121/

**Comment by yosifkit** [comment]
It was picked up by the automated update job: https://github.com/docker-library/python/commit/ab3d095cb74ee82f11b6dc59f113ad01b60d41c1.  

https://github.com/docker-library/python/tree/ab3d095cb74ee82f11b6dc59f113ad01b60d41c1#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet, so https://github.com/docker-library/official-images/pull/15866
