### ISSUE TITLE
python:3.8 missing pub key?

### ISSUE THREAD

**Issue by queglay** [docker-library/python#894]
In the python:3.8 image, $HOME/.ssh/id_rsa exists but there is no pub key.

I'm not sure why only one would be there.  Shouldn't the private key be removed in any case?

**Comment by tianon** [comment]
https://explore.ggcr.dev/?image=python:3.8
-> `amd64` image https://explore.ggcr.dev/?image=python@sha256:3c3270c231ce82b081e2527c60734395b951c0d0c8b9e6b3a3caa515a701b73a&mt=application%2Fvnd.docker.distribution.manifest.v2%2Bjson&size=2007
-> "layers" https://explore.ggcr.dev/layers/python@sha256:3c3270c231ce82b081e2527c60734395b951c0d0c8b9e6b3a3caa515a701b73a/
-> both `/home` and `/root` do not have any `.ssh` directory anywhere I can see :sweat_smile:

Can you be more specific about where in the image you found this SSH key? :thinking:

**Comment by queglay** [comment]
You are right, I apologise when I checked first line this isn't there so it must be coming from something else!
