### ISSUE TITLE
Vulnerability in Python 3.10 (setuptools inside ensurepip folder)

### ISSUE THREAD

**Issue by bhupendra-vaishnav** [docker-library/python#901]
We are working on Python 3.10 and found vulnerable version of setuptools package which is setuptools-65.5.0.

We did see Python 3.10 already has a fix for setuptools package and updated version of setuptools package which is setuptools-65.5.1. Though while doing analysis, we found the traces of vulnerable version inside `ensurepip` folder. 

Please refer absolute file paths highlighted by blue in attached screenshot : 

<Attach image>
<img width="783" alt="Screenshot 2024-01-19 at 3 49 22 PM" src="https://github.com/docker-library/python/assets/148317470/921dfd8f-71ac-453b-b58f-2cb474b90c28">

Vulnerability reference : https://github.com/advisories/GHSA-r9hx-vwmv-q579

CC: @samruddhikhandale, @eljog, @gauravsaini04

**Comment by samruddhikhandale** [comment]
> ./usr/local/lib/python3.10/ensurepip/_bundled/setuptools-65.5.0-py3-none-any.whl

As `ensurepip` module is part of `pip`, does the Python image needs an update for the `pip` package as well?

We use the python image as base for the [dev container images](https://github.com/devcontainers/images) which are getting flagged with the [`setuptools` vulnerability.](https://github.com/advisories/GHSA-r9hx-vwmv-q579) in our scanners. 

We appreciate the quick fix for https://github.com/docker-library/python/pull/783, hoping to get this resolved as well. Thank you! 

// cc @tianon

**Comment by tianon** [comment]
The `ensurepip` module is part of Python's own stdlib (which is thus where this is coming from), not `pip` :sob:

**Comment by samruddhikhandale** [comment]
Hmmm. @tianon Is there any way to patch this? 🤔

**Comment by tianon** [comment]
I'm sure there's a way -- the best one would be for Python upstream to do new releases with the updated `setuptools` bundled (because this really isn't a Docker-specific problem -- it just looks like one because we seem to be one of the few parties publishing builds of their sources fairly "vanilla").  I don't know what the likelihood of that happening is, though.

For your builds, it would probably be pretty reasonable to purge the `ensurepip` module completely from your derivative images, but I must admit I don't know how common `ensurepip` is for users to actually use.

**Comment by samruddhikhandale** [comment]
> For your builds, it would probably be pretty reasonable to purge the ensurepip module completely from your derivative images, but I must admit I don't know how common ensurepip is for users to actually use.

Removing `ensurepip` could break the ability to bootstrap `pip` into new virtual environments created with `venv` (a tool for creating isolated Python environments), or other systems that rely on `ensurepip` to ensure `pip` is available. Hence, I don't think we should remove `ensurepip` from our images.

>  it just looks like one because we seem to be one of the few parties publishing builds of their sources fairly "vanilla"

@tianon Is the python image always build with latest builds of Python?  

@bhupendra-vaishnav can you raise this issue in https://github.com/python/cpython and ask them to update their `ensurepip` bundle?

**Comment by tianon** [comment]
Yep, we build from the latest published releases and try to keep any changes minimal.

See https://github.com/docker-library/python/blob/b273afc57978521d33fefe5887ad901d0d35de87/3.10/bookworm/Dockerfile for the current `Dockerfile` for `python:3.10`.

**Comment by edmorley** [comment]
I think this issue should be closed as wontfix, given that the fix should come from upstream (as the wheel in the ensurepip folder comes from upstream).
