### ISSUE TITLE
Consider including `uv` in images

### ISSUE THREAD

**Issue by hkad98** [docker-library/python#905]
I suggest including [uv](https://github.com/astral-sh/uv) in all Python image variants. `uv` is a Python package written in rust and blazingly fast. It comes from the creators of `ruff` (famous and fast Python linter).

**Comment by tianon** [comment]
While interesting, it's not included in Python by default (nor explicitly endorsed by Python upstream), whereas `pip` _is_, so unfortunately installing this is going to be left as an exercise for the reader unless/until that changes. :bow:

**Comment by hkad98** [comment]
@tianon, thanks for your reply. Hopefully, it will be included in Python by default soon.
