### ISSUE TITLE
python 2.7.18 alpine image based on broken musl version

### ISSUE THREAD

**Issue by gnurizen** [docker-library/python#916]
The python 2.7.18 alpine image based on alpine 3.11.5 has a broken ld-musl build.  Its using musl 1.1.24 r2 which has a busted crc link between the musl and musl-dbg package:

 msg="CRC checksum mismatch" exe=/proc/1698625/root/lib/ld-musl-x86_64.so.1:**b48ff764** debuglink=/proc/1698625/root/usr/lib/debug/lib/ld-musl-x86_64.so.1.debug:**cdfc8916**

alpine-3.11.8 doesn't have this problem, apparently musl 1.1.24 r3 fixed it:

`
/ # readelf -wk /lib/ld-musl-x86_64.so.1 
Contents of the .gnu_debuglink section:

  Separate debug info file: ld-musl-x86_64.so.1.debug
  CRC value: 0xcdfc8916
`

Not sure this rises to level of something that should be fixed or if that ship has sailed but thought it was worth mentioning.   Programs that rely on debug information for doing things like stack unwinding may be affected by this bug (ie http://github.com/parca-dev).

**Comment by yosifkit** [comment]
Closing because the `2.7` image is not supported. Python 2.7 has been "end of life" since Jan 2020.
