### ISSUE TITLE
Threading issues in python3.11 to python3.11.9-slim-bookworm

### ISSUE THREAD

**Issue by taylornelsonbluecargo** [docker-library/python#917]
We notice threading issues in our environment with the minor version upgrade

**Comment by collinc777** [comment]
Noticing the same thing here

**Comment by jackguac** [comment]
Yep - same problem. Gunicorn workers all crashing. I've downgraded to python3.10 image and all fine.

**Comment by tianon** [comment]
"threading issues" is not really enough for us to reproduce, let alone help diagnose :wink:

Does anyone have a minimal reproducer?

**Comment by yosifkit** [comment]
We didn't change any build flags or anything else (except likely some OS package updates from a rebuild) between `3.11.8` and `3.11.9`, so if there is an issue, it would be in `python` itself or a `pip` installed python package.

**Comment by LaurentGoderre** [comment]
Does this looks similar to your issues? https://github.com/benoitc/gunicorn/issues/2899

**Comment by jim-schwoebel** [comment]
having this issue as well, can reproduce on python v 3.11.6

**Comment by tianon** [comment]
> "threading issues" is not really enough for us to reproduce, let alone help diagnose 😉
> 
> Does anyone have a minimal reproducer?



> Does this looks similar to your issues? [benoitc/gunicorn#2899](https://github.com/benoitc/gunicorn/issues/2899)

**Comment by yosifkit** [comment]
If `-bullseye` works and `-bookworm` does not, that sounds like `libseccomp`: https://github.com/docker-library/python/issues/837#issuecomment-1599640563 and more generally, https://github.com/docker-library/official-images/issues/16829

**Comment by martin-thoma** [comment]
Switching from `python:3.11-slim-buster` to `python:3.11-slim-bookworm` I saw the same error message.

**Comment by yosifkit** [comment]
@martin-thoma, it is the libseccomp (and docker and containerd) of the host that you need to update, not anything in the container.

**Comment by martin-thoma** [comment]
Got it! Updating docker fixed the issue for me.

**Comment by edmorley** [comment]
This can presumably be closed out, given it was an outdated Docker issue?

> it is the libseccomp (and docker and containerd) of the host that you need to update, not anything in the container.

> Got it! Updating from docker 20 to docker 24 fixed the issue for me.
