### ISSUE TITLE
Python:3.11-slim-bookworm image still uses debian:12.0 but not 12.5

### ISSUE THREAD

**Issue by OlgasAcc** [docker-library/python#923]
There is already 2-months-old rebuilt image for the non-slim version of Python:3.11-bookworm (uses the latest debian:12.5).
Could you please rebuild the slim version image as well?

<img width="1367" alt="image" src="https://github.com/docker-library/python/assets/55320727/fc19afbb-6e40-491e-963d-0eb3593eac13">

Thanks

**Comment by tianon** [comment]
I can't reproduce: :thinking:

```console
$ docker run --rm --pull=always python:3.11-slim-bookworm cat /etc/debian_version
3.11-slim-bookworm: Pulling from library/python
Digest: sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c
Status: Image is up to date for python:3.11-slim-bookworm
12.5
```

**Comment by OlgasAcc** [comment]
> I can't reproduce: 🤔
> 
> ```
> $ docker run --rm --pull=always python:3.11-slim-bookworm cat /etc/debian_version
> 3.11-slim-bookworm: Pulling from library/python
> Digest: sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c
> Status: Image is up to date for python:3.11-slim-bookworm
> 12.5
> ```

Thanks @tianon, the image description in the Docker-hub has confused me. Thanks!
