### ISSUE TITLE
Support platform darwin/arm64

### ISSUE THREAD

**Issue by reneleonhardt** [docker-library/python#929]
The official Python image is amazing, thank you!

Would it be possible to provide builds for more platforms?
GitHub Actions can easily access [macos-latest](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) for example.
Docker buildx / BuildKit / containerd / Go support many platforms including `darwin/arm64`:
https://github.com/containerd/containerd/blob/v1.7.17/platforms/platforms.go#L96

I was able to easily compile scripts with Nuitka on platforms this base image already offers (like `linux/amd64` and arm64).
If python would also push `darwin/arm64` manifests then the Python ecosystem could offer native builds for more Desktop users.
In times of llama.cpp and DuckDB I think more possibilities to build native experiences are crucial for the community to spread forward into new territories and use cases.

**Comment by tianon** [comment]
Unfortunately, `darwin` is not supported in https://github.com/docker-library/official-images, and I'm not actually sure what it would even _mean_ for it to be. :thinking:

As far as I know, macOS containers are not currently (or planned to be) a thing.  I have seen several very clever/cute hacks over the years (with varying degrees of "macOS" behavior), but nothing that seemed like it was gaining much momentum. :see_no_evil:

**Comment by tianon** [comment]
Closing for now, as this is not something we plan to work on (and as I noted above, not something I even understand what it would _mean_ to work on, so more details are definitely required).
