### ISSUE TITLE
Docker Official Image python:<version>-alpine issue

### ISSUE THREAD

**Issue by cciradih** [docker-library/python#930]
From my observation, there is a problem with the image based on alpine 3.20⁠. I don't know the root cause, but it appears to cause the following errors:
```
Error relocating /usr/local/bin/../lib/libpython3.12.so.1.0: pwritev2: symbol not found
Error relocating /usr/local/bin/../lib/libpython3.12.so.1.0: preadv2: symbol not found
```
Downgrading to alpine 3.19 can solve this problem.

Use `FROM python:alpine3.19` instead of `FROM python:alpine`.

**Comment by LaurentGoderre** [comment]
I think this is a duplicate of #927

**Comment by cciradih** [comment]
https://github.com/docker-library/python/issues/930#issuecomment-2152582795

**Comment by cciradih** [comment]
https://github.com/docker-library/python/issues/930#issuecomment-2152582795
