### ISSUE TITLE
What is the image retention/removal policy?

### ISSUE THREAD

**Issue by martin-thoma** [docker-library/python#932]
Looking at https://github.com/docker-library/python/commit/7eefa0c4911bcf998ff5f880df51dc7f8bbf6dec I assume that Python images that reached their end of life (EOL) will be removed.

I guess the same is true for the Debian version.

Is it guaranteed that images will stay on Dockerhub until the EOL is reached?

**Comment by LaurentGoderre** [comment]
@martin-thoma removing them there doesn't remove them from the registry, only from the build system, which means they receive no further update even if the base image has updates.

**Comment by LaurentGoderre** [comment]
The debian repo still has a tag for Debian Squeeze last updated 8 years ago: https://hub.docker.com/layers/library/debian/squeeze/images/sha256-f028d90e41fbfc9e453c6df47fa4bf45b12314319788ddffd52e951ddc51ed29?context=explore

**Comment by martin-thoma** [comment]
Thanks for the clarification :+1: 

But when are images removed from the registry?

**Comment by tianon** [comment]
It's not guaranteed, but our policy thus far has been to avoid removing any old content unless there's an overriding concern (maintainer request, etc).
