### ISSUE TITLE
Media type for `python:3.10-slim-bookworm` changed to `"application/vnd.oci.image.index.v1+json"`

### ISSUE THREAD

**Issue by ahpd** [docker-library/python#936]
In the past week or so the media type for `python:3.10-slim-bookworm` has changed to `"application/vnd.oci.image.index.v1+json"`. I believe it used to be `"application/vnd.docker.distribution.manifest.list.v2+json"` which is what the [base image](https://github.com/docker-library/python/blob/9602fc7493ee0d09c124a05553aadee142992df8/3.10/slim-bookworm/Dockerfile#L7) `debian:bookworm-slim` shows: 

```
➜ docker manifest inspect debian:bookworm-slim | head                             
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:39868a6f452462b70cf720a8daff250c63e7342970e749059c105bf7c1e8eeaf",
         "platform": {
            "architecture": "amd64",

➜ docker manifest inspect python:3.10-slim-bookworm | head
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1944,
         "digest": "sha256:8244f266195f442379acd0e7d8918b1ef3967050ebf49c40291e89d0a1ba8f94",
         "platform": {
            "architecture": "amd64",
```

Is this intended and if so what was the reason for changing the media types? We currently have several Vertex AI pipelines that use the Python images which are failing due to this issue 
```json
{
	"errors": [{
		"code": "MANIFEST_UNKNOWN",
		"message": "Manifest has media type \"application/vnd.oci.image.manifest.v1+json\" but client accepts [\"application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws\"]"
	}]
}
```
Thank you.

**Comment by jonjohnsonjr** [comment]
I'd file an issue against Google.

**Comment by yosifkit** [comment]
Yes, this was intentional. We are in a slow, but active process of migrating all of Official Images builds from the classic `docker build` to the `docker build` backed by buildkit. Python is one that was added recently. Many of the images in Docker Official Images are now built using buildkit and use these "newer" `oci` media types; eventually all of them will be.

More about the OCI: https://opencontainers.org/

**Comment by ahpd** [comment]
Got it, thank you for the explanation.
