### ISSUE TITLE
python:3 Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by kavyakul** [docker-library/python#95]
Hi,
I am running docker image python:3 to run a python script as follows
_docker run -it --rm  --name alert -p 8955:8955 -v "$PWD":/usr/src/myapp -w /usr/src/myapp  python:3 python ./main.py <ARGUMENTS>_

**Inside container:**
 I can access web URL: http://localhost:8955/metrics

**On host:**
 I cannot access URL: using localhost/0.0.0.0/127.0.0.1 , it gives me below error
`[dockeradmin@vmh-qlhlido20-test1 server]$  curl -vv http://localhost:8955/metrics
* About to connect() to localhost port 8955 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8955 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8955
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer`

**while using Host IP, I get:**
` curl -vv http://IP:8955/metrics
* About to connect() to IPport 8955 (#0)
*   Trying IP...
* Connection refused
* Failed connect to IP:8955; Connection refused
* Closing connection 0
curl: (7) Failed connect to IP:8955; Connection refused
`

**docker version**
Client:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

**docker inspect --format '{{ .NetworkSettings.IPAddress }}' alert**
172.17.0.202

Please help to let me know how can it be corrected

**Comment by yosifkit** [comment]
My only thought is that your python app is only listening on `localhost`/`127.0.0.1`.  In that case it would be inaccessible outside that container.
