### ISSUE TITLE
Python 3.12.6 automated version bump missing

### ISSUE THREAD

**Issue by edmorley** [docker-library/python#960]
Late on Friday, a number of Python security updates were released:
https://blog.python.org/2024/09/python-3130rc2-3126-31110-31015-3920.html

The version bumps for most of those were pushed by the automation on Sat:
https://github.com/docker-library/python/commits/master/

For example:
https://github.com/docker-library/python/commit/b4ded1bb3966d489d8f98b829beb40c4eff8202d

However, notably the bump for 3.12 to 3.12.6 is missing.
Did the automation job for that one fail - and now needs retriggering? (I don't know where these version bump jobs run and how to find the logs for them)

(Context: This blocks me being able to rebase #955, but also will hold up the eventual release of these security updates in the PR to https://github.com/docker-library/official-images)

**Comment by jnoordsij** [comment]
Looks like the automated `update.sh` job is failing for v3.12; see also https://doi-janky.infosiftr.net/job/update.sh/job/python/.

Or to be more precise, the `python-hy` test is failing:
```
	'python-hy' [4/9]...WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/funcparserlib/
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 8, in <module>
    sys.exit(hy_main())
             ^^^^^^^^^
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
TypeError: exec() arg 1 must be a string, bytes or code object
failed
```

Given that this was recently altered in https://github.com/docker-library/official-images/commit/4c92a2d5c530d5f84e0e3b7e4ecc45778eb212b7, it's probably time to ping @tianon ;)

**Comment by tianon** [comment]
Yeah, this is https://github.com/hylang/hy/issues/2598 :disappointed: (I saw it over there over the weekend, but hadn't got back here yet to see how it affects us)

**Comment by tianon** [comment]
I think the easiest fix here is to do the bump manually this time and ignore that failing CI, and hope that https://github.com/hylang/hy/pull/2599 gets into a release soon :smile:

We can also update the test to exclude 3.12 for now (which is similarly sane).

**Comment by tianon** [comment]
> We can also update the test to exclude 3.12 for now (which is similarly sane).

Done in https://github.com/docker-library/official-images/commit/8a8969b7e73edd3b714cf51253888b739217e1e6

**Comment by tianon** [comment]
https://github.com/docker-library/python/commit/ceb2ec17e8c168a574d0430d394d0e05544693df -> https://github.com/docker-library/official-images/pull/17521 :+1:
