### ISSUE TITLE
python 3.11 windows image

### ISSUE THREAD

**Issue by windelbouwman** [docker-library/python#968]
Hi,

I used a python 3.11 windows image in the past, but I noticed that this was removed? What is the policy for windows images?

Best regards,
Windel

**Comment by tianon** [comment]
They didn't explicitly call it out in the 3.11 release notes / announcement post, but 3.11 is now in "security-fix-only mode" and that means it no longer gets Windows and macOS installers.

Here's an example where they've called it out explicitly for 3.10.11:

> The final regular bugfix release for Python 3.10! It is now entering security-fix-only mode. This also means this is the last version for which we will ship Windows and macOS installers. If you rely on these binary releases, it's time to upgrade to Python 3.11.

See also the "No installers" section of https://www.python.org/downloads/release/python-31110/

> According to the release calendar specified in [PEP 664](https://peps.python.org/pep-0664/), Python 3.11 is now in the "security fixes only" stage of its life cycle: 3.11 branch only accepts security fixes and releases of those are made irregularly in source-only form until October 2027. Python 3.11 isn't receiving regular bug fixes anymore, and binary installers are no longer provided for it. Python 3.11.9 was the last full bugfix release of Python 3.11 with binary installers.
