### ISSUE TITLE
Is PROFILE_TASK actually used in the Dockerfile?

### ISSUE THREAD

**Issue by RobertDeRose** [docker-library/python#979]
I see that in the history of the linux template, that PROFILE_TASK was specifically set to a value and used across both invocation of `make`. However, I downloaded the 3.12.7 and 3.13.0 Dockerfiles to understand what it going on, and I enabled Docker's full logging and noticed that the profiling step does not get invoked.

It appears that this variable is now `""` and then the Makefile just skips the step, thus essentially disabling the `--enabled-optimization` flag.

If someone could just confirm my findings and ensure I am not missing something, that would be awesome.

Thanks!

**Comment by yosifkit** [comment]
Doh, yeah that is causing it to skip the optimizations 😢. Now that none of the python versions need it, we can just drop it out of the template and apply the results (rather than having to conditionalize it in the template). Looks like it was missed when PROFILE_TASK was moved around in https://github.com/docker-library/python/pull/794.

**Comment by edmorley** [comment]
Wouldn't the `test -z` here ignore `PROFILE_TASK` if set to the empty string, and so continue to use the default task in that case?
https://github.com/python/cpython/blob/37e533a39716bf7da026eda2b35073ef2eb3d1fb/configure.ac#L1905

**Comment by edmorley** [comment]
(but either way, passing in `PROFILE_TASK` is dead code now and can be removed :-) )

**Comment by yosifkit** [comment]
Yeah, but we're setting for the `make` invocation, which doesn't look for empty

https://github.com/docker-library/python/blob/7666104c8091d2b89ab13df6117d2399ab13fdbf/3.13/bookworm/Dockerfile#L53-L56

https://github.com/python/cpython/blob/37e533a39716bf7da026eda2b35073ef2eb3d1fb/Makefile.pre.in#L330

**Comment by RobertDeRose** [comment]
Oh, glad I am not crazy, I can open a PR for this.

**Comment by yosifkit** [comment]
That'd be great. Thank you!
