### ISSUE TITLE
python:3.11-slim-bookworm can't apt-install chromium

### ISSUE THREAD

**Issue by tbliu** [docker-library/python#991]
Hi! I started running into docker build issues with apt-installing chromium today using the python:3.11-slim-bookworm base image.

Basic steps to reproduce:
```Dockerfile
FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -fy chromium
```

`docker build .` outputs
```
STEP 1/2: FROM python:3.11-slim-bookworm
STEP 2/2: RUN apt-get update && apt-get install -fy chromium
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8789 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2712 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [214 kB]
Fetched 9260 kB in 3s (3636 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 chromium : Depends: libc++1-19 (>= 1:19.1.4) but it is not installable
            Depends: libc++abi1-19 (>= 1:19.1.4) but it is not installable
            Depends: libunwind-19 (>= 1:19.1.4) but it is not installable
            Depends: chromium-common (= 131.0.6778.108-1~deb12u1) but it is not going to be installed
            Recommends: chromium-sandbox but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Error: building at STEP "RUN apt-get update && apt-get install -fy chromium": while running runtime: exit status 100
```

Tried seeing if I could patch the missing dependencies here but no luck.

I did find that slim-bullseye is able to install chromium though:
```Dockerfile
FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -fy chromium
```

I just started encountering this issue today--it was working fine earlier this week, so any help or guidance here would be appreciated!

**Comment by Xevelopy** [comment]
Faced a similar issue today but it seems to be a general issue with Debian Bookworm and Chromium.

Debian is aware of this and already checks on how they can handle the situation. 
There should be a fix soon.

What could be done is adding the bookworm-proposed-updates to your /etc/apt/sources.list through docker file and then do a apt dist-update.

That worked for me but be aware that this action leads to removal of libc++1-16, libc++abi1-16, libunwind-16
and install libc++1-19, libc++abi1-19, libunwind-19

Information is from this Bugreport: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1089182

**Comment by tbliu** [comment]
Yup, this works for me. Thanks!
